- openfisca_france/tests/fiche_de_paie/coordinatrice1_2014_03.py
- openfisca_france/tests/fiche_de_paie/ingenieur_ssii1_2013_08.py
- openfisca_france/tests/test_fiche_de_paie.py
Check TODO in ingénieur fiche de paie
> New test for fiche de paie

- openfisca_france/model/aides_logement.py
- openfisca_france/model/impot_revenu/ir.py
- openfisca_france/model/input_variables/base.py
- openfisca_france/model/minima_sociaux/cmu.py
- openfisca_france/model/pfam.py
- openfisca_france/param/param.xml
pour la maj des loyers plafonds dans param.xml, voir l'arrêté http://www.legifrance.gouv.fr/affichTexte.do;jsessionid=967256EBE100E2D0D3DBD1C6F54AEE80.tpdjo15v_2?cidTexte=JORFTEXT000029555804&dateTexte=20141231
Un doute sur la date d'entrée en vigueur : soit 1er octobre soit 10 octobre...
> avancements équipe mes-aides

- openfisca_france/model/minima_sociaux/cmu.py
- openfisca_france/param/param.xml
vu et validé avec Jérôme ce matin
> corrige formule cmu base ressources, montants annuels

- CONTRIBUTING.md
Ensure the warning will [appear in GitHub's GUI](https://help.github.com/articles/setting-guidelines-for-repository-contributors/).
> Document commit messages rules

- openfisca_france/model/aides_logement.py
Last commit before erasing this now ill-named branch
> Add analysis:ignore for pep8 parsing

- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/apprentissage.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/tests/formulas/remuneration_apprenti_bad.yaml
- openfisca_france/tests/test_apprentissage.py
Introduces apprenti
Introduces apprentissage_contrat_debut
Introduces remuneration_apprenti
> Apprentissage

- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/model/prestations/prestations_familiales/cf.py
- openfisca_france/param/param.xml
* Réécriture du Complément Familial
* Introduction du Complément Familial majoré
* Mise à jour des plafonds des prestations familiales sous conditions de ressources (1er janvier 2015)
* Revalorisation des minima sociaux (1er avril 2015)
Passe les tests mes-aides.
> Complément familial majoré et revalorisation des minima sociaux

- openfisca_france/model/prestations/minima_sociaux/cmu.py
- openfisca_france/model/revenus/autres.py
Ajout de la colonne pensions_alimentaires_versees
> Abattement en cas de pension alimentaire versée pour la CMU et l'ACS

- openfisca_france/param/param.xml
Fixes https://github.com/sgmap/openfisca-france/issues/1
Tested locally
> Revalorisation plafonds ASS

- openfisca_france/model/caracteristiques_socio_demographiques/logement.py
- openfisca_france/model/prestations/prestations_familiales/cf.py
- openfisca_france/param/param.xml
* Éligibilité spécifique
* Plafond spécifique
* Montant spécifique
> Implémentation du Complément Familial pour les DOM

- openfisca_france/model/prestations/prestations_familiales/af.py
- openfisca_france/model/prestations/prestations_familiales/base_ressource.py
- openfisca_france/param/param.xml
Introduce af_enfant_a_charge
Introduce af_eligibilite_base
Introduce af_eligibilite_dom
Introduce af_age_aine
Introduce af_majoration_enfant
> Refonte des allocations familiales et ajout des DOM

- openfisca_france/param/param.xml
Fixes https://github.com/sgmap/openfisca-france/issues/4
> Mise a jour cotisations sociales pour les autoentrepreneurs

- openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
This partially revert commit "Fix allocation naissance de la PAJE"
3afbd794909fc5672ae2a7e6c6ebe600e5e7ff08.
#	openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
> Switch back to salaire_brut and  rstbrut in ASI-ASPA

- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
- openfisca_france/tests/fiches_de_paie/apprenti.yaml
- openfisca_france/tests/fiches_de_paie/salarie_montaigne_2014-01.yaml
@eraviart, @MattiSG @cbenz @jdesboeufs 
Some tests are still failing. Some of them are related to allocations familiales brutes ou nettes de CRDS.
Stagiaire might be wrong too (working from the train).
> Fix some apprenti related tests

- openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
- openfisca_france/model/prestations/minima_sociaux/cmu.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/model/revenus/activite/non_salarie.py
Big refactor for TNS
Change is the way RSA is computed
> Tns refactor

- openfisca_france/model/prestations/minima_sociaux/cmu.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/model/prestations/prestations_familiales/paje.py
Prestation partagée d'éducation de l'enfant
Connected to https://github.com/sgmap/mes-aides-ui/issues/61
> Introduce PreparE

- openfisca_france/model/caracteristiques_socio_demographiques/logement.py
- openfisca_france/model/prestations/aides_logement.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/model/revenus/activite/non_salarie.py
- openfisca_france/param/param.xml
- openfisca_france/tests/formulas_mes_aides/aide_logement_non_calculable.yaml
- openfisca_france/tests/formulas_mes_aides/rsa_eligibilite_tns.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_5451169b31061e1c4a8da349.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_553fa8b7301cd06239697158.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_553fbd0e301cd062396971ce.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_553fc13246bea9643939512b.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_5540d62546bea96439395305.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_5540d71646bea9643939530f.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_555aff483b9f6b603184d3a8.yaml
Connected to https://github.com/sgmap/mes-aides-ui/issues/36
Connected to https://github.com/sgmap/mes-aides-ui/issues/48
> Tns agricoles et autres

- openfisca_france/model/prestations/minima_sociaux/cmu.py
paje_clca et paje_prepare sont des inputs, il ne faut pas les estimer en multipliant par 12
> Fix bug CLCA compté en double

- openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
- openfisca_france/param/param.xml
Connected to sgmap/openfisca-france#13
> Invalidité > 50% nécessaire pour bénéficier de l'ASPA à 62 ans

- openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
- openfisca_france/param/param.xml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_54e4c0bffb31b85d4074fe15.yaml
Follows @benjello 's comment on #261 
Depends on https://github.com/sgmap/mes-aides-api/pull/22
> Change taux_invalidite_aspa_anticipe to decimal

- openfisca_france/model/prestations/minima_sociaux/ass.py
- openfisca_france/tests/formulas_mes_aides/ass_abbattement.yaml
Connected to sgmap/openfisca-france#19
> Neutraliser le salaire d'activitié partielle interrompue dans la BR de l'ASS

- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/model/revenus/activite/salarie.py
Connected to sgmap/mes-aides-ui#77
> Neutralisation forfaitaire des revenus non pros pour la BR RSA

- openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
- openfisca_france/model/prestations/minima_sociaux/cmu.py
> Use numpy abs

- openfisca_france/reforms/allocations_familiales_imposables.py
Change calculate to calculate_add to appropriate variables.
> small correction to allocations familiales imposables (calculate_add)

- openfisca_france/tests/test_allegement_fillon.py
Test show how to fix #267
Allgement fillon are calculated on yearly basis and you should provide the wages for the entire year
> One more test for allegement_fillon

- openfisca_france/model/prestations/minima_sociaux/cmu.py
Sinon Openfisca crashe dans certaines situations
> Fix small bug in cmu_base_ressources_i

- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
- openfisca_france/param/param.xml
- openfisca_france/param/parameters.xml
Rename bareme viellessedeplaf to vieillesse_deplafonnee
> Rename bareme viellesseplaf to vieillesse_plafonnee

- openfisca_france/param/param.xml
- openfisca_france/tests/embauche.sgmap.fr/test_embauche_55c1dbb46149d1903b3d1e27.yaml
- openfisca_france/tests/embauche.sgmap.fr/test_embauche_55c20c8d6149d1903b3d20a4.yaml
- openfisca_france/tests/embauche.sgmap.fr/test_embauche_55c20f536149d1903b3d2129.yaml
- openfisca_france/tests/embauche.sgmap.fr/test_embauche_55c224446149d1903b3d21ae.yaml
- openfisca_france/tests/embauche.sgmap.fr/test_embauche_55c227796149d1903b3d2233.yaml
- openfisca_france/tests/formulas/salsuperbrut.yaml
Source: http://travail-emploi.gouv.fr/informations-pratiques,89/fiches-pratiques,91/remuneration,113/l-allegement-de-charges-patronales,1031.html
Should fix sgmap/cout-embauche#29.
@benjello Can you please review this?  :)
> Update plafonds for fillon

- openfisca_france/model/prestations/aides_logement.py
Split aide_logement_montant_brut in sub-functions to make this formula more readable.
> Refactor aide_logement_montant_brut

- openfisca_france/reforms/plf2015.py
- openfisca_france/tests/reforms/test_plf2015.py
plf_2015 is now applied to revenus 2013.
Tests are changed accordingly.
> Test plf2015

- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- openfisca_france/param/param.xml
- openfisca_france/reforms/plf2015.py
- openfisca_france/tests/base.py
- openfisca_france/tests/formulas/irpp.yaml
Import reforms/plf2015.py into hard coded legislation. Tests for the reform not implemented.
> Decote 2015

- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- openfisca_france/tests/formulas/irpp.yaml
implement true_decote that is the decote amount provided by dgfip  (at least on their simulator)
which is the fiscal gain accountable to the decote mechanism.
> implement true_decote that is the decote amount provided by dgfip

- openfisca_france/model/prestations/aides_logement.py
- openfisca_france/param/param.xml
- openfisca_france/param/parameters.xml
- openfisca_france/tests/formulas/aides_logement.yaml
@benjello, j'ai supprimé des références à `D_enfch` qui semblaient ne pas avoir leur place dans `openfisca-france`. Dis moi si ça pose problème. 
Connected to sgmap/mes-aides-ui#169
> Al enfants handicapes

- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
- openfisca_france/param/param.xml
- openfisca_france/tests/formulas/arrco.yaml
Fixing embauche bugs [114](https://github.com/sgmap/cout-embauche/issues/114) and [17](https://github.com/sgmap/cout-embauche/issues/17).
Respectively these ludwig tests : 
http://embauche.sgmap.fr/tests/55c4838b6149d1903b3d3e5c/show
http://embauche.sgmap.fr/tests/55c382a46149d1903b3d2d82/show
> Arrco bugs for second tranche

- openfisca_france/model/base.py
- openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
- openfisca_france/model/caracteristiques_socio_demographiques/logement.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/stage.py
- openfisca_france/model/prestations/education.py
- openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/model/prestations/prestations_familiales/paje.py
- openfisca_france/model/revenus/activite/non_salarie.py
- openfisca_france/model/revenus/activite/salarie.py
- openfisca_france/model/revenus/capital/financier.py
- openfisca_france/model/revenus/capital/foncier.py
- openfisca_france/model/revenus/remplacement/chomage.py
- openfisca_france/model/revenus/remplacement/retraite.py
- openfisca_france/reforms/aides_cd93.py
- openfisca_france/reforms/aides_ville_paris.py
- openfisca_france/reforms/inversion_revenus.py
Migration following https://github.com/openfisca/openfisca-core/pull/365
Depends on #367
> Uniformize variable declaration

- openfisca_france/param/param.xml
I'm surprised this doesn't break tests.
> Update plafond de la sécurité sociale

- openfisca_france/param/param.xml
- openfisca_france/tests/formulas/exoneration_cotisations_employeur_zrd.yaml
Revalorisation du SMIC, thanks to @HelaG :)
> Update SMIC horaire brut 2016

- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- openfisca_france/tests/formulas/irpp_cehr.yaml
cehr en dated formulas.
Put some yaml test on it.
> "cehr" becomes a DatedVariable

- openfisca_france/__init__.py
- openfisca_france/decompositions/decomp.xml
- openfisca_france/decompositions/decomp_contrib.xml
- openfisca_france/decompositions/decompositions-multiples.xml
- openfisca_france/decompositions/fiche_de_paie_decomposition.xml
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
- openfisca_france/model/revenus/activite/salarie.py
- openfisca_france/scripts/web_trace.py
- openfisca_france/tests/fiches_de_paie/TEMPLATE.yaml
- openfisca_france/tests/fiches_de_paie/apprenti.yaml
- openfisca_france/tests/fiches_de_paie/assistant_emission_2014-01.yaml
- openfisca_france/tests/fiches_de_paie/business_develop_2015-02.yaml
- openfisca_france/tests/fiches_de_paie/coordinatrice_2014-03.yaml
- openfisca_france/tests/fiches_de_paie/ingenieur_etude_2014-07.yaml
- openfisca_france/tests/fiches_de_paie/ingenieur_ssii_2013-08.yaml
- openfisca_france/tests/fiches_de_paie/salarie_montaigne_2014-01.yaml
- openfisca_france/tests/fiches_de_paie/thesard_2011-07.yaml
- openfisca_france/tests/formulas/aide_premier_salarie.yaml
- openfisca_france/tests/formulas/cice.yaml
- openfisca_france/tests/formulas/cout_du_travail.yaml
- openfisca_france/tests/formulas/cout_du_travail_final.yaml
- openfisca_france/tests/formulas/salaire_super_brut.yaml
- openfisca_france/tests/formulas/salaire_super_brut_hors_allegements.yaml
- openfisca_france/tests/test_basics.py
- openfisca_france/tests/test_cotsoc_fonc.py
- openfisca_france/widgets/Composition.py
> Aide à la première embauche

- openfisca_france/model/datatrees.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
- openfisca_france/model/revenus/activite/salarie.py
- openfisca_france/param/param.xml
- openfisca_france/tests/formulas/allegement_cotisation_allocations_familiales.yaml
- openfisca_france/tests/formulas/cout_du_travail.yaml
Implementation of  #267
The idea : generalize the computation of Fillon-like variables.
> Update allegement cot fam

- openfisca_france/param/param.xml
[Circulaire](http://www.agirc-arrco.fr/fileadmin/agircarrco/documents/circulaires/agirc_arrco/2015/201515drj_parametres_2016.pdf) AGIRC - ARCCO du 28-12-2015
Fichier : [201515drj_parametres_2016.pdf](https://github.com/openfisca/openfisca-france/files/94567/201515drj_parametres_2016.pdf)
> Update taux AGIRC GMP

- openfisca_france/param/param.xml
Les taux de 2016 [ici](https://www.urssaf.fr/portail/home/taux-et-baremes/taux-de-cotisations/les-employeurs/les-taux-de-cotisations-de-droit.html)
Les taux de 2017 et la référence aux décrets [ici](www.netpme.fr/info-conseil-1/gestion-entreprise/gestion-quotidienne/gestion-paie/actualite/114381-paie-ce-qui-change-au-1er-janvier-2016#poursuite-de-la-hausse-des-cotisations-vieillesse)
> Update taux cotisation vieillesse déplafonnée

- openfisca_france/model/prestations/prestations_familiales/af.py
- openfisca_france/param/param.xml
- openfisca_france/tests/formulas/af.yaml
Connected to sgmap/openfisca-france#37
> Seulement une demi majoration pour âge pour les enfants en garde alternée ouvrant droit

- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/apprentissage.py
> Remove print

- openfisca_france/model/base.py
Depends on https://github.com/openfisca/openfisca-core/pull/377
> Add base function requested_period_last_or_next_value

- openfisca_france/reforms/inversion_revenus.py
- openfisca_france/scripts/measure_performances.py
Interdependent with https://github.com/openfisca/openfisca-core/pull/379
> Adapt to extra_params core branch

- openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
- openfisca_france/model/datatrees.py
- openfisca_france/model/model.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
- openfisca_france/model/prestations/minima_sociaux/cmu.py
- openfisca_france/model/prestations/minima_sociaux/ppa.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/model/prestations/prestations_familiales/af.py
- openfisca_france/model/revenus/autres.py
- openfisca_france/model/revenus/remplacement/indemnites_journalieres_securite_sociale.py
- openfisca_france/param/param.xml
- openfisca_france/reforms/aides_ville_paris.py
- openfisca_france/tests/formulas/af.yaml
- openfisca_france/tests/formulas/garde_alternee.yaml
- openfisca_france/tests/formulas/ppa.yaml
- openfisca_france/tests/formulas/rsa_celibataire.yaml
- openfisca_france/tests/formulas/rsa_couple.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_548ac530bf2c83e6182edb2d.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_54f7282125be8dd27ba42168.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_551d4d49d8e0018545eb071b.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_551d5fa6d5717876456fda88.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_55252a6c86e10bba11f76d3f.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_55915b4148433cfe2f4370dd.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_55af58cc84c8730b6e7430cd.yaml
Connected to sgmap/mes-aides-ui#199
Some renaming : 
rfon_ms -> rsa_revenus_fonciers
br_rmi -> rsa_base_ressources
br_rmi_i -> rsa_base_ressources_i
br_rmi_pf -> rsa_base_ressources_prestations_familiales
br_rmi_ms -> rsa_base_ressources_minima_sociaux
ra_rsa_i -> rsa_revenu_activite_i
ra_rsa -> rsa_revenu_activite
alt -> garde_alternee
> Calcul de la PPA

- openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
contribution dans le browser, pas sur d'avoir fait de la bonne manière...
> add link for reduction impôt exceptionnelle

- openfisca_france/model/prestations/aides_logement.py
- openfisca_france/tests/formulas/aides_logement.yaml
Connected to sgmap/openfisca-france#35
> Abattement pour les revenus enfants dans AL

- openfisca_france/model/prestations/aides_logement.py
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_548efa8e09d6285e02d4e6b0.yaml
Connected to sgmap/openfisca-france#16
> Evaluation forfaitaire pour les TNS

- openfisca_france/model/prestations/prestations_familiales/cf.py
- openfisca_france/model/prestations/prestations_familiales/paje.py
Connected to sgmap/mes-aides-api#71
Change cumul rule: no CF is there is PAJE
(no matter which one is the biggest)
> Change cumul rule for CF/PAJE

- openfisca_france/model/prestations/minima_sociaux/cmu.py
Otherwise we give cmu for people with rsa not computable
> Make sure rsa is perceived for cmu eligibilite

- openfisca_france/model/revenus/activite/salarie.py
@laem: I let you merge this PR since it may raise some conflicts with what you are doing right now
> Cleaning (flake8)

- openfisca_france/model/prestations/minima_sociaux/ppa.py
- openfisca_france/tests/formulas/ppa.yaml
Connected to sgmap/openfisca-france#51.
No big change, so I'll merge it tonight if no objection.
> Add ASS to PPA base ressource

- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/param/param.xml
- openfisca_france/tests/formulas/rsa_exclusion_foyer.yaml
Connected to sgmap/mes-aides-ui#258
Depends on openfisca/openfisca-core#382
> Exclure un enfant du calcul du RSA s'il fait diminuer le montant

- openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
@cbenz : this PR is to be propagated to the api also for the hackathon
> Prolonge aidper, credit_impots et reductions

- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
- openfisca_france/model/revenus/activite/salarie.py
- openfisca_france/param/param.xml
- openfisca_france/tests/fiches_de_paie/salarie_ipp_2014-11.yaml
- openfisca_france/tests/fiches_de_paie/salarie_ipp_2014-11_indemnite_fin_contrat.yaml
- openfisca_france/tests/formulas/cif_cdd.yaml
- openfisca_france/tests/formulas/indemnite_cdd.yaml
> Indemnite fin contrat

- openfisca_france/model/prestations/minima_sociaux/ppa.py
- openfisca_france/tests/formulas/ppa.yaml
> Add pensions_invalidite to ppa base ressources

- openfisca_france/model/prestations/prestations_familiales/paje.py
- openfisca_france/param/param.xml
- openfisca_france/tests/formulas/paje.yaml
- openfisca_france/tests/test_yaml.py
Connected to sgmap/mes-aides-api#82
> Revaloriation 1er avril

- CHANGELOG.md
- openfisca_france/model/base.py
- openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
- openfisca_france/model/caracteristiques_socio_demographiques/logement.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/charges_deductibles.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
- openfisca_france/model/prelevements_obligatoires/isf.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py
- openfisca_france/model/prestations/minima_sociaux/ass.py
- openfisca_france/model/prestations/prestations_familiales/paje.py
- openfisca_france/model/revenus/activite/non_salarie.py
- openfisca_france/model/revenus/activite/salarie.py
- openfisca_france/model/revenus/autres.py
- openfisca_france/model/revenus/capital/financier.py
- openfisca_france/model/revenus/capital/foncier.py
- openfisca_france/model/revenus/capital/plus_value.py
- openfisca_france/model/revenus/remplacement/chomage.py
- openfisca_france/model/revenus/remplacement/indemnites_journalieres_securite_sociale.py
- openfisca_france/model/revenus/remplacement/retraite.py
- setup.py
See https://github.com/openfisca/openfisca-core/pull/384
> Replace `build_column` calls by `Variable` classes

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/ppa.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/param/param.xml
- openfisca_france/tests/formulas/ppa.yaml
- setup.py
- Loosen etudiant condition
- Take into account AAH in a specific way
- Add ressources to the BR
> Adjust ppa computation

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_totaux.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
- openfisca_france/model/revenus/activite/salarie.py
- openfisca_france/param/param.xml
- openfisca_france/tests/formulas/CSG_CRDS_salaire.yaml
- openfisca_france/tests/formulas/complementaire_sante.yaml
- openfisca_france/tests/formulas/forfait_social.yaml
- setup.py
La complémentaire santé est obligatoire depuis le 1er janvier 2016. 
Elle impacte les cotisations employeur, salarié, l'assiette non abattue de la CSG-CRDS, le forfait social (qui n'était pas rattaché aux cotisations employeur avant cette PR), la taxe sur les salaires (:scream_cat: )
> Complementaire sante - forfait social - taxe sur les salaires

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
- openfisca_france/model/revenus/activite/salarie.py
- openfisca_france/param/param.xml
- openfisca_france/tests/formulas/cice.yaml
- openfisca_france/tests/formulas/taxe_apprentissage.yaml
- openfisca_france/tests/formulas/taxe_salaires.yaml
- setup.py
See changelog : https://github.com/openfisca/openfisca-france/commit/e88436f54ae14d00a462a6d3dada2199cb7414e1
@benjello qu'en penses-tu ? Je ne suis pas vraiment familier avec tout ça. Cette PR fait suite à des [remarques d'utilisateurs](sgmap/cout-embauche/issues/102#issuecomment-227108821) sur le simulateur d'embauche.
> Introduce association à but non lucratif

- CHANGELOG.md
- run-travis-tests.sh
- setup.py
See discussion [here](https://github.com/pierrehvz/openfisca-france/pull/2#issuecomment-229077896)
------
> Only enforce version update when PR target is master

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
- setup.py
Thanks @benjello 
Fixes #501 
All the possibilities were not tested unfortunately...
> Correct bug in the computing of allegements de cotisations

- CHANGELOG.md
- openfisca_france/model/prestations/prestations_familiales/aeeh.py
- setup.py
> Fix end date in aeeh

- .travis.yml
- CHANGELOG.md
- setup.py
> Update numpy dependency version to 1.11

- .travis.yml
- CHANGELOG.md
- openfisca_france/reforms/allocations_familiales_imposables.py
- openfisca_france/reforms/plf2016.py
- openfisca_france/reforms/plf2016_ayrault_muet.py
- openfisca_france/tests/base.py
- openfisca_france/tests/reforms/test_plf2016.py
- openfisca_france/tests/reforms/test_plf2016_ayrault_muet.py
- setup.py
Migrating the plf2016 reforms
There is still a bug in ayrault_muet reform.
It seems that we cannot manipulate a variable that is provided by the reform, in the reform.
> Plf106 reform

- CHANGELOG.md
- openfisca_france/decompositions/decomp.xml
- openfisca_france/decompositions/decomp_contrib.xml
- openfisca_france/decompositions/decomp_prestations.xml
- openfisca_france/decompositions/decompositions-multiples.xml
- openfisca_france/model/mesures.py
- openfisca_france/tests/base.py
- setup.py
@cbenz we will need this one for the CPO
> Ppa revenu disponible

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/ppa.py
- openfisca_france/param/param.xml
- openfisca_france/tests/formulas/ppa.yaml
- setup.py
> Adapt PPA to avoid 3 months antedating params

- CHANGELOG.md
- openfisca_france/model/datatrees.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- openfisca_france/model/prelevements_obligatoires/taxe_habitation.py
- setup.py
> Delete rfr_n_1 and rfr_n_2

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/tests/formulas/rsa_celibataire.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_559fbbbef394e1a7011b5762.yaml
- setup.py
+ Fix bugs in RSA:
+  One need to be **strictly** more that 25 to benefit it.
+   Apply rsa_forfait_asf accordingly to the asf actually being paid.
+ Deprecate `rsa_forfait_asf_individu`
> Age must be strictly superior to 25 to get RSA

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/cmu.py
- openfisca_france/tests/formulas/cmu.yaml
- setup.py
- Simplify base ressources
- Fix bug in forfait logement
> Refactor cmu

- CHANGELOG.md
- openfisca_france/model/caracteristiques_socio_demographiques/logement.py
- openfisca_france/model/prestations/minima_sociaux/cmu.py
- openfisca_france/tests/formulas/cmu.yaml
- setup.py
* Tighten CMU/ACS eligibility conditions when when person is less than 25
* Introduce `cmu_acs_eligibilite`, `habite_chez_parents`
> Ajuster l'éligibilité à la CMU pour les moins de 25 ans

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
- openfisca_france/model/prestations/minima_sociaux/ppa.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/tests/formulas/asi.yaml
- openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_54789fdafccedf3f260aeb4c.yaml
- setup.py
* Refactor asi_aspa.py
* Fix abattement for conjoint salary
* Adjust interaction with AAH
> Adjust ASI computation

- CHANGELOG.md
- openfisca_france/param/param.xml
- setup.py
Connected to https://github.com/sgmap/mes-aides-ui/issues/372
> Increase RSA value from Sept 2016

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/model/prestations/prestations_familiales/base_ressource.py
- openfisca_france/model/revenus/capital/plus_value.py
- openfisca_france/param/param.xml
- setup.py
> Add 3vt (PEA)

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
- openfisca_france/tests/formulas/jeune_entreprise_innovante.yaml
- openfisca_france/tests/formulas/salaire_super_brut.yaml
- setup.py
> Non cumul du dispositif d'allègements de cotsoc JEI

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/aah.py
- setup.py
Connected to sgmap/mes-aides-ui#364
Needed by Paris.
> Introduce pch

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/aah.py
- setup.py
Needed by local partners.
We'll probably also calculate it when we move forward with our AAH computation.
This PR will be merged on Friday Nov. 5th if no one objects by then.
> Introduce mva

- CHANGELOG.md
- MANIFEST.in
- setup.py
parameters directory was forgotten in Manifest
> Fix packaging

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/aefa.py
- openfisca_france/model/prestations/minima_sociaux/anciens_ms.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/model/prestations/prestations_familiales/af.py
- openfisca_france/model/prestations/prestations_familiales/ars.py
- openfisca_france/model/prestations/prestations_familiales/base_ressource.py
- openfisca_france/model/prestations/prestations_familiales/cf.py
- openfisca_france/model/prestations/prestations_familiales/paje.py
- openfisca_france/tests/test_nb_enfants.py
- setup.py
* Migrate some formulas to new syntax
* `aefa.py`
* `af.py`
* `anciens_ms.py`
* `ars.py`
* `base_ressource.py`
* `cf.py`
* `paje.py`
* `rsa.py`
> Migrate some formulas to v4 syntax

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
- openfisca_france/tests/formulas/cout_du_travail.yaml
- openfisca_france/tests/formulas/salaire_super_brut.yaml
- openfisca_france/tests/formulas/taxe_apprentissage.yaml
- openfisca_france/tests/scipy/de_net_a_brut.yaml
- setup.py
Pas applicable pour les effectifs entreprise < 250 
Meilleurs tests
> Correct Contribution Supplémentaire à l'Apprentissage

- CHANGELOG.md
- openfisca_france/model/datatrees.py
- openfisca_france/model/revenus/activite/salarie.py
- setup.py
> Deprecate entreprise_assujettie_tva

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
- openfisca_france/model/revenus/activite/salarie.py
- openfisca_france/parameters/cotsoc.xml
- openfisca_france/tests/formulas/maladie_mmid_salarie.yaml
- openfisca_france/tests/formulas/taxe_apprentissage.yaml
- setup.py
Ajout des spécificités du régime d'Alsace-Moselle pour les cotisations sociales
- Maladie MMID salarié
- Taxe Apprentissage
- Taxe Apprentissage - Contribution supplémentaire
> Cotsoc alsace moselle

- CHANGELOG.md
- openfisca_france/model/prestations/bourses_superieur.py
- openfisca_france/model/prestations/education.py
- setup.py
> Introduce echelon_bourse

- CHANGELOG.md
- openfisca_france/model/mesures.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py
- openfisca_france/tests/reforms/test_cesthra.py
- openfisca_france/tests/reforms/test_parametric_reform.py
- openfisca_france/tests/reforms/test_plf2015.py
- openfisca_france/tests/reforms/test_plf2016.py
- openfisca_france/tests/reforms/test_plf2016_ayrault_muet.py
- openfisca_france/tests/reforms/test_plfr2014.py
- setup.py
Rename revnet to revenu_net
Rename revini to revenu_initial
Continue mesures migration
Complete remplacement migration
> Rename impo to impots_directs

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
- openfisca_france/parameters/cotsoc.xml
- openfisca_france/parameters/prelevements_sociaux.xml
- setup.py
- SMIC
- Plafond sécu
- AGS
- GMP
- Aide PME prolongée de 6 mois
> Mise à jour des cotisations sociales 2017

- CHANGELOG.md
- openfisca_france/decompositions/fiche_de_paie_decomposition.xml
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_totaux.py
- openfisca_france/model/revenus/activite/salarie.py
- openfisca_france/parameters/cotsoc.xml
- openfisca_france/tests/formulas/penibilite.yaml
- setup.py
> Pénibilité

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
- setup.py
Bug remarqué maintenant que l'aide 1er sal est nulle (depuis le 1er janvier 2017)
> Fix aide pme

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
- openfisca_france/model/revenus/activite/salarie.py
- openfisca_france/reforms/inversion_directe_salaires.py
- setup.py
> Add a sans_objet level for contrat_de_travail

- CHANGELOG.md
- openfisca_france/parameters/prelevements_sociaux.xml
- openfisca_france/tests/formulas/cice.yaml
- setup.py
> Mise à jour du taux du CICE 2017

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
Connected to #683 
Depends on #689
> Documente les guidelines de rédaction du Changelog

- setup.py
Cassé lors du renommage de la license.
Merger après #703
> Réparer le versionnement continu

- CHANGELOG.md
- setup.py
Ré-écrit le changelog, la version `14.1.0` aurait dû être une majeure.
> Fix Changelog

- setup.py
Les breaking changes ne concernent pas france.
> Déclare France compatible avec Core v8

- CHANGELOG.md
* Détails :
- Précise le Changelog pour la version 15.0.0
- - - -
- Modifient des éléments non fonctionnels de ce dépôt
> Improve 15.0.0 changelog

- README.md
Connected to https://github.com/openfisca/openfisca-doc/issues/44
* Détails :
- Documente la version de Python
- - - -
> Documente la version de Python

- CONTRIBUTING.md
Connected to #712 
* Détails :
- Documente la procédure pour faire tourner les tests en utilisant une feature branch de core
- - - -
- Modifient des éléments non fonctionnels de ce dépôt
> Document use other branch core

- CHANGELOG.md
- openfisca_france/model/mesures.py
- openfisca_france/model/prestations/prestations_familiales/aeeh.py
- setup.py
Problème rencontré en production sur mes-aides.
--------------
* Périodes concernées : à partir du 01/01/2003.
* Zones impactées : `prestations/prestations_familiales/aeeh`.
* Détails :
- Retourne pour `aeeh` un montant mensuel et non annuel
- - - -
- Impactent l'API publique d'OpenFisca France
> Make aeeh a monthly defined variable

- .travis.yml
> Update pypi credentials

- CHANGELOG.md
- setup.py
Connected to openfisca/openfisca-web-api#125 
> Upgrade core

- .travis.yml
- travis-run-tests.sh
> Fix build and run application tests before the version validation

- .github/PULL_REQUEST_TEMPLATE.md
* Zones impactées : **openfisca-france/.github/PULL_REQUEST_TEMPLATE.md**
* Détails :
- fonctionnalité in lieu of fonctionalité
- - - -
Ces changements _(effacez les lignes ne correspondant pas à votre cas)_ :
> corrects typo : fonctionnalité in lieu of fonctionalité

- CHANGELOG.md
- openfisca_france/parameters/prestations.xml
- setup.py
* Périodes concernées : à partir du 01/04/2017.
* Zones impactées : `openfisca_france/parameters/prestations.xml`, plus particulièrement les plafonds et montants de l'ASI et de l'ASPA
- - - -
En savoir plus : http://www.legislation.cnav.fr/Documents/circulaire_cnav_2017_13_04042017.pdf
> Update ASPA and ASI values

- openfisca_france/scripts/parameters/baremes_ipp/README.md
> Explicit platform limitation

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/isf.py
- openfisca_france/parameters/bouclier_fiscal.xml
- openfisca_france/parameters/cotsoc.xml
- openfisca_france/parameters/fonc.xml
- openfisca_france/parameters/impot_revenu.xml
- openfisca_france/parameters/prelevements_sociaux.xml
- openfisca_france/parameters/taxation_capital.xml
- setup.py
> Supprimer les commentaires des fichiers XML de paramètres

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/aah.py
- openfisca_france/model/prestations/minima_sociaux/ada.py
- openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
- openfisca_france/model/prestations/minima_sociaux/ass.py
- openfisca_france/model/prestations/minima_sociaux/cmu.py
- openfisca_france/model/prestations/prestations_familiales/aeeh.py
- setup.py
* Détails :
- Migre les formules liées aux prestations sociales vers la syntaxe introduite par OpenFisca-Core 4
> Migre les prestations sociales vers la syntaxe v4

- CHANGELOG.md
- openfisca_france/parameters/cmu.xml
- openfisca_france/parameters/prestations.xml
- setup.py
* Périodes concernées : à partir du 01/04/2017.
- `openfisca_france/parameters/cmu.xml`
- `openfisca_france/parameters/prestations.xml`
* Détails :
- Mise à jour du plafond de ressources pour la CMU
- Cf. Code de la sécurité sociale - Article D861-1
- Mise à jour du montant de l'AAH et de son complément de ressources 
- [Circulaire indiquant le coefficient de revalorisation](http://circulaire.legifrance.gouv.fr/pdf/2017/03/cir_41966.pdf)
> Revalorisation de prestations

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/stage.py
- openfisca_france/parameters/cotsoc/stage/taux_gratification_min.yaml
- setup.py
Travail hackathon DILA "CodeGouv".
Import de paramètres depuis les [simulateurs de la DILA tournant sous "G6K"](https://gitlab.com/pidila/sp-simulateurs-data)
> Déplace les paramètres des stagiaires depuis les formules vers la législation

- CHANGELOG.md
- openfisca_france/parameters/bourses_education/bourse_college/montant_taux_1.yaml
- openfisca_france/parameters/bourses_education/bourse_college/montant_taux_2.yaml
- openfisca_france/parameters/bourses_education/bourse_college/montant_taux_3.yaml
- setup.py
- tests/formulas/bourse.yaml
* Périodes concernées : à partir du 07/05/2017.
* Zones impactées : `openfisca_france/parameters/bourses_education/bourse_college`.
- - - -
> Met a jour les bourses de college pour la campagne 2017-2018

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- notebooks/README.md
- notebooks/getting-started.ipynb
- openfisca_france/scripts/parameters/baremes_ipp/README.md
- setup.py
Connected to openfisca/openfisca-doc#89
> Reference the new address of the documentation

- CHANGELOG.md
- openfisca_france/parameters/cotsoc/pat/commun/chomfg.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_sociales/ags/employeur.yaml
- setup.py
> Rajouter les références supprimées lors du passage à YAML

- CHANGELOG.md
- openfisca_france/entities.py
- setup.py
* Documentation des entités 
* Détails :
- Définition des ménages et des foyers fiscaux.
- - - -
> Document foyer fiscal and ménage entities

- README.md
Connected to openfisca/openfisca-core#570
* Zones impactées : `README.md`.
* Détails :
- les liens vers l'API pointent vers `fr.openfica.org/api/v18`
- - - -
Ces changements modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).
> Mettre à jour l'URL de l'API

- CHANGELOG.md
- openfisca_france/model/prestations/aides_logement.py
- setup.py
Depends on https://github.com/openfisca/openfisca-core/pull/575
Connected to openfisca/openfisca-core#573 
* Détails :
- Simplifie le calcul des aides au logement en utilisant le calcul de législation dynamique (nouvelle feature de OpenFisca)
> Simplifie le calcul des aides logement

- README.md
Connected to openfisca/openfisca-core#577
* Changement dans la documentation.
* Zones impactées : `README.md`.
* Détails :
- Ajout de liens vers la nouvelle API et sa documentation Swagger
- Mise à jour de la procédure pour servir l'API
- - - -
Ces changements modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).
> Update the documentation for the new API

- CHANGELOG.md
- Makefile
- README.md
- index.html
- setup.py
- tests/test_api.py
Connected to openfisca/openfisca-core#576
Depends on openfisca/openfisca-core#583
> Mets à jour script lancement de l'API

- CHANGELOG.md
- openfisca_france/conf/cache_blacklist.py
- openfisca_france/model/prestations/minima_sociaux/ppa.py
- openfisca_france/parameters/prestations/minima_sociaux/ppa/montant_de_base.yaml
- openfisca_france/parameters/prestations/minima_sociaux/rsa/forfait_logement/index.yaml
- openfisca_france/parameters/prestations/minima_sociaux/rsa/montant_de_base_du_rsa.yaml
- setup.py
- tests/formulas/ppa.yaml
* Périodes concernées : à partir du 01/01/2016.
* Zones impactées : `/prestations/ppa`.
* Détails :
- Améliore l'implémentation de la prime d'activité en utilisant le bon montant forfaitaire
> Améliore l'implémentation de la PPA

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- setup.py
- tests/test_opt_out_cache.py
* Détails :
- Adapte France à OpenFisca Core v21.2
> Adapt to core v21.2

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- openfisca_france/model/revenus/capital/financier.py
- openfisca_france/model/revenus/capital/plus_value.py
- openfisca_france/parameters/impot_revenu/plus_values.yaml
- openfisca_france/reforms/allocations_familiales_imposables.py
- setup.py
> Ipp 2 : Update taxation des revenus du capital dans IR -- Merge sur master

- CHANGELOG.md
- circle.yml
- openfisca_france/model/prestations/minima_sociaux/cmu.py
- setup.py
- tests/formulas/cmu.yaml
Depends on https://github.com/openfisca/openfisca-core/pull/621
Connected to Connected to openfisca/openfisca-core#586
Pas d'impact sur les performances, testé sur des cas types et sur une simulation de 40 000 individus et 10 000 familles
(Je demande 4 revues pour en avoir une, ne vous sentez pas obligé d'en faire une deuxième ^^)
> Migre la dernière formule vers la syntaxe standard 🎉 🎉 

- CHANGELOG.md
- openfisca_france/model/prestations/aides_logement.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/model/prestations/prestations_familiales/base_ressource.py
- setup.py
Depends on https://github.com/openfisca/openfisca-core/pull/602
* Détails :
- Adapte France à OpenFisca Core v22
> Improve projectors

- circle.yml
* Ensure using latest version of twine
> Fix pypi publishing

- .github/PULL_REQUEST_TEMPLATE.md
* Détails :
- Corrige les liens ci-dessous
- - - -
- - - -
> Corrige les liens dans le texte d'accompagnement des PRs

- CHANGELOG.md
- openfisca_france/model/prestations/logement_social.py
- openfisca_france/reforms/simulation_reform.py
- setup.py
* Amélioration fonctionnelle
* Zones impactées : `reforms/simulation_reform`.
* Détails :
- Création d'une réforme qui adapte la législation pour les simulateurs
> Create a simulation reform to adapt legislation to simulator usage

- CHANGELOG.md
- openfisca_france/parameters/prestations/minima_sociaux/rmi/RMI_fixe.yaml
- openfisca_france/parameters/prestations/minima_sociaux/rsa/RMI_fixe.yaml
- setup.py
* Détails :
- Supprime des paramètres obsolètes
> Remove unused parameters

- .circleci/config.yml
> Limit parallelism to 2 containers

- CHANGELOG.md
- openfisca_france/model/base.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- openfisca_france/model/revenus/activite/salarie.py
- setup.py
* Zones impactées : `model/base`.
* Détails :
- Modifie le taux de primes pour qu'il soit égal à 19,5 % au lieu de 25 %
> Fix taux primes

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
- openfisca_france/parameters/cotsoc/pat/commun/maladie.yaml
- openfisca_france/parameters/cotsoc/sal/commun/maladie.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_sociales/mmid/employeur.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_sociales/mmid/salarie.yaml
- setup.py
* Périodes concernées : à partir du 01/01/2018.
* Zones impactées : `prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive`.
* Détails :
- Corrige la cotisation patronale maladie (mmida) à partir de 2018. 
- Annule la cotisation salariale maladie (mmid) à partir de 2018.
Réf: Décret n° 2017-1891 relatif au taux des cotisations d'assurance maladie: https://www.legifrance.gouv.fr/eli/decret/2017/12/30/CPAS1732212D/jo/texte
Fix #1088
> Corrige les cotisations maladie à partir du 01-01-2018

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
- setup.py
- tests/fiches_de_paie/business_develop_2015-02.yaml
* Zones impactées : `prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive`.
* Détails :
- Corrige le calcul de la cotisation  agirc gmp
- - - -
- - - -
> Corrige la cotisation agirc gmp

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
- setup.py
* Zones impactées : `model/prestations/minima_sociaux/asi_aspa`.
* Détails :
- Suppression de `revenus_fonciers_minima_sociaux`
> Supprime une formule non-utilisée

- CHANGELOG.md
- openfisca_france/model/base.py
- openfisca_france/model/mesures.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
- tests/formulas/travail_non_salarie.yaml/artisan.yaml
- tests/formulas/travail_non_salarie/artisan_commercant_profession_liberale.yaml
- `prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie`
- `mesures`
* Détails :
- Ajout sommaire des contributions et cotisations sociales des non salariés artisan, commeçcant ou profession libérale
- Ajout des variables
- assiette_csg_crds_non_salarie
- categorie_non_salarie
- crds_non_salarie
- csg_non_salarie
- famille_independant
- formation_artisan_commercant
- formation_profession_liberale
- maladie_maternite_artisan_commercant
- maladie_maternite_profession_liberale
- retraite_complementaire_artisan_commercant
- vieillesse_artisan_commercant
- vieillesse_profession_liberale
- - - -
Et surtout, n'hésitez pas à demander …
> Cotisations non salarie

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/ppa.py
- setup.py
- tests/formulas/ppa_2018.yaml
* Zones impactées : `model\prestations\minima_sociaux\ppa`.
* Détails :
- Correction de la formule de calcul du forfait logement en fonction du nombre de personnes au foyer.
- Correction des tests pour la revalorisation de la prime d'activité.
> Fiabilisation de la Prime d’activité (PPA) au 1er avril 2018

- CHANGELOG.md
- openfisca_france/model/base.py
- openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
- openfisca_france/model/caracteristiques_socio_demographiques/logement.py
- openfisca_france/model/mesures.py
- setup.py
Child of #372 
---
* Zones impactées : `openfisca_france/model/**/*`.
* Détails :
- - - -
> Linte model

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/impot_revenu/charges_deductibles.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
- openfisca_france/model/prelevements_obligatoires/isf.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/apprentissage.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_totaux.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
- setup.py
Child of #372 
---
* Zones impactées : `openfisca_france/model/prelevements_obligatoires/**/*`.
* Détails :
- Règle W504 : saut de ligne avant opérateur binaire
- - - -
> Linte model/prelevements (W504)

- .gitignore
- CHANGELOG.md
- openfisca_france/france_taxbenefitsystem.py
- openfisca_france/situation_examples/__init__.py
- openfisca_france/situation_examples/couple.json
- setup.py
Connected to openfisca/openfisca-core#664
Depends on openfisca/openfisca-core#744
> Définit les exemples à utiliser dans la route /spec

- CHANGELOG.md
- MANIFEST.in
- setup.py
> Properly package simulation examples

- CHANGELOG.md
- Makefile
- README.md
- openfisca_france/model/prestations/minima_sociaux/aah.py
- setup.py
- tests/reforms/test_allocations_familliales_imposables.py
- tests/reforms/test_parametric_reform.py
- tests/reforms/test_plf2016.py
- tests/reforms/test_plf2016_ayrault_muet.py
- tests/reforms/test_plfr2014.py
- tests/test_api.py
- tests/test_coefficient.py
- tests/test_entities.py
- tests/test_nb_enfants.py
- tests/test_parameters.py
- tests/test_tax_rates.py
- tests/utils.py
Child of #372 
Fixes #372 
---
* Zones impactées : `**/*`.
* Détails :
- - - -
> Linte la totale

- CHANGELOG.md
- openfisca_france/model/prestations/prestations_familiales/base_ressource.py
- setup.py
- `prestations/prestations_familiales/base_ressource.py`
* Détails :
- Corrige la biactivité dans les bases ressources des prestations sociales
Vise à résoudre #836
> Corrige la biactivite

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
- openfisca_france/model/revenus/activite/salarie.py
- setup.py
* Périodes concernées : Avant 01/01/2018.
* Zones impactées : `prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique`.
* Détails :
- Correction et clarification de la cotisation exceptionnelle de solidarité
- - - -
- - - -
- ~[ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution~.
> Corrige la cotisation exceptionnelle de solidarité

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/versement_transport.py
- setup.py
* Zones impactées : `prelevements_obligatoires/prelevements_sociaux/contributions_sociales/versement_transport`.
* Détails :
- Une valeur donnée pour le taux est transmise à toutes les sous-périodes (annuel vers mensuel par exemple)
- - - -
- - - -
- ~[ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution~.
> Fix taux_versement_transport set_input

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/ass.py
- setup.py
- tests/formulas/ass_interessement.yaml
* Périodes concernées : à partir du 01/01/2017.
* Zones impactées : `prestations/minima_sociaux/ass`.
* Détails :
- Suite à l'ajout de l'intéressement (cumul ASS et salaire) la règle de base de non indemnisation a été cassée
- - - -
- - - -
> Ajoute des références et fiabilise les formules ASS

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
- setup.py
> Corrige une faute de frappe

- .circleci/config.yml
* Détails :
- Effectuer les étapes d'intégration continue sur Python 3 seulement
- - - -
- - - -
> Effectue les étapes d'intégration continue sur Python 3 seulement

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/ppa.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- setup.py
* Détails :
- Ajoute des références pour la prise en compte de l'ASF dans le RSA et la PPA
- Ajoute des références pour la prise en compte du CF et des AL dans la PPA
> Ajoute des références pour la prise en compte de l'ASF, les AF et le CF dans le RSA et la PPA

- CHANGELOG.md
- openfisca_france/reforms/de_net_a_brut.py
- setup.py
* Détails :
- Retire une référence inadaptée.
- Corrige le label d'une variable.
- - - -
- - - -
- ~[ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution~.
> Corrige des références et descriptions

- openfisca_france/model/prestations/minima_sociaux/anciens_ms.py
- openfisca_france/parameters/bourses_education/bourse_college/montant_taux_1.yaml
- openfisca_france/parameters/bourses_education/bourse_college/montant_taux_2.yaml
- openfisca_france/parameters/bourses_education/bourse_college/montant_taux_3.yaml
- openfisca_france/parameters/bourses_education/bourse_lycee/apres_2016/echelon_1/montant.yaml
- openfisca_france/parameters/bourses_education/bourse_lycee/apres_2016/echelon_2/montant.yaml
- openfisca_france/parameters/bourses_education/bourse_lycee/apres_2016/echelon_3/montant.yaml
- openfisca_france/parameters/bourses_education/bourse_lycee/apres_2016/echelon_4/montant.yaml
- openfisca_france/parameters/bourses_education/bourse_lycee/apres_2016/echelon_5/montant.yaml
- openfisca_france/parameters/bourses_education/bourse_lycee/apres_2016/echelon_6/montant.yaml
- openfisca_france/parameters/prestations/prestations_familiales/ape.yaml
- openfisca_france/parameters/prestations/prestations_familiales/ars/taux_college.yaml
- openfisca_france/parameters/prestations/prestations_familiales/ars/taux_lycee.yaml
- openfisca_france/parameters/prestations/prestations_familiales/ars/taux_primaire.yaml
- openfisca_france/parameters/prestations/prestations_familiales/asf/taux_1_parent.yaml
- openfisca_france/parameters/prestations/prestations_familiales/asf/taux_2_parents.yaml
- openfisca_france/parameters/prestations/prestations_familiales/paje/base/taux_allocation_base.yaml
- openfisca_france/parameters/prestations/prestations_familiales/paje/prime_naissance/adopt.yaml
- openfisca_france/parameters/prestations/prestations_familiales/paje/prime_naissance/prime_tx.yaml
Connected to https://github.com/betagouv/mes-aides-ui/issues/1413
* Zones impactées : `openfisca-france/openfisca_france/parameters/bourses_education/*`.
* Détails :
- Remplace l'acronyme `BMAF` dans la description des paramètres par sa signification,
- Précise la périodicité mensuelle du montant des bourses de collège et lycée.
- - - -
- Corrigent ou améliorent une documentation déjà existante.
- - - -
> Explicite acronymes et périodes des bourses de collège et lycée

- .github/ISSUE_TEMPLATE.md
* Détails :
- Ajoute un template pour les issues, comme [celui d'OpenFisca Core](https://github.com/openfisca/openfisca-core/blob/master/.github/ISSUE_TEMPLATE.md)
- - - -
- - - -
> Ajoute un template pour les issues

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/cs/ressources.py
- setup.py
- tests/formulas/cs/ressources.yaml
* Zones impactées : `prestations/minima_sociaux/cs/ressources`.
* Détails :
- Améliore la prise en compte des bourses sur critères sociaux pour la CSS
> Améliore la prise en compte des bourses sur critères sociaux pour la CSS

- CHANGELOG.md
* Détails :
- Corrige une erreur dans le lien vers une pull request dans le CHANGELOG.md.
- - - -
- - - -
> Corrige le CHANGELOG.md

- CHANGELOG.md
- openfisca_france/model/covid19.py
- openfisca_france/parameters/covid19.yaml
- setup.py
- tests/formulas/covid19/famille.yaml
- tests/formulas/covid19/tpe.yaml
* Zones impactées : `model/covid19`.
* Détails :
- Ajoute un premier calcul de l'aide exceptionnelle pour les TPE
> Ajoute les aides exceptionnelles pendant l'épisode de crise sanitaire du COVID-19

- .gitignore
- .gitpod.Dockerfile
- .gitpod.yml
- CHANGELOG.md
- README.md
- setup.py
* Détails :
- Facilite l'utilisation de GitPod
- - - -
> Ajoute une configuration de base pour GitPod

- CHANGELOG.md
- openfisca_france/parameters/prestations/prestations_familiales/af/age3.yaml
- openfisca_france/parameters/prestations/prestations_familiales/af/bmaf.yaml
- openfisca_france/parameters/prestations/prestations_familiales/af/modulation/majoration_plafond_par_enfant_supplementaire.yaml
- openfisca_france/parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_1.yaml
- openfisca_france/parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_1_base.yaml
- openfisca_france/parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_2.yaml
- openfisca_france/parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_2_base.yaml
- setup.py
Connected to #1404 
* Périodes concernées : à partir du 01/01/2020.
* Zones impactées : `prestations/prestations_familiales/af`.
* Détails :
- Revalorisation périodique de l'Allocation Familiale.
- - - -
- - - -
Quelques conseils à prendre en cxmpte :
> Revalorisation des allocations familiales au 1er avril 2020

- CHANGELOG.md
- openfisca_france/parameters/prestations/minima_sociaux/aah/majoration_plafond_couple.yaml
- openfisca_france/parameters/prestations/minima_sociaux/aah/montant.yaml
- setup.py
* Périodes concernées : à partir du 01/11/2019.
* Zones impactées : `prestations/minima_sociaux/aah`.
* Détails :
- Actualise les paramètres de l'AAH
> Actualise corrige param aah

- CHANGELOG.md
- openfisca_france/parameters/cotsoc/gen/smic_h_b.yaml
- setup.py
- tests/formulas/ppa.yaml
* Périodes concernées : à partir du 01/01/2021.
* Détails :
- Nouvelle valeur du SMIC
> Ajoute la revalorisation 2021 du SMIC horaire brut

- CHANGELOG.md
- openfisca_france/parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_1.yaml
- openfisca_france/parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_2.yaml
- setup.py
- `parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_1.yaml`.
- `parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_2.yaml`.
* Détails :
- Corrige un encodage empêchant le bon import des paramètres
> Corrige un encodage d'accents aigus

- CHANGELOG.md
- openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
- openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- setup.py
* Détails :
- Corrige des fautes de frappe dans les descriptions de variables.
- - - -
> Corrige des fautes de frappe

- CHANGELOG.md
- openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
- openfisca_france/model/prestations/garantie_pret_etudiant.py
- openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/parameters/geopolitique/eee.yaml
- openfisca_france/parameters/geopolitique/index.yaml
- openfisca_france/parameters/prestations/garantie_pret_etudiant/age_max.yaml
- openfisca_france/parameters/prestations/garantie_pret_etudiant/banques_conventionnees.yaml
- openfisca_france/parameters/prestations/garantie_pret_etudiant/duree_min.yaml
- openfisca_france/parameters/prestations/garantie_pret_etudiant/duree_min_residence_continue_annees.yaml
- openfisca_france/parameters/prestations/garantie_pret_etudiant/index.yaml
- openfisca_france/parameters/prestations/garantie_pret_etudiant/montant_max.yaml
- setup.py
- tests/formulas/garantie_pret_etudiant.yaml
- tests/formulas/garantie_pret_etudiant_condition_nationalite.yaml
- tests/formulas/nationalite.yaml
- tests/formulas/rsa/rsa_condition_nationalite.yaml
* Périodes concernées : à partir du 08/06/2020.
* `model/prestations/garantie_pret_etudiant.py`
* `model/prestations/garantie_pret_etudiant.py`
* `parameters/prestations/garantie_pret_etudiant/*`
* Détails :
- Ajoute l'éligibilité à la garantie du prêt étudiant par l'État.
- Décrit la garantie du prêt étudiant par l'État.
* Limitations connues :
1. L'éligibilité est approximée par l'âge alors que la condition réelle est la majorité. Un‧e mineur‧e émancipé‧e devrait être éligible.
2. Une incohérence existe dans le montant maximal garanti selon les sources. Voir le code pour les détails.
3. Une incohérence existe dans les dates de définition : l'existence du dispositif est attestée dès le 08/06/2020, mais aucune banque n'était …
> Ajoute la garantie du prêt étudiant par  l'État et corrige l'appartenance à l'EEE

- CHANGELOG.md
- openfisca_france/parameters/prestations/garantie_pret_etudiant/montant_max.yaml
- setup.py
* Périodes concernées : à partir du 16/02/2021.
- `parameters/prestations/garantie_pret_etudiant/montant_max.yaml`
* Détails :
- Mise à jour du montant maximum du prêt étudiant garanti par l'État.
- - - -
- - - -
Cette modification s'appuie sur une confirmation par une source interne au Ministère de l'Enseignement supérieur. Suite à ma demande de clarification, une demande de mise à jour du site education.gouv.fr a été faite et devrait être effective prochainement.
> Met à jour le plafond du prêt étudiant garanti par l'État

- CHANGELOG.md
- openfisca_france/conf/cache_blacklist.py
- openfisca_france/model/prestations/transport.py
- openfisca_france/parameters/prestations/transport/aide_financement_permis_apprenti.yaml
- setup.py
- tests/formulas/aide_financement_permis_apprenti.yaml
* Périodes concernées : À partir du 03/01/2019.
* Zones impactées : `prestations/transport.py`.
* Détails :
- Ajoute l'aide au financement du permis de conduire pour les apprentis.
- - - -
> Ajoute l'aide au financement du permis de conduire pour les apprentis

- CHANGELOG.md
- openfisca_france/model/prestations/alimentation.py
- openfisca_france/model/prestations/education.py
- openfisca_france/model/prestations/garantie_pret_etudiant.py
- setup.py
- tests/formulas/crous_repas_un_euro.yaml
- tests/formulas/garantie_pret_etudiant.yaml
* `prestations/alimentation.py`
* `prestations/education.py`
* Détails :
- Ajoute l'élément `enseignement_superieur` à l'énumération utilisé dans `scolarite`
- Ajoute la variable `etablissement_scolaire` pour indiquer le type (public, privé sous contrat, hors contratà des établissements scolaire
- Fiabilise l'éligibilité des repas à 1e à partir de ces nouvelles informations
- - - -
- - - -
> Modélise un étudiant de l'enseignement supérieur et fiabilise le repas à 1e du CROUS

- CHANGELOG.md
- openfisca_france/model/patrimoine/livret_epargne_populaire.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- openfisca_france/model/prestations/logement_social.py
- setup.py
- tests/formulas/logement_social_eligible.yaml
- tests/patrimoine/livret_epargne_populaire/eligibilite.yml
* `patrimoine/livret_epargne_populaire.py`.
* `prestations/logement_social.py`
* Détails :
- Ajoute la condition d'autonomie à l'éligibilité au livret d'épargne populaire
- Ajoute la condition de majorité au logement social
- - - -
- - - -
> Fiabiliser l'éligibilité au livret d'épargne populaire et au logement social

- CHANGELOG.md
- openfisca_france/model/prestations/education.py
- openfisca_france/model/prestations/enseignement_superieur/aide_mobilite_internationale.py
- openfisca_france/parameters/prestations/aide_mobilite_internationale/duree_sejour.yaml
- openfisca_france/parameters/prestations/aide_mobilite_internationale/montant.yaml
- setup.py
- tests/formulas/bourses_superieur/aide_mobilite_internationale.yaml
* `prestations/education.py`
* `prestations/enseignement_superieur/aide_mobilite_internationale.py`
* `parameters/prestations/aide_mobilite_internationale/*`
* Détails :
- Ajoute les variables `aide_mobilite_internationale` et `aide_mobilite_internationale_eligibilite` qui calculent l'Aide à la Mobilité Internationale.
- Ajoute les variables `debut_etudes_etranger` et `fin_etudes_etranger` pour caractériser un séjour de formation ou de stage à l'étranger.
- - - -
Modélise l'[aide à la mobilité internationale](https://www.etudiant.gouv.fr/fr/bourses-erasmus-et-aide-la-mobilite-internationale-ami-67) (400€ / mois).
- Votre séjour aidé à l'étranger dure entre 2 et 9 mois consécutifs.
- Vous êtes boursier …
> Modélise l'aide à la mobilité internationale

- CHANGELOG.md
- openfisca_france/parameters/prelevements_sociaux/contributions/csg/activite/deductible/taux.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions/csg/activite/taux_global.yaml
- setup.py
Connected to #1519 
Cette PR vise à lever deux questions simples concernant les références législatives openfisca / IPP (cf. commentaires).
* Zones impactées : `openfisca_france/parameters/prelevements_sociaux/contributions/csg/activite/`.
* Détails :
- Met à jour le lien vers le barème IPP correspondant au taux global et déductible de la CSG.
- Complète par le lien legifrance menant à l'article précis.
- - - -
- Modifient des éléments non fonctionnels …
> Met à jour des références de taux de CSG activité

- openfisca_france/model/prestations/enseignement_superieur/bourse_criteres_sociaux.py
- tests/formulas/bourses_superieur/bourse_criteres_sociaux.yaml
* Zones impactées : `prestations/enseignement_superieur/bourse_criteres_sociaux.py`.
* Détails :
- Corrige l'échelon de la BCS pour les étudiants éligibles mais aux ressources trop élevées
- - - -
- - - -
> Corrige l'échelon de la BCS pour les étudiants éligibles mais aux ressources trop élevées

- CHANGELOG.md
- openfisca_france/model/revenus/capital/plus_value.py
- setup.py
Corrections de caractères UTF-8
> Corrige un encodage de caractères dans les métadonnées

- CHANGELOG.md
- openfisca_france/model/caracteristiques_socio_demographiques/capacite_travail.py
- openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
- openfisca_france/model/caracteristiques_socio_demographiques/logement.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/stage.py
- openfisca_france/model/prestations/aides_logement.py
- openfisca_france/model/prestations/minima_sociaux/aah.py
- openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/model/prestations/prestations_familiales/aeeh.py
- openfisca_france/model/prestations/prestations_familiales/paje.py
- openfisca_france/model/revenus/activite/salarie.py
- openfisca_france/model/revenus/remplacement/rente_accident_travail.py
- setup.py
Closes #1581. Closes #1582. Closes #1583. Closes #1584. Closes #1585. Closes #1587. Closes #1588. Closes #1590.
- `model/caracteristiques_socio_demographiques/capacite_travail.py`
- `model/caracteristiques_socio_demographiques/demographie.py`
-  `model/caracteristiques_socio_demographiques/logement.py`
-  `caracteristiques_socio_demographiques/capacite_travail.py`
-  `model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py`
- ` model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/stage.py`
-  `model/prestations/aides_logement.py`
-  `model/prestations/minima_sociaux/aah.py`
-  `model/prestations/minima_sociaux/asi_aspa.py`
- …
> Configure les variables par mois

- CHANGELOG.md
- openfisca_france/model/mesures.py
- openfisca_france/model/prestations/prestations_familiales/aeeh.py
- openfisca_france/parameters/prestations/prestations_familiales/aeeh/age.yaml
- setup.py
- tests/formulas/aeeh.yaml
* Amélioration technique et correction d'un crash. 
* Périodes concernées : jusqu'au 31/12/2005
* Zones impactées : `model/prestations/prestations_familiales/aeeh.py`.
* Détails :
- Séparation de l'AEEH et de l'AES en créant la variable `aes`
- Correction de l'accès aux paramètres débutant par un nombre (utilisation de la méthode `ParameterNodeAtInstant._children`
- - - -
- Modifient l'API publique d'OpenFisca France.
- Ajoutent une fonctionnalité.
- - - -
> Répare aeeh et crée aes

- openfisca_france/parameters/prelevements_sociaux/cotisations_secteur_public/rafp/salarie/rafp.yaml
- openfisca_france/parameters/prelevements_sociaux/regimes_complementaires_retraite_secteur_prive/agff/salarie/cadre/agff.yaml
- tests/test_preprocessing.py
Ajoute le test qui vérifie que la start date est la bonne et que la valeur a cette date n'est pas nulle.
> WIP: Ajoute le test pour start

- CHANGELOG.md
- openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
- setup.py
* Zones impactées : `model/caracteristiques_socio_demographiques/demographie.py`.
* Détails :
- Ajoute une variable Enum pour le régime de sécurité sociale
- - - -
- Ajoutent une fonctionnalité : variable  Enum pour le régime de sécurité sociale que je vais pouvoir utiliser dans openfisca-france-local.  Étant un paramètre national, je trouvais ça plus judicieux de l'ajouter ici.
- - - -
> Ajoute une variable Enum pour le régime de sécurité sociale

- CHANGELOG.md
- openfisca_france/parameters/prelevements_sociaux/regimes_complementaires_retraite_secteur_prive/apec/employeur/apec.yaml
- openfisca_france/parameters/prelevements_sociaux/regimes_complementaires_retraite_secteur_prive/apec/salarie/apec.yaml
- setup.py
* Zones impactées : `parameters`.
* Détails :
- Corrige quelques erreurs dans certains parametres, ayant trait aux unités (unités manquantes, unités définies plusieurs fois).
- - - -
- - - -
> Corrections paramètres (unités des barèmes)

- CHANGELOG.md
- openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
- openfisca_france/model/covid19/jeunes.py
- setup.py
- tests/formulas/aide_jeunes_diplomes_anciens_boursiers.yaml
* Périodes concernées : à partir du 01/01/2021 au 31/21/2021.
- `caracteristiques_socio_demographiques/demographie.py`.
- `covid19/jeunes.py`
* Détails :
- `plus_haut_diplome_niveau`, `plus_haut_diplome_date_obtention`, `alternant` sont désormais des variables mensuelles (et non plus annuelles). 
- - - -
- - - -
Et …
> Facilite l'utilisation des variables associées à aide_jeunes_diplomes_anciens_boursiers

- CHANGELOG.md
- openfisca_france/model/prestations/transport.py
- openfisca_france/parameters/prestations/transport/carte_sncf_eleve_apprenti.yaml
- setup.py
- tests/formulas/carte_sncf_eleve_apprenti.yaml
* Zones impactées : `openfisca_france/model/prestations/transport.py`.
* Détails : Ajout de l'aide  https://www.sncf.com/fr/offres-voyageurs/cartes-tarifs-grandes-lignes/eleves-apprentis
- - - -
- - - -
> Ajout de l'aide carte scnf eleve apprenti

- CHANGELOG.md
- openfisca_france/model/prestations/enseignement_superieur/aide_merite.py
- setup.py
- tests/formulas/bourses_superieur/aide_merite.yaml
`openfisca-france/tests/formulas/bourses_superieur/aide_merite.yaml` 
`openfisca-france/openfisca_france/model/prestations/enseignement_superieur/aide_merite.py`
* Détails :
- Change la période d'éligibilité pour l'aide au mérite. Le calcul de l'aide au mérite se base sur une année universitaire et non sur une année civile.  
- - - -
- - - -
> Change la période d'éligibilité pour l'aide au mérite

- CHANGELOG.md
- openfisca_france/model/prestations/education.py
- openfisca_france/model/prestations/mobilite_jeunes.py
- openfisca_france/parameters/prestations/aide_mobilite_master.yaml
- openfisca_france/parameters/prestations/aide_mobilite_parcoursup.yaml
- setup.py
- tests/formulas/aide_mobilite_master.yaml
- tests/formulas/aide_mobilite_parcoursup.yaml
* Périodes concernées : à partir du 21/08/2017.
* Zones impactées : `prestations/mobilite_jeunes.py`.
* Détails :
- Ajoute les aides à la mobilité Master et ParcourSup.
- - - -
- - - -
:warning:  repose sur #1501 
> Ajoute les aides à la mobilité ParcourSup et Master

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
- openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/allegement_cotisation_allocations_familiales/plafond_smic.yaml
- openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/allegement_cotisation_allocations_familiales/reduction.yaml
- openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/ensemble_des_entreprises/plafond.yaml
- openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/ensemble_des_entreprises/reduction_maximale/entreprises_de_20_salaries_et_plus.yaml
- openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/ensemble_des_entreprises/reduction_maximale/entreprises_de_moins_de_20_salaries.yaml
- openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/entreprises_ayant_signe_un_accord_de_rtt_avant_le_30_06_2003/plafond.yaml
- openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/entreprises_ayant_signe_un_accord_de_rtt_avant_le_30_06_2003/reduction_maximale.yaml
- openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/entreprises_restees_aux_39_heures_hebdomadaires_au_30_06_2003/plafond.yaml
- openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/entreprises_restees_aux_39_heures_hebdomadaires_au_30_06_2003/reduction_maximale.yaml
- setup.py
* Périodes concernées : à partir du 2018/01/01
* Zones impactées : `parameters.prelevements_sociaux.reductions_cotisations_sociales.fillon`.
* Détails :
- Mise à jour des paramètres
- Ajout des références législatives correspondantes
- - - -
> Revue des allègements des cotisations employeur (ex-Fillon, jeune entreprise innovante et allegements branche famille)

- CHANGELOG.md
- openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/ensemble_des_entreprises/reduction_maximale/entreprises_de_20_salaries_et_plus.yaml
- openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/ensemble_des_entreprises/reduction_maximale/entreprises_de_moins_de_20_salaries.yaml
- setup.py
* Zones impactées : `parameters.prelevements_sociaux.reductions_cotisations_sociales.fillon`.
* Détails :
- Corrige une erreur humaine dans la PR precedente: suppression de décrets
> Corrige les suppressions des decrets

- openfisca_france/parameters/cmu/plafond_base.yaml
Revalorisatin de la CSS pour Avril
> Reval CSS Avril

- CHANGELOG.md
- openfisca_france/model/prestations/cheque_energie.py
- setup.py
- tests/formulas/cheque_energie/eligibilite_logement.yaml
- tests/formulas/cheque_energie/montant.yaml
- `model/prestations/cheque_energie.py`.
* Détails :
- Correction de la variable `cheque_energie`.
- - - -
- Corrigent un calcul déjà existant.
- - - -
> Corrige cheque energie

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/aah.py
- openfisca_france/parameters/prestations/minima_sociaux/aah/abattements/abattement_activite_tranche_inf.yaml
- openfisca_france/parameters/prestations/minima_sociaux/aah/abattements/abattement_activite_tranche_sup.yaml
- openfisca_france/parameters/prestations/minima_sociaux/aah/abattements/abattement_conjoint.yaml
- openfisca_france/parameters/prestations/minima_sociaux/aah/abattements/tranche_smic.yaml
- openfisca_france/parameters/prestations/minima_sociaux/aah/abattements_avant_2011/abattement_300_700.yaml
- openfisca_france/parameters/prestations/minima_sociaux/aah/abattements_avant_2011/abattement_700_1100.yaml
- openfisca_france/parameters/prestations/minima_sociaux/aah/abattements_avant_2011/abattement_inf_300.yaml
- openfisca_france/parameters/prestations/minima_sociaux/aah/abattements_avant_2011/abattement_sup_1100.yaml
- openfisca_france/parameters/prestations/minima_sociaux/aah/taux_incapacite_rsdae.yaml
- setup.py
`model/prestations/minima_sociaux/aah.py`.
`parameters/prestations/minima_sociaux/aah/`
* Détails :
- Ajout de fichiers .yaml pour les paramètres de la formule de calcul des ressources `aah_base_ressources`
> Corrections formule aah

- CHANGELOG.md
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/activite/abattement.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/activite/taux.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/retraite/taux.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/taux_global.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/deductible/abattement.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/deductible/taux.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/imposable/abattement.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/imposable/taux.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/taux_global.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/chomage/deductible/abattement.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/chomage/deductible/taux_plein.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/chomage/deductible/taux_reduit.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/chomage/imposable/abattement.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/chomage/imposable/taux_plein.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/chomage/imposable/taux_reduit.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/chomage/min_exo.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/chomage/taux_global.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/indemnites_journalieres/deductible/taux.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/indemnites_journalieres/taux_global.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/preretraite/imposable/taux_plein.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/preretraite/imposable/taux_reduit.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/preretraite/taux_global.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/retraite_invalidite/deductible/taux_median.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/retraite_invalidite/imposable/taux_median.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/retraite_invalidite/imposable/taux_plein.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/retraite_invalidite/imposable/taux_reduit.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/retraite_invalidite/taux_global.yaml
- setup.py
* Zones impactées : `parameters/prelevements_sociaux/contributions_sociales`.
* Détails :
- Ajout de références
- Mise en forme et corrections de typos
- - - -
Ces changements : 
- - - -
> Harmonisation CSG/CRDS

- CHANGELOG.md
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/activite/abattement.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/chomage/employeur/chomage.yaml
- setup.py
* Zones impactées : `contributions_sociales/crds/activite/abattement`.
* Détails :
- Corrige erreur de frappe
> Corrige typo

- .github/workflows/workflow.yml
- CHANGELOG.md
- setup.py
*  Amélioration technique.
* Détails :
- Déclencher le workflow GitHub Actions pour les pull-requests
> Ajoute pull request comme trigger du CI workflow 

- CHANGELOG.md
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/ags/employeur/ags.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/ags/employeur/index.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/ags/index.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/asf/employeur/asf.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/asf/employeur/index.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/asf/index.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/asf/salarie/asf.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/asf/salarie/index.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/chomage/employeur/chomage.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/chomage/employeur/index.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/chomage/index.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/chomage/salarie/chomage.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/chomage/salarie/index.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_regime_assurance_chomage/index.yaml
- setup.py
* Zones impactées : `parameters/prelevements_sociaux/cotisations_regime_assurance_chomage`.
* Détails :
- Harmonisation des fichiers avec les barèmes-ipp
- Tous les chemins sont updatés pour ne pas casser le code
- - - -
- Modifient l'API publique d'OpenFisca France
- - - -
> Harmonisation - Prelevements Sociaux - cotisations_regime_assurance_chomage (Partie 3 et 4) 

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/index.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/montant_couple.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/montant_seul.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/plafond_ressource_couple.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/plafond_ressource_seul.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/taux_minimum_d_invalidite.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/caah/garantie_ressources.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/caah/index.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/caah/majoration_vie_autonome.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/caah/montant_complement_ressources.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/caah/taux_montant_complement_ressources.yaml
- setup.py
- `parameters/prestations_sociales/prestations_etat_de_sante/asi`
-  `parameters/prestations_sociales/prestations_etat_de_sante/caah`
* Détails :
- Harmonisation des fichiers avec les barèmes-ipp (ajout de références)
- Pas de modification de chemins: version mineure
- - - -
- Modifient l'API publique d'OpenFisca France
- - - -
> Harmonisation - Prestations Sociales- prestations_etat_de_sante.invalidite (Partie 2) 

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
- openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/apprentissage/apprentissage_taxe.yaml
- openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/apprentissage/apprentissage_taxe_alsace_moselle.yaml
- setup.py
* Zones impactées : `parameters/prelevements_sociaux/autres_taxes_salaires/apprentissage`.
* Détails :
- Ajoute des commentaires
> Ajoute des explications à la PR 1737

- CHANGELOG.md
- openfisca_france/parameters/marche_travail/salaire_minimum/smic/nb_heures_travail_mensuel.yaml
- openfisca_france/parameters/marche_travail/salaire_minimum/smic/smic_b_horaire.yaml
- openfisca_france/parameters/marche_travail/salaire_minimum/smic/smic_b_mensuel.yaml
- setup.py
* Périodes concernées : à partir du 01/10/2021.
* Zones impactées : `parameters/marche_travail/salaire_minimum/smic/*`.
* Détails :
- Revalorise le SMIC à partir de janvier 2022.
- Complète le SMIC mensuel par sa revalorisation d'octobre 2021.
- - - -
- - - -
> Met à jour le SMIC

- CHANGELOG.md
- openfisca_france/model/mesures.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
- openfisca_france/parameters/impot_revenu/plus_values.yaml
- setup.py
- tests/calculateur_impots/yaml/regime_benef_reel_agricole_avec_cga.yaml
- tests/calculateur_impots/yaml/rpns_pv.yaml
- `openfisca_france/model/mesures.py`
- `openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py`
- `openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py`
- `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py`
- `openfisca_france/parameters/impot_revenu/plus_values.yaml`
- `tests/calculateur_impots/yaml/regime_benef_reel_agricole_avec_cga.yaml`
- `tests/calculateur_impots/yaml/rpns_pv.yaml`
* Détails :
- Correction des taux d'imposition et des formules concernant les plus-values de cession pour les non-salariés (RPNS).
- Ces PV sont soumises aux prélèvements sociaux applicables sur …
> Correction des Plus-Values de Cession pour les Non-Salariés

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/visale/plafond_loyer/etudiant/hors_ile_de_france.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/visale/plafond_loyer/etudiant/ile_de_france.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/visale/plafond_loyer/plafond_loyer.yaml
- setup.py
* Zones impactées : `openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/visale/plafond_loyer/etudiant/`.
* Détails :
- Correction d'une URL 404 : Remplacement de l'extension ".html" par ".htm" pour qu'elle fonctionne.
> Correction d'une URL.

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rmi/rmi_cond/condition_age_allocataire.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rmi/rmi_cond/nombre_minimal_enfant_si_condition_age_n_est_pas_respectee.yaml
- setup.py
Changement mineur
* Périodes concernées :  à partir du 01/06/2009
* Zones impactées : Rmi_cond
parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rmi/rmi_cond/patrimoine
/Users/ahmedz/leximpact/source/openfisca-
* Détails : J'ai ajouté les références législatives et le last_review
> Ajoute références et last_review pour rmi.age_minimum

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/age_max_rsa_jeune.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/age_min_rsa_jeune.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/age_minimum_allocataire.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/age_pac.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/duree_min_titre_sejour/eee.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/duree_min_titre_sejour/non_eee.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/majoration_isolement/age_limite_enfant.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/majoration_isolement/duree_du_droit.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/majoration_isolement/limite_duree_droit_majoration_isolement.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/nombre_minimal_enfants.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/patrimoine/abattement_valeur_locative_immo_non_loue.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/patrimoine/abattement_valeur_locative_terrains_non_loues.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/patrimoine/taux_interet_forfaitaire_epargne_non_imposable.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/rsa_jeune.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/rsa_jeune_en_heure.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/montant_minimum_verse.yaml
- setup.py
* Périodes concernées :  à partir du 01/06/2009
* Zones impactées : Rsa_cond
* france/openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond
* Détails :
J'ai ajouté les références législatives en vérifiant les valeurs et j'ai ajouté le last_review
> Vérif_Rsa rsa_cond

- CHANGELOG.md
- openfisca_france/model/prestations/jeunes/mobili_jeune.py
- openfisca_france/parameters/prestations_sociales/aides_jeunes/mobilite/mobili_jeune/montant/maximum.yaml
- setup.py
- tests/formulas/mobili_jeune.yaml
* Zones impactées : `model/prestations/jeunes/mobili_jeune.py`.
* Détails :
- Met à jour la variable `mobili_jeune`
- - - -
- - - -
> Met à jour la variable `mobili_jeune`

- CHANGELOG.md
- openfisca_france/parameters/marche_travail/salaire_minimum/smic/nb_heures_travail_mensuel.yaml
- openfisca_france/parameters/marche_travail/salaire_minimum/smic/smic_b_horaire.yaml
- openfisca_france/parameters/marche_travail/salaire_minimum/smic/smic_b_mensuel.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/bonification/seuil_bonification.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/bonification/seuil_max_bonification.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/bonification/taux_bonification_max.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/majoration_isolement/femmes_enceintes.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/majoration_isolement/par_enfant_charge.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/majoration_montant_maximal/couple_1_enfant_2e_enfant.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/majoration_montant_maximal/couples_seul_avec_enfant.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/majoration_montant_maximal/par_enfant_supplementaire.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/majoration_ressources_revenus_activite.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/montant_de_base.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/montant_minimum_verse.yaml
- setup.py
* Zones impactées marche_travail/salaire_minimum/smic ; prestations_sociales/solidarite_insertion/minima_sociaux/ppa
* Détails :
Ajout de références législatives 
Ajout de values
- - - -
> ajout references et values pour le SMIC et la PPA

- CHANGELOG.md
- openfisca_france/parameters/prelevements_sociaux/hsup_exo.yaml
- openfisca_france/parameters/prelevements_sociaux/pss/index.yaml
- openfisca_france/parameters/prelevements_sociaux/pss/plafond_securite_sociale_annuel.yaml
- openfisca_france/parameters/prelevements_sociaux/pss/plafond_securite_sociale_horaire.yaml
- openfisca_france/parameters/prelevements_sociaux/pss/plafond_securite_sociale_mensuel.yaml
- openfisca_france/scripts/parameters/reduce_parameters_paths.py
- setup.py
- parameters/prelevements_sociaux/hsup_exo
* Détails :
- Retire un paramètre non utilisé
> 132 harmonisation prelevements sociaux

- CHANGELOG.md
- openfisca_france/scripts/parameters/unfold_parameters.py
- setup.py
* Périodes concernées : aucune
* Zones impactées : `openfisca_france/scripts/parameters/unfold_parameters.py`.
* Détails :
- Ajout d'un script qui déplie (ie décompose en sous paramètres) un paramètre OpenFisca (ou un barème IPP).
> Ajout d'un script pour déplier le YAML d'un paramètre.

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/montant_couple.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/montant_seul.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/plafond_ressource_couple.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/plafond_ressource_seul.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/asf/montant_asf/orphelin_assimile_deux_parents.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/asf/montant_asf/orphelin_assimile_seul_parent.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/index.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/plafond_base.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/as/allocation_supplementaire/as_menage.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/as/allocation_supplementaire/as_personne_seule.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/as/plafond_ressources/index.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/as/plafond_ressources/plafond_menage.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/as/plafond_ressources/plafond_seul.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/montant_maximum_annuel/couples.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/montant_maximum_annuel/personnes_seules.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/plafond_ressources/couples.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/plafond_ressources/index.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/plafond_ressources/personnes_seules.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/avts/index.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/avts/montants_annuels.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/avts/plafonds_de_ressources_menages.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/avts/plafonds_de_ressources_personnes_seules.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/majconj/plafond_conjoint_pour_maj_pac.yaml
- setup.py
* Périodes concernées :  à partir du 01/01/2022.
* Zones impactées : `parameters/prestations_sociales`.
* Détails des Revalorisations :
- Plafond CMU
- Janvier 2022: ASPA, AS, AVTS
- Juillet 2022: ASPA
- Novembre 2022: ASF
- Ajout de references pour l'ASI
- - - -
> Revalorisations de Janvier, Juillet et Novembre 2022: CMU, ASPA, ASF, AS, AVTS

- .conda/README.md
- .conda/meta.yaml
- .github/get_pypi_info.py
- .github/workflows/workflow.yml
- CHANGELOG.md
- Makefile
- openfisca_france/parameters/taxation_indirecte/tva/taux_intermediaire.yaml
- openfisca_france/parameters/taxation_indirecte/tva/taux_majore.yaml
- openfisca_france/parameters/taxation_indirecte/tva/taux_normal.yaml
- openfisca_france/parameters/taxation_indirecte/tva/taux_normal_majore_temporaire.yaml
- openfisca_france/parameters/taxation_indirecte/tva/taux_particulier_super_reduit.yaml
- openfisca_france/parameters/taxation_indirecte/tva/taux_reduit.yaml
- openfisca_france/parameters/taxation_indirecte/tva/taux_reduit_2.yaml
- openfisca_france/scripts/check_longueur_chemins.py
- openfisca_france/scripts/check_path_length.py
- setup.py
* Détails :
- Correction de l'erreur de CI lors du merge sur master
- - - -
Ces changements modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).
- - - -
> Fix conda test on windows

- .github/workflows/workflow.yml
- CHANGELOG.md
- setup.py
* Périodes concernées : non applicable.
* Zones impactées : `.github/`.
* Détails :
- Corrige l'erreur d'intégration continue sous Linux du type `Version 3.7.9 was not found in the local cache`
- Fige l'OS à `ubuntu-20.04` pour compatibilité de versions Python suite à l'évolution `ubuntu-latest` de la v`20.04` à v`22.04` et par cohérence avec `openfisca-core`
**Informations complémentaires**
* Exemple de [job en erreur sur openfisca-france](https://github.com/openfisca/openfisca-france/actions/runs/3593197800/jobs/6049977161).
* Les versions d'ubuntu disponibles sur GitHub Actions sont listées sur [cette page](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).
* Le même problème a …
> Corrige l'erreur de build en CI suite à l'évolution d'ubuntu-latest

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/agepi/montants/hors_mayotte/maximum.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/agepi/montants/hors_mayotte/minimum.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/agepi/montants/mayotte/maximum.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/agepi/montants/mayotte/minimum.yaml
- setup.py
* Périodes concernées : à partir du 01/12/2022.
- `/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/agepi/montants`
* Détails :
- Revalorisation des montants (+ ~4%) de l'AGEPI suite à la [délibération n° 2022-57 du 23 novembre 2022 du conseil d'administration de Pôle emploi](https://www.bo-pole-emploi.org/bulletinsofficiels/deliberation-n-2022-57-du-23-novembre-2022-bope-n-2022-79.html?type=dossiers/2022/bope-n-2022-79-du-30-novembre-2022) 
- - - -
> Revalorisation des montants de l'AGEPI

- CHANGELOG.md
- openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/indice_majore_minimal.yaml
- setup.py
* Périodes concernées : à partir du 01/01/1985.
* Zones impactées : `parameters/marche_travail/remuneration_dans_fonction_publique/indice_majore_minimal.yaml`.
* Détails :
- Mise à jour du barème : vieilles valeurs (avant 1998 et depui l'origine du barème) et valeurs récentes (2022)
- Mise à jour du barème : complétion des références
- Mise à jour du barème : autres metadata
- - - -
- - - -
> Maj parametre traitement minimal FP

- CHANGELOG.md
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/enfant_marie/montant.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/personne_agee_ou_invalide/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/personne_agee_ou_invalide/montant_1.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/personne_agee_ou_invalide/montant_2.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/personne_agee_ou_invalide/plafond_1.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/personne_agee_ou_invalide/plafond_2.yaml
- setup.py
* Zones impactées : `openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/personne_agee_ou_invalide/`.
* Détails :
- Application du nettoyeur de paramètres pour harmonisation
> Reorder parameters fields

- CHANGELOG.md
- openfisca_france/model/prestations/cheque_energie.py
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/cheque_energie/aide_exceptionnelle.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/cheque_energie/baremes/plus_de_deux_ucs.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/cheque_energie/baremes/une_uc.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/cheque_energie/baremes/une_uc_a_deux_uc.yaml
- setup.py
- tests/formulas/cheque_energie/montant.yaml
* Périodes concernées : à partir du 01/12/2021.
- `parameters/prestations-sociales/solidarite_insertion/autre_solidarite/cheque_energie/aide_exceptionnelle`.
- `parameters/prestations-sociales/solidarite_insertion/autre_solidarite/cheque_energie/une_uc`.
- `model/prestations/cheque_energie`.
* Détails :
- Prise en compte du chèque énergie exceptionnel 2022
- Correction d'une erreur de paramétrage dans les chèques énergie depuis 2019.
- Ajout de références manquantes sur un changement de paramètre de 2021.
- - - -
> Cheque energie exceptionnel

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/isf.py
- openfisca_france/scripts/parameters/unfold_parameters.py
- setup.py
* Zones impactées : `scripts/parameters/unfold_parameters.py`.
* Détails :
- Permet de déplier un répertoire entier 
- Ajoute une option pour effacer les fichiers de paramètres YAML sources
- - - -
> Extend undfold_parameter

- CHANGELOG.md
- openfisca_france/parameters/impot_revenu/calcul_impot_revenu/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/abat_dom/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/decote/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/date_entree_en_vigueur/annee_ir.yaml
- openfisca_france/parameters/impot_revenu/index.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/activite/index.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/imposable/index.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/ars/index.yaml
- setup.py
* Zones impactées : `parameters/prelevements_sociaux/contributions_sociales/csg/activite/`.
* Détails :
- Ajout de champs order aux metadata de paramètres.
- - - -
Ces changements modifient des éléments non fonctionnels de ce dépôt.
> Ordonne les paramètres

- CHANGELOG.md
- openfisca_france/parameters/geopolitique/regions/auvergne_rhone_alpes/departements.yaml
- openfisca_france/parameters/geopolitique/regions/bourgogne_franche_comte/departements.yaml
- openfisca_france/parameters/geopolitique/regions/bretagne/departements.yaml
- openfisca_france/parameters/geopolitique/regions/centre_val_de_loire/departements.yaml
- openfisca_france/parameters/geopolitique/regions/corse/departements.yaml
- openfisca_france/parameters/geopolitique/regions/grand_est/departements.yaml
- openfisca_france/parameters/geopolitique/regions/guadeloupe/departements.yaml
- openfisca_france/parameters/geopolitique/regions/guyane/departements.yaml
- openfisca_france/parameters/geopolitique/regions/hauts_de_france/departements.yaml
- openfisca_france/parameters/geopolitique/regions/martinique/departements.yaml
- openfisca_france/parameters/geopolitique/regions/mayotte/departements.yaml
- openfisca_france/parameters/geopolitique/regions/normandie/departements.yaml
- openfisca_france/parameters/geopolitique/regions/nouvelle_aquitaine/departements.yaml
- openfisca_france/parameters/geopolitique/regions/occitanie/departements.yaml
- openfisca_france/parameters/geopolitique/regions/pays_de_la_loire/departements.yaml
- openfisca_france/parameters/geopolitique/regions/provence_alpes_cote_d_azur/departements.yaml
- openfisca_france/parameters/geopolitique/regions/reunion/departements.yaml
- openfisca_france/parameters/impot_revenu/index.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/ars/ars_plaf/majoration_par_enf_supp.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/prime_exceptionnelle_rentree/index.yaml
- setup.py
- `openfisca_france/parameters/geopolitique/regions/`
- `openfisca_france/parameters/impot_revenu/`
- `openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/ars/`
- `openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/prime_exceptionnelle_rentree/`
* Détails :
- Corrections de diverses erreurs dans les fichiers YAML des paramètres, dont une typo qui rendait le YAML invalide.
> Corrections parametres

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/taxe_habitation/taxe_habitation.py
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/plaf_rfr_degrev/autres_demi_parts_supp.yaml
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/plaf_rfr_degrev/deux_premieres_demi_parts_supp.yaml
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/plaf_rfr_degrev/index.yaml
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/plaf_rfr_degrev/premiere_part.yaml
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/plaf_rfr_degrev_degressif/autres_demi_parts_supp.yaml
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/plaf_rfr_degrev_degressif/deux_premieres_demi_parts_supp.yaml
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/plaf_rfr_degrev_degressif/premiere_part.yaml
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/taux_inf_plaf.yaml
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/taux_sup_plaf.yaml
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/exon_age_min.yaml
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/exon_plaf_rfr/demi_part_supp.yaml
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/exon_plaf_rfr/premiere_part.yaml
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/frais_assiette.yaml
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/maj_seuil_valeur_locative_abattement_condition_modeste.yaml
- openfisca_france/parameters/taxation_indirecte/taxe_habitation/seuil_valeur_locative_abattement_condition_modeste.yaml
- setup.py
- tests/formulas/taxe_habitation.yaml
* Périodes concernées : à partir de 2023
* Zones impactées : `prelevements_obligatoires/taxe_habitation/taxe_habitation.py`
* Détails :
- Code la suppression de la taxe d'habitation sur les résidences principales
> Code la suppression de la taxe d'habitation

- CHANGELOG.md
- openfisca_france/model/prestations/enseignement_superieur/bourse_criteres_sociaux.py
- setup.py
- tests/formulas/bourses_superieur/bourse_criteres_sociaux.yaml
- `tests/formulas/bourses_superieur/bourse_criteres_sociaux.yaml`
- `openfisca_france/model/prestations/enseignement_superieur/bourse_criteres_sociaux.py`
* Détails :
- Refacto condition d'elligibilité à la bourse aux critères sociaux selon l'année d'étude
- Déplacement du code dans une variable plus appropriée
- - - -
- - - -
> Refacto bourse_criteres_sociaux_elligibilite_etude

- openfisca_france/model/prestations/minima_sociaux/aah.py
- openfisca_france/reforms/aah_deconjugalisee.py
Récupération de l'AAH déconjugalisée, et séparation de l'AAH en deux versions, classique et déconjugalisée
> Ajout periode transitoire de l'AAH déconjugalisé pour septembre + réforme permettant le double affichage

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_0bis.yaml
- openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_1.yaml
- openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_2.yaml
- openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_3.yaml
- openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_4.yaml
- openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_5.yaml
- openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_6.yaml
- openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_7.yaml
- setup.py
* Zones impactées : `prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources`.
* Détails :
- Nettoyage des références pour passage de la validation des paramètres.
- - - -
> Fix reference

- CHANGELOG.md
- openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
- openfisca_france/model/prestations/enseignement_superieur/bourse_criteres_sociaux.py
- setup.py
- tests/formulas/bourses_superieur/bourse_criteres_sociaux.yaml
- `caracteristiques_socio_demographiques/demographie.py`
- `prestations/enseignement_superieur/bourse_criteres_sociaux.py`
* Détails :
- Ajoute une variable orphelin
- Améliore le calcul de la bourse sur critères sociaux pour les personnes orphelines.
> Ajoute une variable orphelin et adapte le calcul de BCS

- openfisca_france/model/prestations/minima_sociaux/aah.py
* Zones impactées : `openfisca_france/model/prestations/minima_sociaux/aah.py`.
* Détails :
- Les pensions alimentaires versées sont maintenant soustraites de la base de ressources de l'AAH au lieu d'y êtres additionnées.
- Si un individu versait des pensions alimentaires, le montant de son AAH était inférieur à celui qu'il aurait reçu s'il n'avait pas versé de pensions alimentaires.
- - - -
> Msa fiab aah pensions alimentaires versees

- CHANGELOG.md
- openfisca_france/conf/cache_blacklist.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_m/pente.yaml
- setup.py
- tests/formulas/ppa/ppa.yaml
- tests/formulas/rsa/rsa_celibataire.yaml
* à partir du 01/01/2016.
- `openfisca_france/model/prestations/minima_sociaux/rsa.py`.
- `openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_m/pente.yaml`.
* Détails :
- Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
- Cas dans lesquels une erreur était constatée.
- - - -
> Correction pente rsa null

- CHANGELOG.md
- openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/indice_majore_minimal.yaml
- openfisca_france/parameters/marche_travail/salaire_minimum/smic/smic_b_horaire.yaml
- openfisca_france/parameters/marche_travail/salaire_minimum/smic/smic_b_mensuel.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/montant.yaml
- setup.py
- tests/formulas/aah/aah_couple.yaml
* Périodes concernées : à partir du 01/01/2023.
- `parameters/marche_travail/salaire_minimum/smic`
- `parameters/marche_travail/remuneration_fonction_publique/indice_majore_minimal`
- `parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/montant`
* Détails :
- Revalorisation du smic horaire au premier mai
- Revalorisation de l'indice minimum de traitement dans la fonction publique du premier janvier et du premier mai
- Revalorisation de l'AAH au premier avril
- - - -
- - - -
> Revalorisation SMIC et indice majore minimal

- CHANGELOG.md
- openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/gipa/index.yaml
- openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/indicefp/index.yaml
- openfisca_france/parameters/marche_travail/salaire_minimum/smic/index.yaml
- openfisca_france/parameters/marche_travail/salaire_minimum/smic/nb_heures_travail_mensuel.yaml
- openfisca_france/parameters/marche_travail/salaire_minimum/smic/smic_b_mensuel.yaml
- openfisca_france/parameters/marche_travail/salaire_minimum/smig/index.yaml
- openfisca_france/parameters/marche_travail/salaire_minimum/smig/smig_brut_horaire/index.yaml
- setup.py
* Zones impactées : `parametres/marche_travail`.
* Détails :
- Nettoyage et harmonisation avec les barèmes IPP
> Homogeneisation

- CHANGELOG.md
- openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/complementaire_sante/index.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_m/pente.yaml
- setup.py
- `openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_m/pente.yaml`
- `openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/complementaire_sante/index.yaml`
* Détails :
- Correction de la metadata `order` d'un paramètre
- Correction d'une typo dans une metadata `reference`
> Fix metadata

- CHANGELOG.md
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/dons/dons_coluche/plafond.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/imputation_sur_le_revenu_global/plafond_deficits_agricoles.yaml
- setup.py
* Évolution du système socio-fiscal. Changement mineur.
* Périodes concernées :  à partir du 01/01/2021.
-`parameters/impot_revenu/calcul_revenus_imposables/deductions`.
- `parameters/impot_revenu/calcul_reductions_impots/dons/dons_coluche`.
* Détails :
- Mise à jour des montants d'abattement sur les pensions et les déficits agricoles
- Documente le mode de calcul
- Actualise le plafond des frais liés à l'accueil d'une personne âgée
- Documente l'extension de l'augmentation dérogatoire du plafond pour les dons coluche
- Actualise les abattements pour frais professionnels
- - - -
- - - -
> Actualisation abattements IR

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
- setup.py
* Périodes concernées : jusqu'au 01/01/2018.
* Zones impactées : `model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py`
`model/prelevements_obligatoires/impot_revenu/ir.py.`
* Détails :
- Corrige double positionnement de cncn_info dans le calcul de l'impôt
- Rajoute les plus-values de vente d'entreprise liée à un départ à la retraite dans cotisations 
- - - -
- - - -
> Plus values

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1/couples.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1/famille_1pac.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1/majoration_par_pac_supp.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1/personnes_seules.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2/couples.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2/famille_1pac.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2/majoration_par_pac_supp.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2/personnes_seules.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3/couples.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3/famille_1pac.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3/majoration_par_pac_supp.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3/personnes_seules.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel/biactifs_parents_isoles.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel/plafond_ressources_0_enfant.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_plein/plafond_ressources_0_enfant.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/majoration_plafond_par_enfant_supplementaire.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_1.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_1_base.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_2.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_2_base.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/biactifs_isoles.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_0_enfant.yaml
- setup.py
* Périodes concernées : à partir de 01/01/2023 et 01/01/2022.
- `parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1/`
- `parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2/`
- `parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3/`
- `parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/`
- `parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/`
- `parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel/`
- …
> Revalorisations des RLS, AF, CF pour 01/2023 et 01/2022 + correction de titre d'arrêté PAJE

- CHANGELOG.md
- openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/indicefp/point_indice_en_euros.yaml
- openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/indicefp/point_indice_en_nominal.yaml
- setup.py
* Évolution du système socio-fiscal.  | Changement mineur.
* Périodes concernées : à partir du 01/07/2023.
* Zones impactées : `parameters/marche_travail/remunerations_fonction_publique/indicefp`.
* Détails :
- Actualise le point d'indice en juillet 2023
- - - -
- - - -
> Point indice

- CHANGELOG.md
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/index.yaml
- setup.py
* Zones impactées : `parameters/impot_revenu/calcul_revenus_imposables/abat_rni/index.yaml`.
* Détails :
- Suppression d'un élément `order` qui ne correspond pas à un fichier existant
> Supprime un order incorrect

- CHANGELOG.md
- openfisca_france/model/mesures.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
- openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
- openfisca_france/model/prestations/minima_sociaux/rsa.py
- openfisca_france/parameters/prestations_sociales/prestations_familiales/bmaf/bmaf.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/bmaf/bmaf_e_t_i.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/bmaf/bmaf_regimes_agricoles.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/bmaf/index.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/bmaf/salaire_mensuel_base_dans_departement_seine.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/def_biactif/index.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/def_biactif/revenu_professionnel_plancher_couples_biactifs/en_nombre_fois_bmaf.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/def_biactif/revenu_professionnel_plancher_couples_biactifs/en_pourcentage_pss.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/def_biactif/revenu_professionnel_plancher_couples_biactifs/index.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/def_pac/age_max_pac_apprentissage_stage_formation_droit_aes.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/def_pac/age_maximal_personnes_charge.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/def_pac/enfants/age_intermediaire.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/def_pac/enfants/age_limite.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/def_pac/enfants/age_minimal.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/def_pac/enfants/index.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/def_pac/index.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/def_pac/revenu_plafond_pac_non_scolaire.yaml
- setup.py
- `parameters/prestations_sociales/prestations_familiales/bmaf`.
- `parameters/prestations_sociales/prestations_familiales/def_*`
* Détails :
- Corrige description, références et doc
- Corrige quelques anciennes valeurs
> Clean-presta-fam

- CHANGELOG.md
- openfisca_france/model/patrimoine/livret_epargne_populaire.py
- openfisca_france/parameters/taxation_capital/epargne/livret_a/taux.yaml
- openfisca_france/parameters/taxation_capital/epargne/livret_epargne_populaire/taux.yaml
- setup.py
- tests/patrimoine/livret_epargne_populaire/taux.yml
**Première contribution n'hésitez pas sur les retours :-)**
* Périodes concernées : à partir du 2023-08-01
- openfisca_france/model/patrimoine/livret_epargne_populaire.py
* Détails :
- Mise à jour de la formule et du taux du LEP
- Mise à jour du taux du livret A 
- - - -
> Mise a jour du taux du LEP a partir du 1er aout

- CHANGELOG.md
- setup.py
* Zones impactées : `setup.py`.
* Détails :
- Corrige le numéro de version du setup.py
> Corrige le numéro de version du setup vers 153.1.0

- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/plafond_base.yaml
* Zones impactées : `openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/plafond_base.yaml`.
* Détails :
- Changement du plafond de base de la css
- - - -
- - - -
> feat(css): ajout arrete du 2023-03-31 a effet le 2023-04-01

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux1pac.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux2pac.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux3pac.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux4pac.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux5pac.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux6pac.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux_couple.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux_pac_supp.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux_seul.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1/couples.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1/famille_1pac.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1/majoration_par_pac_supp.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1/personnes_seules.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2/couples.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2/famille_1pac.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2/majoration_par_pac_supp.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2/personnes_seules.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3/couples.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3/famille_1pac.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3/majoration_par_pac_supp.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3/personnes_seules.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/ars/ars_plaf/plafond_ressources.yaml
- openfisca_france/parameters/taxation_capital/epargne/livret_a/majoration_base.yaml
- openfisca_france/parameters/taxation_capital/epargne/livret_a/taux.yaml
- setup.py
* Périodes concernées : à partir du 01/01/2022.
-  `openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0`
- `/taux1pac.yaml`
- `/taux2pac.yaml`
- `/taux3pac.yaml`
- `/taux4pac.yaml`
- `/taux5pac.yaml`
- `/taux6pac.yaml`
- `/taux_couple.yaml`
- `/taux_pac_supp.yaml`
- `/taux_seul.yaml`
- `openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1`
- `/couples.yaml`
- `/famille_1.yaml`
- `/majoration_par_pac_supp.yaml`
- `/personnes_seules.yaml`
- `openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2`
- `/couples.yaml`
- `/famille_1.yaml`
- `/majoration_par_pac_supp.yaml` …
> Revalorisations des R0, RLS, AF, CF et Taux LEP + correction de référence ARS à partir de 01/01/2022

- CHANGELOG.md
- openfisca_france/parameters/taxation_capital/epargne/livret_a/taux.yaml
- setup.py
* Détails :
- Correction d'une erreur sur champ de paramètres, n'affectant pas les calculs, qui n'est plus valide
> Remove last_review

- CHANGELOG.md
- openfisca_france/parameters/impot_revenu/bareme_ir_depuis_1945/bareme.yaml
- openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/decote/seuil_celib.yaml
- openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/decote/seuil_couple.yaml
- openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/plafond_avantages_procures_par_demi_part/celib.yaml
- openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/plafond_avantages_procures_par_demi_part/celib_enf.yaml
- openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/plafond_avantages_procures_par_demi_part/general.yaml
- openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/plafond_avantages_procures_par_demi_part/reduc_postplafond.yaml
- openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/plafond_avantages_procures_par_demi_part/reduc_postplafond_veuf.yaml
- openfisca_france/parameters/marche_travail/salaire_minimum/smic/smic_b_horaire.yaml
- openfisca_france/parameters/marche_travail/salaire_minimum/smic/smic_b_mensuel.yaml
- setup.py
- tests/formulas/prime_partage_valeur.yaml
* Périodes concernées : à partir du 01/01/2024.
* Zones impactées : `parameters/marche_travail/salaire_minimum/smic`.
* Détails :
- Mise à jour de certains paramètres pour 2024 : le SMIC, le barème de l'IR, le plafonnement du quotient familial
- Modifie un test utilisant l'IR 2023
- - - -
- - - -
> Revalorisation 2024 : SMIC, barème

- CHANGELOG.md
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/enfant_marie/montant.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/pensions_alimentaires/plafond.yaml
- setup.py
* Périodes concernées : à partir du 01/01/2024.
- `openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/pensions_alimentaires/plafond.yaml`.
- `openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/pensions_alimentaires/plafond.yaml`
* Détails :
- Met à jour un abattement de l'IR 
- - - -
> Update param ir

- openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel/biactifs_parents_isoles.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel/plafond_ressources_0_enfant.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_plein/biactifs_parents_isoles.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_plein/plafond_ressources_0_enfant.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/biactifs_isoles.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_0_enfant.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_majoration/biactifs_isoles.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_majoration/couple_avec_1_revenu.yaml
* Périodes concernées :à partir du 01/01/2024.
- `parameters/prestations_sociales/prestations_familiales`
- `/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018`
- `/taux_partiel`
- `/biactifs_parents_isoles.yaml`
- `/plafond_ressources_0_enfant.yaml`
- `/taux_plein`
- `/biactifs_parents_isoles.yaml`.
- `/plafond_ressources_0_enfant.yaml`
- `/prestations_generales/cf/cf_plaf`
- `/majoration/biactifs_isoles.yaml`
- `/plafond_ressources_0_enfant.yaml` 
* Détails :
- Revalorisation des plafinds de la Prestation d'Accueil du Jeune Enfant (PAJE)
- Revalorisation des plafonds du Complément Familial (CF)
- - - -
> Revalorisation janvier 2024 PAJE et CF

- CHANGELOG.md
- openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/charges_deductibles.py
- openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
- openfisca_france/model/revenus/activite/salarie.py
- setup.py
- `openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py`.
- `openfisca_france/model/caracteristiques_socio_demographiques/demographie.py`
- `openfisca_france/model/prelevements_obligatoires/impot_revenu/charges_deductibles.py`
- `openfisca_france/model/revenus/activite/salarie.py`
* Détails :
- Annualise la variable caseT qui est une case de la déclaration annuelle de l'impôt sur le revenu
- Ajoute des variables de revenus assimilés salaire
- Ajoute les cases fiscales des nouveau plan d'épargne retraite
- - - -
> Divers fix impot revenu

- CHANGELOG.md
- openfisca_france/parameters/taxation_capital/epargne/livret_epargne_populaire/taux.yaml
- setup.py
* Périodes concernées : à partir du 01/02/2024.
* Zones impactées : `openfisca_france/model/patrimoine/livret_epargne_populaire.py`.
* Détails :
- Mise à jour du taux de rémunération du Livret d'Épargne Populaire
> Met à jour le taux du LEP

- CHANGELOG.md
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/pme/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/pme/souscription_capital/index.yaml
- setup.py
> Harmonisation index

- CHANGELOG.md
- openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/montant_plein.yaml
- openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/montant_plein_mayotte.yaml
- openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/plaf_coup.yaml
- openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/plaf_seul.yaml
- setup.py
* Zones impactées : `openfisca_france/parameters/chomage/allocations_assurance_chomage/ass`.
* Détails :
- Met à jour les valeurs de l'ASS à partir d'avril 2023
- Ajoute des références pour des paramètres de l'ASS
- - - -
- - - -
> Ass maj params

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py
- openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/chomage.py
- setup.py
- tests/formulas/csg/csg_remplacement.yaml
* Zones impactées : `model/revenus/remplacement/chomage.py`.
* Détails :
- Corrige, dans l'assiette de la CSG/CRDS pour le chomage, la cotisation retraite complementaire (passage d'une valeur journalière à mensuelle)
- - - -
- - - -
> Prelevements sociaux chomage

- CHANGELOG.md
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/investissements_immobiliers/duflot_pinel_denormandie/location_6_ans/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/investissements_immobiliers/duflot_pinel_denormandie/location_6_ans/taux_metro.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/investissements_immobiliers/duflot_pinel_denormandie/location_6_ans/taux_om.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/investissements_immobiliers/duflot_pinel_denormandie/location_9_ans/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/investissements_immobiliers/duflot_pinel_denormandie/location_9_ans/taux_metro.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/investissements_immobiliers/duflot_pinel_denormandie/location_9_ans/taux_om.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/investissements_immobiliers/duflot_pinel_denormandie/plafond.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/investissements_immobiliers/duflot_pinel_denormandie/taux_prolongation/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/investissements_immobiliers/duflot_pinel_denormandie/taux_prolongation/taux_prolong1_6ans.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/investissements_immobiliers/duflot_pinel_denormandie/taux_prolongation/taux_prolong2_6ans.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/investissements_immobiliers/duflot_pinel_denormandie/taux_prolongation/taux_prolong_9ans.yaml
- setup.py
* Zones impactées : ` openfisca_france/parameters/impot_revenu/calcul_reductions_impots/investissements_immobiliers/duflot_pinel_denormandie`.
* Détails :
- Ajoute des index
- - - -
> Fix harmonisatioin credit immo

- CHANGELOG.md
- openfisca_france/parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general/famille/employeur/famille.yaml
- setup.py
* Zones impactées : `parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general/famille/employeur/famille`.
* Détails :
- Retire les tranches d'un barème en conservant les premières et en retirant les dernières.
> Clean cotis famille

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_etudiant/autres_etudiants_en_chambres_rehabilitees_de_ru/menages.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_etudiant/autres_etudiants_en_chambres_rehabilitees_de_ru/personnes_isolees.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_etudiant/loyer_considere_comme_paye_etudiants_logeant_en_ru/menages.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_etudiant/loyer_considere_comme_paye_etudiants_logeant_en_ru/personnes_isolees.yaml
- setup.py
* Périodes concernées : à partir du 01/10/2023.
* Zones impactées : `prestations_sociales.aides_logement.allocations_logement.al_etudiant`.
* Détails :
- Mise à jour des équivalences de loyer, en complément de https://github.com/openfisca/openfisca-france/pull/2208 A noter que les paramètres mis à jour ne semblent pas utilisés dans le moteur de calcul, d'où l'absence de tests.
- - - -
- - - -
> Revalorisations APL étudiants

- CHANGELOG.md
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/deductible/abattement.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/deductible/taux.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/imposable/abattement.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/imposable/taux.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/index.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/taux_global.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/index.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/allocations_chomage/deductible/abattement.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/allocations_chomage/imposable/abattement.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/allocations_chomage/imposable/taux_reduit.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/allocations_chomage/min_exo.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/allocations_preretraite/imposable/taux_reduit.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/index.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/imposable/taux_reduit.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/taux_plein.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/taux_reduit.yaml
- setup.py
* Zones impactées : `parameters/prelevements_sociaux/csg`.
* Détails :
- Élimine des doublons de documentation
> Prelev sociaux 2

- CHANGELOG.md
- openfisca_france/parameters/prelevements_sociaux/cotisations_secteur_public/mmid/colloc/sous_plafond/employeur/maladie.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_secteur_public/mmid/colloc/sous_plafond/salarie/maladie.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_secteur_public/mmid/etat/sous_plafond/employeur/maladie.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_secteur_public/mmid/etat/sous_plafond/salarie/maladie.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general/cnav/employeur/vieillesse_plafonnee.yaml
- openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/allegement_general/ensemble_des_entreprises/entreprises_de_moins_de_50_salaries.yaml
- openfisca_france/units.yaml
- setup.py
* Zones impactées : `parameters`.
* Détails :
- Tri des tranches des barèmes par seuil croissant
- Correction de l'indentation dans une metadata
- Homogénéïsation des units avec les barèmes IPP et le simulateur LexImpact
> Tri des tranches des barèmes ; amélioration des units ; correction d'une metadata

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/education/contrat_engagement_jeune/montants/montant_majeurs_1ere_tranche_ir.yaml
- openfisca_france/parameters/prestations_sociales/education/contrat_engagement_jeune/montants/montant_majeurs_non_imposables.yaml
- openfisca_france/parameters/prestations_sociales/education/contrat_engagement_jeune/montants/montant_mineurs.yaml
- setup.py
* Périodes concernées : à partir du 01/04/2024.
* Zones impactées : `prestations/jeunes/contrat_engagement_jeune.py`.
* Détails :
- Actualise les montants forfaitaires du CEJ suite aux revalorisations pour le 1er avril 2024.
> Actualise les montants forfaitaires du CEJ

- openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/montant_plein.yaml
- openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/montant_plein_mayotte.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/montant.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/plafond_ressource_couple.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/plafond_ressource_seul.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/bmaf/bmaf.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/plafond_base.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/montant_de_base.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_m/montant_de_base_du_rsa.yaml
Évolution du système socio-fiscal. | Amélioration technique. | Correction d'un crash. | Changement mineur.
Périodes concernées : à partir du 01/04/2024.
Zones impactées : [
openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/montant_plein.yaml,
openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/montant_plein_mayotte.yaml,
openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/montant.yaml,
openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/plafond_ressource_couple.yaml,
openfisca_france/parameters/prestations_sociales/prestations_etat_ …
> Msa release big brother

- CHANGELOG.md
- openfisca_france/parameters/chomage/allocations_assurance_chomage/alloc_base/montant_minimal_are_formation.yaml
- openfisca_france/parameters/chomage/allocations_assurance_chomage/alloc_base/montant_minimum/apres_1979/mayotte.yaml
- openfisca_france/parameters/chomage/allocations_assurance_chomage/alloc_base/montant_minimum/apres_1979/montant_minimum_hors_mayotte.yaml
- openfisca_france/parameters/chomage/allocations_assurance_chomage/alloc_base/partie_fixe/apres_1992/partie_fixe.yaml
- setup.py
* Périodes concernées :à partir du 01/07/2024.
* Zones impactées : `parameters/chomage/allocations_assurance_chomage/alloc_base`.
* Détails :
- Met à jour les paramètres de l'ARE pour 2024
- - - -
- - - -
> Revalorise ARE juillet 2024

- CHANGELOG.md
- openfisca_france/parameters/marche_travail/index.yaml
- openfisca_france/parameters/prestations_sociales/education/contrat_engagement_jeune/montants/montant_majeurs_1ere_tranche_ir.yaml
- openfisca_france/parameters/prestations_sociales/education/contrat_engagement_jeune/montants/montant_majeurs_non_imposables.yaml
- openfisca_france/parameters/prestations_sociales/education/contrat_engagement_jeune/montants/montant_mineurs.yaml
- openfisca_france/parameters/taxation_capital/epargne/livret_epargne_populaire/coefficient_multiplicateur.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_assurance_vie/bons_contrats_placements/apres_le_1_1_90/duree_8_ans_et_primes_avant_1998.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_assurance_vie/bons_contrats_placements/apres_le_1_1_90/index.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_assurance_vie/bons_contrats_placements/entre_1_1_83_et_31_12_89/index.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_assurance_vie/bons_contrats_placements/index.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_taux_fixe/bons_banque_tresor_epargne_ptt/emis_a_partir_de_1_1_1998_avec_anonymat.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_taux_fixe/bons_banque_tresor_epargne_ptt/emis_a_partir_du_1_1_95_et_sans_anonymat.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_taux_fixe/bons_banque_tresor_epargne_ptt/emis_avant_1_6_78.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_taux_fixe/bons_banque_tresor_epargne_ptt/emis_entre_1_1_83_et_1_1_1998_avec_anonymat.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_taux_fixe/bons_banque_tresor_epargne_ptt/emis_entre_1_1_83_et_31_12_89_sans_anonymat.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_taux_fixe/bons_banque_tresor_epargne_ptt/emis_entre_1_1_90_et_31_12_94_sans_anonymat.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_taux_fixe/bons_banque_tresor_epargne_ptt/emis_entre_1_6_78_et_20_1_80.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_taux_fixe/bons_banque_tresor_epargne_ptt/emis_entre_21_1_80_et_31_12_82_avec_anonymat.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_taux_fixe/bons_banque_tresor_epargne_ptt/emis_entre_21_1_80_et_31_12_82_sans_anonymat.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_taux_fixe/bons_banque_tresor_epargne_ptt/index.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_taux_fixe/plan_d_epargne_populaire/index.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_taux_fixe/plan_d_epargne_populaire/retrait_apres_8_ans.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_taux_fixe/plan_d_epargne_populaire/retrait_avant_4_ans.yaml
- openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/liberatoire_taux_fixe/plan_d_epargne_populaire/retrait_entre_4_et_8_ans.yaml
- setup.py
-  `parameters/marche_travail`
- `parameters/taxation_capital`
- `parameters/prestations_sociales/education/contrat_engagement_jeune`
* Détails :
- Harmonisation avec les barèmes IPP
- Nettoyage des champs note, index et documentation
> Harmonisation avec les Barèmes IPP

- CHANGELOG.md
- openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/indemnite_residence/taux/zone1.yaml
- openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/indemnite_residence/taux/zone2.yaml
- openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/indemnite_residence/taux/zone3.yaml
- setup.py
- `openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/indemnite_residence/taux/*`
* Détails :
- Met à jour la description
- Ajoute une référence, le `short_label` et `last_value_still_valid_on`
> màj : Indemnité de résidence dans la fonction publique

- CHANGELOG.md
- openfisca_france/model/prestations/jeunes/pass_sport.py
- setup.py
- tests/formulas/pass_sport.yaml
* Évolution du système socio-fiscal. | Amélioration technique. | Correction d'un crash. | Changement mineur.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
- Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
- Cas dans lesquels une erreur était constatée.
- - - -
- Ajoutent une fonctionnalité (par exemple ajout d'une …
> Corrige le calcul d'éligibilité ars & aeeh pour le pass'Sport

- CHANGELOG.md
- openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/alleg_gen/mmid/index.yaml
- setup.py
* Zones impactées : `parameters`.
* Détails :
- Correction d'index.
> Minor-fix-bis

- CHANGELOG.md
- openfisca_france/parameters/impot_revenu/calcul_impot_revenu/pv/bspce/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_impot_revenu/pv/bspce/taux_moins_3_ans.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/divers/rehabilitation_residences_touristiques/plafond.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/divers/rehabilitation_residences_touristiques/taux.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/divers/restauration_patrimoine_bati/taux_22.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/dons/dons_aux_partis_politiques/plafond_seul.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/dons/dons_cultuels/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/dons/taux_reduction.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/index.yaml
- pyproject.toml
- `parameters/impot_revenu/calcul_impot_revenu/pv/bspce/index.yaml`
- `parameters/impot_revenu/calcul_impot_revenu/pv/bspce/taux_moins_3_ans.yaml`
- `parameters/impot_revenu/calcul_reductions_impots/divers/rehabilitation_residences_touristiques/plafond.yaml`
- `parameters/impot_revenu/calcul_reductions_impots/divers/rehabilitation_residences_touristiques/taux.yaml`
- `parameters/impot_revenu/calcul_reductions_impots/divers/restauration_patrimoine_bati/taux_22.yaml`
- `parameters/impot_revenu/calcul_reductions_impots/dons/dons_aux_partis_politiques/plafond_seul.yaml`
- `parameters/impot_revenu/calcul_reductions_impots/dons/dons_cultuels/index.yaml`
- `parameters/impot_revenu/calcul_reductions_impots/dons/taux_reduction …
> Corrige les erreurs du Control Center suite PR réductions d'impôts

- CHANGELOG.md
- openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot_plafonnees.py
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/sofica/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/sofica/plafond.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/sofica/plafond_revenu_net_global.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/sofica/taux_majore_1.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/sofica/taux_majore_2.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/sofica/taux_reduction_normal.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/sofipeche/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/souscriptions_parts_fcpi_fip/index.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/souscriptions_parts_fcpi_fip/plafond_celibataire.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/souscriptions_parts_fcpi_fip/plafond_couple.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/souscriptions_parts_fcpi_fip/taux.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/souscriptions_parts_fcpi_fip/taux_corse.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/souscriptions_parts_fcpi_fip/taux_outre_mer.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/souscriptions_parts_fcpi_fip/taux_special.yaml
- pyproject.toml
* Évolution intermédiaire du système socio-fiscal
* `model/prelevements_obligatoires/impot_revenu/reductions_impot_plafonnees.py`.
* `parameters/impot_revenu/calcul_reductions_impots/souscriptions/sofica`.
* `parameters/impot_revenu/calcul_reductions_impots/souscriptions/souscriptions_parts_fcpi_fip`.
* Détails :
- Dossier réduc d'impôt SOFICA : renommage des paramètres pour les rendre explicites et changement dans les formules
- Dossier FCPI / FPI : labels et références
- - - -
> Paramètres souscriptions capital

- openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/cheque_energie/baremes/plus_de_deux_ucs.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/cheque_energie/baremes/une_uc.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/cheque_energie/baremes/une_uc_a_deux_uc.yaml
- tests/formulas/cheque_energie/montant.yaml
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
- Passage du chèque énergie à une période annuelle (retour au master).
- Revalorisation du 01/01/2023 des barèmes du chèque énergie.
- - - -
- - - -
> Retour au master période chèque énergie et reval 2023 des barèmes

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/bonification/seuil_max_bonification.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/bonification/taux_bonification_max.yaml
- pyproject.toml
- tests/formulas/ppa/ppa_2018.yaml
* Évolution du système socio-fiscal. Changement mineur.
* Périodes concernées :  jusqu'au 01/01/2019. | à partir du 01/10/2018.
* Zones impactées : `parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m`.
* Détails :
- Fait passer date de réforme à octobre 2018, date où les salaires concernés par les nouveaux calculs de PA débutent (c'est explicite dans le décrets associés).
- - - -
- - - -
> Corrige PA autour de la réforme de 2018

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/montant_maximum_annuel/couples.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/montant_maximum_annuel/personnes_seules.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/plafond_ressources/couples.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/plafond_ressources/personnes_seules.yaml
- pyproject.toml
* Périodes concernées : à partir du 01/01/2025
* Zones impactées : `openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa`.
* Détails :
- Ajoute les revalorisations du 1e janvier 2025
- - - -
- …
> Met à jour les paramètres de l'aspa pour 2025

- CHANGELOG.md
- openfisca_france/model/prestations/minima_sociaux/ppa.py
- pyproject.toml
- tests/formulas/rsa/rsa_condition_nationalite.yaml
* Périodes concernées : à partir du 01/01/2016.
* Zones impactées : `model/prestations/minima_sociaux/ppa.py`.
* Détails :
- Ajoute le critère d'éligibilité sur la nationalité à la PPA
- - - -
- - - -
> Ajoute condition nationalite ppa

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/ressources/dar_12.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel/plafond_ressources_0_enfant.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/plaf_cmg/deuxieme_plafond_ne_adopte_apres_04_2014/deux_enfants.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/plaf_cmg/deuxieme_plafond_ne_adopte_apres_04_2014/enfant.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/plaf_cmg/deuxieme_plafond_ne_adopte_apres_04_2014/majoration_enfant_supp.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/plaf_cmg/premier_plafond_ne_adopte_apres_04_2014/deux_enfants.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/plaf_cmg/premier_plafond_ne_adopte_apres_04_2014/enfant.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/plaf_cmg/premier_plafond_ne_adopte_apres_04_2014/majoration_enfant_supp.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/majoration_plafond_par_enfant_supplementaire.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_1.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_1_base.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_2.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_2_base.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/biactifs_isoles.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_0_enfant.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_majoration/biactifs_isoles.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_majoration/couple_avec_1_revenu.yaml
- pyproject.toml
* Périodes concernées : à partir du 01/01/2025.
* `openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/ressources`
* `openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/plaf_cmg`
* `openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress`
* `openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf`
* Détails :
- Revalorisations de plusieurs paramètres pour les prestations familiales.
- - - -
> Revalorisations de paramètres pour les prestations familiales pour 2025-01

- CHANGELOG.md
- openfisca_france/model/prestations/bail_reel_solidaire.py
- pyproject.toml
* Périodes concernées : à partir du 01/07/2024.
* Zones impactées : `openfisca_france/model/prestations/bail_reel_solidaire.py`.
* Détails :
- Utilisation de pkg_resources pour charger le fichier CSV (celui ci n'était pas correctement récupéré lors d'utilisation externe)
- Refactorisation des variables liées au Bail Réel Solidaire
- Simplification de la logique de calcul des plafonds et de l'éligibilité  - Cas dans lesquels une erreur était constatée.
- - - -
- - - -
> Amélioration récupération du CSV pour le Bail Réel solidaire

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/education/depart1825/age/maximum.yaml
- openfisca_france/parameters/prestations_sociales/education/depart1825/age/minimum.yaml
- openfisca_france/parameters/prestations_sociales/education/depart1825/montant_maximum.yaml
- openfisca_france/parameters/prestations_sociales/education/depart1825/proportion_maximum.yaml
- openfisca_france/parameters/prestations_sociales/education/mobilite/internationale/duree_sejour/mois_max.yaml
- openfisca_france/parameters/prestations_sociales/education/mobilite/internationale/duree_sejour/mois_min.yaml
- openfisca_france/parameters/prestations_sociales/education/pass_colo/montants.yaml
- pyproject.toml
* Périodes concernées :  à partir du 01/01/2018.
* Zones impactées : `parameters/prestations_sociales/education`.
* Détails :
- Met à jour et documente les paramètres relatifs à l'aide à la mobilité internationale, au pass colo et au départ1825.
- - - -
- - - -
> Harmonise aides aux voyages des jeunes

- CHANGELOG.md
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/location_meublee/plafond.yaml
- openfisca_france/parameters/impot_revenu/calcul_reductions_impots/outremer_investissement/plafond.yaml
- openfisca_france/parameters/marche_travail/indemnite_fin_contrat/taux.yaml
- openfisca_france/parameters/marche_travail/primes_exceptionnelles/prime_partage_valeur/plafond_exoneration.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/cont_sur_options/salarie/taux_plein.yaml
- openfisca_france/parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general/casa/pensions_retraite_preretraite_invalidite.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_plaf_acc/zone_1/personne_isolee_sans_enfant.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_plaf_acc/zone_3/menage_ou_isole_avec_2_enfants.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_plaf_acc/zone_3/menage_ou_isole_par_enfant_en_plus.yaml
- openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_plaf_acc/zone_3/menage_seul.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/age_fin_educ.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/age_minimal.yaml
- openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/decote/borne_superieure_decote.yaml
- openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/decote/taux_decote.yaml
- openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/plaf/plafonnement_taux_imposition.yaml
- pyproject.toml
openfisca_france/parameters/impot_revenu/calcul_reductions_impots/location_meublee/plafond.yaml
openfisca_france/parameters/impot_revenu/calcul_reductions_impots/outremer_investissement/plafond.yaml
openfisca_france/parameters/marche_travail/indemnite_fin_contrat/taux.yaml
openfisca_france/parameters/marche_travail/primes_exceptionnelles/prime_partage_valeur/plafond_exoneration.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/cont_sur_options/salarie/taux_plein.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general/casa/pensions_retraite_preretraite_invalidite.yaml …
> [paramètres] Mise à jour des last_value_still_valid_on

- CHANGELOG.md
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/rsa_jeune_en_heure.yaml
- pyproject.toml
* Périodes concernées : aucune
* Zones impactées : `openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/rsa_jeune_en_heure.yaml`.
* Détails :
- Corrige le problème de cohérence de date sur le RSA jeune : https://control-center.tax-benefit.org/parameters/61352/github.com/openfisca/openfisca-france/master/raw_unprocessed_parameters/errors
- - - -
- - - -
> [paramètres] Corrige le problème de cohérence de date sur le RSA jeune

- CHANGELOG.md
- openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/montant_plein.yaml
- openfisca_france/parameters/prestations_sociales/education/contrat_engagement_jeune/montants/montant_majeurs_1ere_tranche_ir.yaml
- openfisca_france/parameters/prestations_sociales/education/contrat_engagement_jeune/montants/montant_majeurs_non_imposables.yaml
- openfisca_france/parameters/prestations_sociales/education/contrat_engagement_jeune/montants/montant_mineurs.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/montant.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/plafond_ressource_couple.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/asi/plafond_ressource_seul.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/bmaf/bmaf.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/montant_de_base.yaml
- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_m/montant_de_base_du_rsa.yaml
- pyproject.toml
* Évolution du système socio-fiscal. | Amélioration technique. | Correction d'un crash. | Changement mineur.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
- Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
- Cas dans lesquels une erreur était constatée.
- - - -
- Ajoutent une fonctionnalité (par exemple ajout d'une …
> revalorisation des prestations sociales en avril 2025

- openfisca_france/model/prestations/prestations_familiales/paje.py
- tests/formulas/paje/paje_adoption.yaml
Process interne à la MSA pour leurs releases, la description détaillée des changements est disponible dans la PR #2542 .
> MSA release Gigowatt - TDP-1441

- .github/workflows/workflow.yml
- CHANGELOG.md
- Makefile
- pyproject.toml
* Périodes concernées : aucune.
* Détails :
- Mise à jour de la CI pour tester Python 3.13.
- Améliorations de la doc.
- Petits ajustement pour que tout fonctionne.
- - - -
- - - -
> Compatibilité Python 3.13
