openfisca/openfisca-france

openfisca_france/model/aides_logement.py
openfisca_france/model/cotisations_sociales/travail_fonction_publique.py
openfisca_france/model/cotisations_sociales/travail_totaux.py
openfisca_france/model/input_variables/base.py
openfisca_france/model/minima_sociaux/rsa.py
openfisca_france/model/pfam.py
openfisca_france/model/prestations_familiales/af.py
openfisca_france/model/prestations_familiales/ars.py
openfisca_france/model/prestations_familiales/asf.py
openfisca_france/model/prestations_familiales/cf.py
openfisca_france/model/prestations_familiales/paje.py
openfisca_france/param/param.xml

Hello,
Voici un package de commit à merger d'urgence (après review) car avec gros potentiel de conflits insolubles si divergence.
En plus d'ajustements sur les AL, il y a l'implémentation de la neutralisation des ressources qui ne sont plus perçues pour le RSA, ainsi qu'une refonte importante des sous-jacents des prestations familiales.
__Neutralisation des ressources pour le RSA__
Désormais le calcul du RSA examine les ressources qui ne sont plus versées, afin d'appliquer le cas échéant de __neutraliser ces ressources__. Cela signifie que pour par exemple calculer un RSA en avril, il faut non seulement les salaires janvier-février-mars, __mais aussi avril__ (en tout cas une valeur non-nulle) !
__Refonte dans les prestations familiales__
Plusieurs formules avec les anciennes périodes ont …

Progression Mes-Aides 03/03/2015

---

openfisca_france/tests/formulas/af.yaml
openfisca_france/tests/formulas/gratification_stage.yaml

@eraviart @jdesboeufs @nanocom @fpagnoux : remaining falling af tests are related to a probem with twins in majoration pour age des allocations familiales

Modify absolute error margin to make yearly converted af tests to pass

---

openfisca_france/model/caracteristiques_socio_demographiques/logement.py
openfisca_france/model/prestations/aides_logement.py

Jusqu'à maintenant il y avait incohérence entre openfisca et mes-aides : openfisca considérait que "3" signifiait  HLM, alors que mes-aides considérait qu'il s'agissait d'un foyer. 
=> Création d'une nouvelle valeur pour les foyer (7) 
Depends on #258 
Depends on https://github.com/sgmap/mes-aides-api/pull/21
Connected to https://github.com/sgmap/mes-aides-ui/issues/74

Distinction entre loyer et hlm dans statut_occupation

---

openfisca_france/param/param.xml

UTF-8 is a common standard nowadays, the leading `U+FEFF` in `param.xml` is noise.

Remove BOM from XML file

---

openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
openfisca_france/param/param.xml
openfisca_france/tests/embauche.sgmap.fr/taxe_apprentissage.yaml
openfisca_france/tests/fiches_de_paie/coordinatrice_2014-03.yaml
openfisca_france/tests/fiches_de_paie/ingenieur_etude_2014-07.yaml

Changement du taux de la taxe d'apprentissage (qui passe de `0.005` à `0.0068`).
Suppression de la contribution au développement de l'apprentissage (qui était de `0.0018`, elle a donc été simplement ajoutée à la taxe).
**Source**
- Augmentation du taux de la taxe : [ LOI n° 2013-1279 du 29 décembre 2013 de finances rectificative pour 2013, article 60](http://www.legifrance.gouv.fr/affichTexteArticle.do;jsessionid=9B99F4419C389C9F14A3E75337896643.tpdila22v_1?cidTexte=JORFTEXT000028400921&idArticle=LEGIARTI000028428572&dateTexte=20131230)
> 5° A la fin du deuxième alinéa de l'article 1599 ter B, le pourcentage : « 0,50 % » est remplacé par le pourcentage : « 0,68 % » ; 
> Le présent article s'applique pour les contributions et taxe dues au titre des rémunérations versées à compter du 1er …

Taxe apprentissage

---

openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
openfisca_france/param/param.xml
openfisca_france/tests/formulas/formation_professionnelle.yaml

Mise à jour du taux de la contribution à la formation professionnelle continue. 
> Pour les contributions calculées sur les rémunérations versées en 2015 et recouvrées en 2016, les taux ont été modifiés : la contribution est dorénavant unique de 1 % pour les entreprises à partir de 10 salariés (le seuil de 20 salariés disparaît). 
[Décret](http://www.legifrance.gouv.fr/eli/decret/2014/10/24/ETSD1418587D/jo) (article 9) qui détaille la répartition des cotisations, et donc les taux par taille d'entreprise. 
Et notre cher [service-public.fr](https://www.service-public.fr/professionnels-entreprises/vosdroits/F22570)

Taux formation pro

---

openfisca_france/model/prestations/aides_logement.py
openfisca_france/model/prestations/minima_sociaux/cmu.py
openfisca_france/model/prestations/minima_sociaux/rsa.py

Use `situation_occupation_famille` instead of heavy entity casting.
Btw, is there any *practical* reason why `statut_occupation` is related to a `Menage` ? It seems like it is always used  in the context of a `Famille`.
(This caused @kinta95 some trouble, as she was trying to declare a `statut_occupation` for a `Familles` in yaml tests, which sounds pretty natural)

Simplify situation_occupation in al, cmu, rsa

---

openfisca_france/param/param.xml

See https://github.com/openfisca/openfisca-core/issues/368 and the [source](https://github.com/openfisca/openfisca-core/issues/368#issuecomment-168713564) of the param history.
IM_max appears to be the only rate breaking tests after @cbenz 's [fix](https://github.com/openfisca/openfisca-france/commit/7b881be35aebe830eadad64b3af102479ac2141d)

Add historical supp_fam IM_max param

---

openfisca_france/model/prestations/minima_sociaux/ppa.py

"L'AAH est prise en compte à 100%, en tant que prestation sociale, pour le calcul de la prime d'activité : L. 842-4, R. 844-4 et R. 844-5 CSS." — https://mes-aides.gouv.fr/tests/5693d5e8ab1adc4751a7cb46/show

Include AAH in PPA resources

---

openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
openfisca_france/param/param.xml

Le taux du coefficient a changé en 2016.
[source](https://www.urssaf.fr/portail/sites/urssaf/home/employeur/beneficier-dune-exoneration/exonerations-generales/la-reduction-generale.html)

Update taux fillon

---

openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/apprentissage.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
openfisca_france/param/param.xml
openfisca_france/tests/formulas/taux_versement_transport.yaml

Il passe de 10 à 11. 
Référence : Loi de finances 2016 - article 4 "Limitation des effets de seuils dans les TPE et les PME"

Update seuil versement transport2016

---

openfisca_france/param/param.xml

Garantie minimale des salaires.
Baisse du taux : 
>Pour 2016, la cotisation AGS passe à 0,25 %, alors qu'elle était fixée à 0,30 % depuis avril 2011.
[Source service-public.fr](https://www.service-public.fr/professionnels-entreprises/actualites/006582)

Update taux AGS

---

openfisca_france/param/param.xml

Le taux a changé légèrement. 
[Source](https://www.urssaf.fr/portail/home/taux-et-baremes/taux-de-cotisations/les-employeurs/les-taux-de-cotisations-de-droit.html) urssaf (**attention** le tableau URSSAF inclut la CSA dans la ligne MMID, nous l'avons séparé dans OpenFisca). 
[Lien](http://www.netpme.fr/info-conseil-1/gestion-entreprise/gestion-quotidienne/gestion-paie/actualite/114381-paie-ce-qui-change-au-1er-janvier-2016#augmentation-des-cotisations-patronales-dassurance-maladie) avec la référence du décret.

Update taux contribution assurance maladie patronale

---

.gitignore
openfisca_france/__init__.py
openfisca_france/model/extensions/README.md
openfisca_france/model/extensions/__init__.py
openfisca_france/model/model.py

With mes-aides, we had, in several contexts, the need for **formulas that would not be included by default in the general openfisca france model**. The most significant example si local prestations (e.g Paris). The idea is to avoid polluting the country general model with specific formulas that most people don't need.
We first used *reforms* to do this. From my understanding, *reforms* were originally implemented to allow economists to experiment modifying parameters or formulas, in order to compare results between this reformed tax benefit system and the original one.
We were able in the beginning to use reforms as a way to insulate local prestations, but it was not pleasant and definitely not scalable. As it was designed for another purpose that ours, it offered features we did not …

Introduce extension mechanism

---

openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
openfisca_france/tests/fiches_de_paie/apprenti.yaml
openfisca_france/tests/formulas/cout_du_travail.yaml
openfisca_france/tests/formulas/participation_effort_construction.yaml
openfisca_france/tests/formulas/salaire_super_brut.yaml
openfisca_france/tests/formulas/salaire_super_brut_hors_allegements.yaml

Le seuil de 20 employés n'était pas pris en compte. 
La seule erreur flagrante pour de nombreux utilisateurs du simulateur d'embauche en février 2016 :+1: 
Le `preprocessing.py` (encore lui !) rendait cette erreur moins visible...

Correction seuil effort construction

---

openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
openfisca_france/tests/fiches_de_paie/business_develop_2015-02.yaml

Sur la [page du pacte de résponsabilité](http://www.economie.gouv.fr/pacte-responsabilite/cice/faq/cumul-autres-avantages) :
Donc peut se cumuler avec l’exonération de charges JEI.
@benjello Ou avais-tu vu que le cumul n'était pas possible ?

Let CICE be combined with JEI

---

openfisca_france/tests/test_yaml.py

I think we all agree that this is not very useful information to debug when travis doesn't pass: 
To remove that, I see two easy solutions, and I would like your advice @cbenz @laem @benjello.
- Set `debug` to false in `test_yaml.py`. It is the implementation suggested here. I don't exactly know what activating `debug` means, does it have other effects that were useful to anyone when running tests ?
- Get rid of the `log.info(...)` in [`formulas.py`](https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/formulas.py#L150). Same question: has anyone been using this to debug code recently ?
Thanks for your feedback.

Stop printing a humongous amount of log in CI

---

openfisca_france/tests/reforms/test_allocations_familliales_imposables.py
openfisca_france/tests/reforms/test_cesthra.py
openfisca_france/tests/reforms/test_landais_piketty_saez.py
openfisca_france/tests/reforms/test_parametric_reform.py
openfisca_france/tests/reforms/test_plf2015.py
openfisca_france/tests/reforms/test_trannoy_wasmer.py
openfisca_france/tests/test_allegement_fillon.py
openfisca_france/tests/test_cotsoc_fonc.py
openfisca_france/tests/test_cotsoc_sal_cap.py
openfisca_france/tests/test_decomposition_fiches_de_paie.py
openfisca_france/tests/test_decompositions.py
openfisca_france/tests/test_repairs.py
openfisca_france/tests/test_suggestions.py
openfisca_france/tests/test_tax_rates.py
openfisca_france/tests/utils.py

Please object if you do need the debug mode **by default** for one of these tests.
Nothings prevents a developper from locally activating the debug mode when debugging a failing tests, but this avalanche of logs in CI is a problem we have to address.

No debug=true in CI tests

---

CHANGELOG.md
run-travis-tests.sh
setup.py

For a PR build, `TRAVIS_PULL_REQUEST = #ofPR` (e.g. `479`), not `true`.

Fix versioning enforcement

---

CHANGELOG.md
openfisca_france/extensions/README.md
setup.py

The folder was accidentally removed in 4.0.0, instead of just being moved.

Add extension folder and README

---

CHANGELOG.md
openfisca_france/tests/test_yaml.py
setup.py

In some contexts (when using extensions, as far as I'm concerned), it is annoying to get `../../../test_yaml.py` to run a yaml test. This just provides a CLI shortcut to be able to do it from anywhere.
Usage: 
```sh
openfisca-run-test my_test.yaml
```
I'm open to suggestion about the command name.

Add console script to run yaml tests

---

CHANGELOG.md
Makefile
setup.py

Reason: `flake8 --first` is no more an option and made fail tests.

Use "python -m compileall" to check for syntax errors, not flake8

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ppa.py
openfisca_france/model/prestations/minima_sociaux/rsa.py
openfisca_france/model/revenus/remplacement/indemnites_journalieres_securite_sociale.py
openfisca_france/tests/formulas/ppa.yaml
openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_54817e07ed60b88866befc03.yaml
openfisca_france/tests/mes-aides.gouv.fr/test_mes_aides_55915f4c9e2a9d0330e7a20f.yaml
setup.py

* Consider some indemnités journalieres as revenus de remplacement in PPA (and RSA), according to the date of the arret de travail.
* Introduce
* `rsa_indemnites_journalieres_hors_activite`
* `rsa_indemnites_journalieres_activite`
* `date_arret_de_travail`

Les indemnités journalière ne sont un revenu d'activité que les 3 premiers mois.

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/rsa.py
openfisca_france/model/revenus/remplacement/indemnites_journalieres_securite_sociale.py
openfisca_france/tests/formulas/ppa.yaml
setup.py

This pull request follows [this discussion](https://github.com/openfisca/openfisca-france/pull/567#discussion_r83694666).
I tried to get rid of not-a-time date values and replace them by either [`date.min`](https://docs.python.org/2/library/datetime.html#datetime.date.min) or [`date.max`](https://docs.python.org/2/library/datetime.html#datetime.date.max) values.
The problem was that using not-a-time values broke the JSON transformation functions, in the context of the Web API but not only.
@fpagnoux Does this reimplementation seems correct to you?
See also [Core modification](https://github.com/openfisca/openfisca-core/pull/414): I enforced `DateCol.default` to be a `date`.

Reimplement not-a-time date values with date.min

---

CHANGELOG.md
openfisca_france/parameters/prestations.xml
openfisca_france/tests/formulas/rsa_celibataire.yaml
setup.py

* Re-apply RSA revalorisation from september
* Correct bonification rate for PPA
The merge of `baremes-ipp` seems to have brought some regressions in the parameters :
I think it was just a typo in the parameter from IPP.
[Source:](https://www.legifrance.gouv.fr/affichTexteArticle.do;jsessionid=A0D42BE09B11FC3AF57EF08286453FA5.tpdila13v_3?idArticle=JORFARTI000031665104&cidTexte=JORFTEXT000031665094&dateTexte=29990101&categorieLien=id)
>« Le montant maximal de la bonification s'élève à 12,782 % du montant forfaitaire mentionné au 1° de l'article L. 842-3 applicable à un foyer composé d'une seule personne.
But this brings the question of the conflict resolving process, which is today:
* IPP parameters are always prioritised over openfisca ones.
* The conflict is added as a tag, and is …

Fix some regressions in parameters introcduced by 6.0.0

---

CHANGELOG.md
openfisca_france/entities.py
openfisca_france/france_taxbenefitsystem.py
openfisca_france/model/prestations/education.py
openfisca_france/model/prestations/minima_sociaux/cmu.py
openfisca_france/tests/formulas/bourse.yaml
openfisca_france/tests/formulas/cmu.yaml
openfisca_france/tests/test_yaml.py
setup.py

Connected to https://github.com/openfisca/openfisca-core/pull/429
For variables `acs`, `bourse_college`, `bourse_lycee`, return a yearly amount instead of artificially divide it by 12 (breaking change) as:
- These concepts are legally defined for a year
- A significant part of the yaml runner complexity (`calculate_output`) was just here to handle these 3 cases in `mes-aides` tests.
- We anyway multiply back the amount by 12 in `mes-aides`.

Move yaml testing to core

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
setup.py

I run into trouble with runs calculating doing calculate at the year level.
@fpagnoux @michelbl : please check that you really intend to compute on the month period

Enforce period to month in aide_logmement_avant_degression

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
setup.py

Détecté suite à un retour utilisateur de mes-aides (mail du 2 janvier 2017 à 13:27)
Quand le demandeur se déclarait handicapé, il était compté à tort dans les personnes à charge, augmentant le montant de la prestation à tort.

Ne pas considérer un demandeur handicapé comme une personne à charge

---

CHANGELOG.md
openfisca_france/model/mesures.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/revenus/autres.py
setup.py

Détecté suite à un retour utilisateur de mes-aides.
Les pensions d'invalidité sont imposables, et doivent donc être entre autres prises en compte dans les aides au logement.

Ajout des pensions d'invalidité au revenu imposable

---

CHANGELOG.md
openfisca_france/parameters/cotsoc.xml
openfisca_france/tests/formulas/ags.yaml
setup.py

Le taux était dupliqué sous deux noms différents, chomfg et ags, dans les fichiers cotsoc.xml et prelevements-sociaux.xml...

Fix AGS duplication

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
openfisca_france/param/param.xml
openfisca_france/parameters/cotsoc.xml
openfisca_france/parameters/prelevements_sociaux.xml
openfisca_france/tests/formulas/maladie_mmid_employeur.yaml
openfisca_france/tests/formulas/reduction_generale-fillon.yaml
setup.py

Encore des modifications non prises en compte (Fillon découle de l'autre)...

2017 rates fix : Fillon & maladie employeur

---

travis-run-tests.sh

See https://github.com/openfisca/openfisca-web-api/pull/95
I think we should merge this PR without releasing, by exceptionally un-protecting the `master` branch.

Check versioning only if code has been updated

---

CHANGELOG.md
openfisca_france/model/base.py
setup.py

Apply https://github.com/openfisca/openfisca-core/pull/467 to `france`.

Simplify boilerplate

---

CHANGELOG.md
openfisca_france/reforms/plf2015.py
openfisca_france/reforms/plf2016.py
openfisca_france/tests/formulas/exoneration_cotisations_employeur_zfu.yaml
openfisca_france/tests/formulas/exoneration_cotisations_employeur_zrd.yaml
openfisca_france/tests/formulas/exoneration_cotisations_employeur_zrr.yaml
openfisca_france/tests/formulas/exoneration_is_creation_zrr.yaml
openfisca_france/tests/reforms/test_allocations_familliales_imposables.py
openfisca_france/tests/reforms/test_cesthra.py
openfisca_france/tests/reforms/test_landais_piketty_saez.py
openfisca_france/tests/reforms/test_parametric_reform.py
openfisca_france/tests/reforms/test_plf2015.py
openfisca_france/tests/reforms/test_plf2016.py
openfisca_france/tests/reforms/test_plf2016_ayrault_muet.py
openfisca_france/tests/reforms/test_plfr2014.py
openfisca_france/tests/reforms/test_trannoy_wasmer.py
openfisca_france/tests/test_allegement_fillon.py
setup.py

* Amélioration technique **non-rétrocompatible**
* Détails :
- Restreint les périodes acceptées par OpenFisca
- La liste des périodes autorisées est disponible dans la [documentation](https://doc.openfisca.fr/periodsinstants.html)
* Détails :
- Adapte `france` à  la version `9.0.0` de `core`.

Unify period formats

---

setup.py

#710 contient une erreur : le changelog mentionne la version `16.0.0` mais `setup.py` mentionne `15.1.1`.
Devons-nous dépublier https://pypi.python.org/pypi/OpenFisca-France `==15.1.1` ?

Corrige la release précédence

---

CHANGELOG.md
openfisca_france/model/prestations/education.py
openfisca_france/parameters/bourses_education.xml
openfisca_france/tests/formulas/bourse.yaml
setup.py

Fixes sgmap/openfisca-france#73
* Périodes concernées : à partir du 01/07/2016.
- Les changements prennent effet à partir de la rentrée scolaire 2016
* Zones impactées: `prestations/education`
* Détails:
- Met à jour le mode de calcul des bourses de collège et lycée, entrés en vigueur à la rentrée 2016.
- Introduit les variables `bourse_college_echelon` et `bourse_lycee_echelon`

Mise à jours des bourses de collège et lycée

---

CONTRIBUTING.md
openfisca_france/extensions/README.md
travis-run-tests.sh

Connected to https://github.com/openfisca/openfisca-core/issues/471
* Détails :
- Corrige des URLs vers la documentation.
- Supprime "/en" de l'URL, utilise HTTPS.
- - - -

Corrige des URLs vers la documentation

---

CHANGELOG.md
openfisca_france/param/param.xml
openfisca_france/parameters/bouclier_fiscal.xml
openfisca_france/parameters/bourses_education.xml
openfisca_france/parameters/cmu.xml
openfisca_france/parameters/cotsoc.xml
openfisca_france/parameters/fonc.xml
openfisca_france/parameters/fuzzyed.txt
openfisca_france/parameters/impot_revenu.xml
openfisca_france/parameters/prelevements_sociaux.xml
openfisca_france/parameters/prestations.xml
openfisca_france/parameters/taxation_capital.xml
openfisca_france/parameters/tns.xml
openfisca_france/reforms/allocations_familiales_imposables.py
openfisca_france/reforms/cesthra_invalidee.py
openfisca_france/reforms/landais_piketty_saez.py
openfisca_france/reforms/plf2015.py
openfisca_france/reforms/plf2016.py
openfisca_france/reforms/plf2016_ayrault_muet.py
openfisca_france/reforms/plfr2014.py
openfisca_france/reforms/trannoy_wasmer.py
setup.py
tests/fiches_de_paie/thesard_2011-07.yaml

Connected to https://github.com/openfisca/openfisca-core/issues/437

Remove fuzzy

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prestations/aides_logement.py
openfisca_france/model/prestations/minima_sociaux/cmu.py
setup.py

Depends on https://github.com/openfisca/openfisca-core/pull/499
* Zones impactées : `prestations/aides_logement`.
* Détails :
- Corrige le calcul de `aide_logement_neutralisation_rsa`.
- - - -
Ces changements _(effacez les lignes ne correspondant pas à votre cas)_ :

Fix aide_logement_neutralisation_rsa

---

.travis.yml
CHANGELOG.md
setup.py
tests/test_legislations.py

Connected to https://github.com/openfisca/openfisca-core/issues/474

Raise nicer errors when legislation is invalid

---

.gitignore
CHANGELOG.md
openfisca_france/extensions/README.md
openfisca_france/france_taxbenefitsystem.py
setup.py

Connected to #736 
Delete *openfisca-france/openfisca_france/extensions*
openfisca-france/.gitignore, line 19
````
openfisca_france/extensions
````
in openfisca-france/openfisca_france/france_taxbenefitsystem.py line 16, 17
````
EXTENSIONS_PATH = os.path.join(COUNTRY_DIR, 'extensions')
EXTENSIONS_DIRECTORIES = glob.glob(os.path.join(EXTENSIONS_PATH, ‘*/'))
````
openfisca-france/openfisca_france/france_taxbenefitsystem.py line 60
````
for extension_dir in EXTENSIONS_DIRECTORIES:
self.load_extension(extension_dir)
````
* Détails :
- Supprimer le dossier Extensions
- - - -
Ces changements _(effacez les lignes ne correspondant pas à votre cas)_ :
- Modifient des éléments non fonctionnels de ce dépôt (par exemple …

Removes Extensions file

---

CHANGELOG.md
openfisca_france/parameters/prestations.xml
setup.py
tests/formulas/rsa_2017.yaml

* Périodes concernées : à partir du 01/04/2016.
* Zones impactées : `taux_1_parent` et `taux_2_parents` dans `prestations.prestations_familiales.asf`.
* Détails :
- https://www.legifrance.gouv.fr/affichTexteArticle.do;jsessionid=1D9FEF8D527DD02D7A6666DAA945964D.tpdila23v_2?cidTexte=JORFTEXT000032345545&idArticle=LEGIARTI000032347447&dateTexte=20160403
Plus d'informations dans la circulaire
http://circulaire.legifrance.gouv.fr/pdf/2016/03/cir_40664.pdf
- - - -

Met à jour le taux de l'ASF sur la base du décret n° 2016-398 du 1er avril 2016

---

CHANGELOG.md
openfisca_france/parameters/prestations.xml
setup.py

* Périodes concernées : à partir du 01/04/2017.
- `prestations.minima_sociaux.rsa.montant_de_base_du_rsa`
- `prestations.prestations_familiales.af.bmaf`
* Détails :
- Mise à jour du montant du montant de base pour le RSA aux 1er avril, 1er septembre 2017.
- [Source](https://www.legifrance.gouv.fr/eli/decret/2017/5/4/2017-739/jo/article_1)
- Mise à jour de la BMAF au 1er avril 2017
- [Source](http://circulaire.legifrance.gouv.fr/pdf/2017/03/cir_41970.pdf)
- Correction mineure du taux de la BMAF au 1er avril 2015
- [Source](http://circulaire.legifrance.gouv.fr/pdf/2016/03/cir_40664.pdf) cf. valeur initiale (valeur erronée 406.21274, valeur corrigée 406.21)

Mise à jour du RSA au 1er avril et au 1er septembre 2017 et de la BMAF au 1er avril 2017

---

CONTRIBUTING.md

Mettre à jour la doc pour faire passer les tests avec CircleCI pour une version de Core pas encore publiée.

Mettre à jour doc pour contribuer avec CircleCI

---

CHANGELOG.md
setup.py

numpy 1.13 breaks openfisca, cf https://github.com/openfisca/openfisca-core/pull/526

Requiert numpy < 1.13

---

openfisca_france/scripts/parameters/baremes_ipp/README.md
setup.py

Simplifie l'installation.
PR sur une PR, pas de changelog OpenFisca.

Ajoute une dépendance optionnelle manquante à l'import des barèmes IPP

---

README.md

Connected to openfisca/openfisca-doc#77
* Zones impactées : `README.md`.
* Détails :
- Decrire les deux procédure d'installation d'Open-Fisca (pip et clone) et accompagner les utilisateurs dans le choix .
- Décrire les fonctionnalités de l'API publique pour pousser des utilisateurs casuals à s'en servir
- - - -
Ces changements  : 
Ceci est une version de travail en anglais.
Je propose de:
- la tester/valider en anglais, 
- la transférer en anglais sur Country Template 
- puis la traduire en Français pour une version finale sur openFisca France
J'ai besoin d'un premier retour avant de faire tester aux utilisateurs.

Give users an actionnable install procedure

---

CHANGELOG.md
openfisca_france/parameters/__root__.xml
openfisca_france/parameters/bouclier_fiscal.xml
openfisca_france/parameters/bourses_education.xml
openfisca_france/parameters/cmu.xml
openfisca_france/parameters/cotsoc.xml
openfisca_france/parameters/fonc.xml
openfisca_france/parameters/impot_revenu.xml
openfisca_france/parameters/prelevements_sociaux.xml
openfisca_france/parameters/prestations.xml
openfisca_france/parameters/taxation_capital.xml
openfisca_france/parameters/tns.xml
openfisca_france/scripts/parameters/baremes_ipp/README.md
openfisca_france/scripts/parameters/baremes_ipp/convert_ipp_xlsx_to_openfisca_xml.py
openfisca_france/scripts/parameters/baremes_ipp/merge_ipp_xml_files_with_openfisca_parameters.py
openfisca_france/scripts/parameters/format_parameters.py
setup.py

Conserver les paramètres modifiés à l'import des barèmes IPP

---

CHANGELOG.md
openfisca_france/reforms/de_net_a_brut.py
setup.py

* Détails
- Répare la réforme `de_net_a_brut`.

Fix de net a brut

---

CHANGELOG.md
setup.py
tests/test_metadata.py

Connected to openfisca/legislation-explorer#107
* Détails :
- Répare la déclaration de l'URL du dépôt, endomagée dans la version `18.6.0`

Fix repository URL

---

CHANGELOG.md
circle.yml
setup.py
tests/test_api.py

+ Détails :
- Mets à jour la version d'OpenFisca-Web-API requise pour qu'elle soit compatible avec la version d'OpenFisca-Core requise.
- Les deux versions référencées dans le `setup.py` étaient incompatibles, rendant impossible, dans certaines conditions, le démarrage de l'API.

Mets à jour l'API pour qu'elle soit compatible avec Core

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prelevements_obligatoires/isf.py
openfisca_france/model/prelevements_obligatoires/taxe_habitation.py
openfisca_france/reforms/landais_piketty_saez.py
setup.py

* Détails :
- Migre les formules situés dans les fichiers suivant vers la syntaxe introduite par OpenFisca-Core 4 :
- `prelevements_obligatoires/impot_revenu/credits_impot.py`
- `prelevements_obligatoires/isf.py`
- `prelevements_obligatoires/taxe_habitation.py`
- `reforms/landais_piketty_saez.py`

Migrations formules

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
setup.py

* Zones impactées : `openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py`.
* Détails :
- Mise à jour du `label` de `age` pour expliciter qu'il s'agit de l'âge en début de mois

Add implementation detail in age label

---

CHANGELOG.md
setup.py

* Détails :
- Déclare OpenFisca-France compatible avec OpenFisca-Core 17

Declare package compatible with Core 17

---

circle.yml
deploy-if-version-bump.sh

Connected to openfisca/openfisca-core#513
Cette PR est l'implémentation sur OpenFisca-France de [la procédure de vérification d'un changement de version avant de déployer ([Check version number change before deployment](https://github.com/openfisca/openfisca-core/pull/547))
**Changement mineur**
Quand il y a un nouveau commit sur la branche master, si le numéro de version n'a pas été modifié, le déploiement n'est pas déclenché.

Check version number change before deployment

---

circle.yml

My master is failing [on CircleCI](https://circleci.com/gh/guillett/openfisca-france/199) because deployment was trigger from my repository.
This should only trigger deployment from commits on master in `openfisca`repository as per indicated in [the documentation](https://circleci.com/docs/1.0/configuration/#deployment).

Prevent deployment from pushes on forks

---

CHANGELOG.md
openfisca_france/parameters/cotsoc.xml
openfisca_france/parameters/prelevements_sociaux.xml
setup.py
tests/formulas/ags.yaml

* Périodes concernées : à partir du 01/07/2017
* Zones impactées : `openfisca_france/parameters/cotsoc.xml`, `openfisca_france/parameters/prelevements_sociaux.xml`.
* Détails :
- Prise en compte de la baisse de la cotisation AGS au 1er juillet.
- - - -
Ces changements

Prise en compte de la baisse de la cotisation AGS au 1er juillet

---

check-version-bump.sh

Je rencontrais quelques problèmes en lançant `check-version-bump.sh` en local. @guillett, il me semble que tu m'avais dit que toi aussi. Est-ce qu'avec ce changement tu peux lancer le script en local sans difficulté ?

Make version check script more robust

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
setup.py
tests/formulas/aide_logement_non_calculable.yaml

* Zones impactées : `/prestations/aides_logement`.
* Détails :
- Suppresion de la notification de non-calculabilité des aides au logement pour les primo-accédants.

Publicize aide_logement as a calculable variable for primo-accédants

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
setup.py
tests/formulas/aides_logement_primo_accedant.yaml

* Zones impactées : `/prestations/aides_logement`.
* Détails :
- Corrige les aides au logement pour les primo-accédants ayant une importante base ressources.
- Le _loyer retenu_ était négatif si les ressources étaient importantes.

Corrige les ALs pour les primo accédants

---

CHANGELOG.md
setup.py

- Amélioration technique
- Détails :
- Déclare OpenFisca-France compatible avec OpenFisca-Core 18

Declare package compatible with core v18

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
openfisca_france/parameters/prestations/aides_logement/autres/abattement_forfaitaire.yaml
setup.py
tests/formulas/aides_logement.yaml

* Périodes concernées : à partir du 01/10/2017.
- `openfisca_france/model/prestations/aides_logement.py`.
- `openfisca_france/parameters/prestations/aides_logement/autres/abattement_forfaitaire.yaml`.
- `tests/formulas/aides_logement.yaml`.
* Détails :
- Ajout de l'abattement forfaitaire de 5€ dans le calcul des aides au logement à partir du 01/10/2017 .
- - - -

Add abatement of 5 euros to apl

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ppa.py
openfisca_france/model/prestations/minima_sociaux/rsa.py
setup.py
tests/formulas/ppa.yaml

- `prestations/minima_sociaux/ppa`
- `prestations/minima_sociaux/rsa`
* Détails :
- Prend en compte l'avantage en nature des primo-accédants dans le calcul des aides au logement.

Déclenchement du forfait logement pour les primo-accédants sans AL

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
setup.py
tests/formulas/aides_logement_primo_accedant.yaml

* Zones impactées : `prestations/aides_logement.py`
* Détails :
- Garantie que l'aide au logement pour un foyer primo-accédant est nulle si le prêt est déjà remboursé.

Fix AL when loan is fully reimbursed

---

CHANGELOG.md
setup.py

* Zones impactées : `setup.py`.
* Détails :
- Définit une version stricte pour l'import d' OpenFisca-Core
- - - -
Ces changements sécurisent les calculs existants.

Definit une version précise de OpenFisca-Core

---

CHANGELOG.md
openfisca_france/model/prestations/prestations_familiales/paje.py
setup.py
tests/test_basics.py

Fixes #880 
* Détails :
- Corrige l'erreur 500 qui apparaît dans les calculs de la PPA et du RSA depuis février 2018.
- Vérifie dans les tests que le revenu disponible peut être calculé jusuqu'à 2020 pour éviter qu'un problème similaire se reproduise.

Corrige l'erreur 500 en prod

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
openfisca_france/model/revenus/activite/salarie.py
setup.py
tests/allegement_fillon.yaml
tests/formulas/allegement_cotisation_allocations_familiales.yaml
tests/test_coefficient.py

* Correction d'un bug.
* Zones impactées : `prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements`.
* Détails :
- Corrige les erreurs de calculs constatés sur la réduction générale ("Fillon").
- (Fixes #844)
- - - -
Ces changements _(effacez les lignes ne correspondant pas à votre cas)_ :

Corrige les erreurs de calcul sur les allègements

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ppa.py
openfisca_france/model/prestations/minima_sociaux/rsa.py
openfisca_france/model/prestations/prestations_familiales/paje.py
setup.py
tests/formulas/paje.yaml

Fixes #880 
This PR is one solution to the issue bellow. #884 is another one
A partir d'avril 2017, la page_clca n'existe plus .
* Périodes concernées : A partir du 04/2017
* Zones impactées : `prestations_familiales/paje.py`.
* Détails :
- Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
- Cas dans lesquels une erreur était constatée.
- - - -

Remplace paje_clca par page_prepare dans le calcul de la paje.

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/revenus/capital/financier.py
openfisca_france/model/revenus/capital/plus_value.py
openfisca_france/parameters/impot_revenu/plus_values.yaml
openfisca_france/reforms/allocations_familiales_imposables.py
setup.py

Les modifications de cette PR sont comparées à la branche `ipp-update-charges-deductibles` (https://github.com/openfisca/openfisca-france/pull/907)
* Périodes concernées : à partir du 01/01/2008 (mais surtout à partir du changement législatif du 01/01/2013)
- `openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py`.
-  `openfisca_france/model/revenus/capital`
-  **`openfisca_france/reforms/allocations_familiales_imposables.py`**
* Détails :
- A partir de 2013, une partie des plus-values est taxé au barème alors qu'avant elles étaient taxées forfaitairement => correction de la formule de l'IR
- Les plus-values et revenus du capital (taxées forfaitairement ou au barème ou éxonérées) doivent entrer en compte dans le …

Ipp 2 :  Update taxation des revenus du capital dans IR

---

CHANGELOG.md
openfisca_france/conf/cache_blacklist.py
openfisca_france/model/mesures.py
openfisca_france/model/prestations/cheque_energie.py
openfisca_france/parameters/cheque_energie.yaml
setup.py
tests/formulas/cheque_energie/montant.yaml
tests/formulas/cheque_energie/unites_consommation.yaml

* Périodes concernées : à partir de 2017
* Zones impactées : `prestations/cheque_energie.py`
* Détails :
- Ajoute le calcul du montant du chèque énergie

Ajout du barème pour le chèque énergie

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
setup.py

Les modifications de cette PR sont comparées à la branche `ipp-update-tax-reductions_immobiliers` (https://github.com/openfisca/openfisca-france/pull/910)
* Périodes concernées : à partir du 01/01/2002
- `openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impots.py`.
- `openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py`
* Détails :
- Mise à jour des formules (2014-2016) de la réduction d'impôt 'invfor' 
- Correction d'une erreur dans la formule précédente : les reports de dépenses entrent dans le plafonnement de la réduction
- TODO : une partie de la réduction d'impôt pour investissement forestier devient un crédit d'impôt en 2014 (Brochure Pratique IR revenus 2014, …

Ipp 5 : Mise à jour de la réduction d'IR pour investissements forestiers

---

CHANGELOG.md
openfisca_france/model/mesures.py
setup.py
tests/formulas/unites_consommation.yaml

* Correction d'un bug
* Zones impactées : `revenus/mesures`
* Détails :
- Corrige la formule des `unites_consommation`
Ces changements corrigent ou améliorent un calcul déjà existant.
Fixes #953

Fix unites_consommations

---

CHANGELOG.md
openfisca_france/model/caracteristiques_socio_demographiques/logement.py
openfisca_france/model/prestations/cheque_energie.py
setup.py
tests/formulas/cheque_energie/eligibilite_logement.yaml

* Périodes concernées : À partir de 2018
* Détails :
- Suppression de l'éligibilité des foyers de Saint Martin au chèque énergie

Prevent incorrect eligibility to cheque energie in Saint Martin

---

CHANGELOG.md
setup.py

* Détails :
- Adapte France à Numpy v1.14

Upgrade numpy

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
openfisca_france/model/revenus/autres.py
setup.py

Les modifications de cette PR sont comparées à la branche `ipp-update-calcul-ip-net` (https://github.com/openfisca/openfisca-france/pull/918)
* Evolution du système socio-fiscal
* Périodes concernées : toutes 
- `  openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py`
- `  openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py`
-`  openfisca_france/model/revenus/autres.py`
* Détails :
- Les avantages fiscaux pour mécénat d'entreprises (depuis 2003) et pour acquisition de biens culturels (depuis 2002) sont définies comme des réductions d'impôt et non plus des crédits d'impôt
- Mise à jour de 'creimp' pour 2014-2016, et correction d'une petite erreur pour 2012
- - - -
- Ajoutent une fonctionnalité (par exemple ajout …

Ipp 13 : Update des crédits/réductions d'impôt restants

---

CHANGELOG.md
openfisca_france/model/prestations/cheque_energie.py
setup.py
tests/formulas/cheque_energie/montant.yaml
tests/formulas/cheque_energie/unites_consommation.yaml

* Zones impactées : `prestations/cheque_energie`
* Périodes concernées : À partir de 2017
* Détails :
- Corrige le calcul des unités de consommation pour le chèque énergie
- Corrige la période de validité des variables relatives au chèque énergie (valide à partir de 2018 et non 2017)
Superseeds #960.

Fix chèque energie implementation

---

CHANGELOG.md
README.md
notebooks/getting-started.ipynb
setup.py

Fixes #965
Fixes #966 
- `README.md`
- `notebooks/getting-started.ipynb`
* Détails :
- Corrige lien vers la documentation
- Corrige lien vers Swagger

Change link to documentation

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
setup.py

* Zones impactées : `.github/PULL_REQUEST_TEMPLATE.md`.
* Détails :
- Amélioration du template de ce message-ci.
- Ajout d'une liste de casses à cocher avec de bonnes conseils pour rédiger une belle pull request.
- - - -

Améliore template de pull request

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
openfisca_france/parameters/prestations/aides_logement/patrimoine/seuil_valorisation.yaml
setup.py
tests/formulas/patrimoine.yaml

* Périodes concernées : à partir du 01/10/2016.
* Zones impactées : `prestations/`
* Détails :
- Ajoute l'exclusion des cas particuliers dans le calcul des ressources prises en compte pour l'aide logement (AAH, AEEH, logement foyer)
- - - -

Ajoute l'exclusion des cas particuliers dans le calcul de la base ressource patrimoine

---

CHANGELOG.md
openfisca_france/parameters/prestations/minima_sociaux/ass/montant_plein.yaml
setup.py
tests/formulas/ass_04_2018.yaml

* Périodes concernées : à partir du 01/04/2018.
* Zones impactées : `prestations/minima_sociaux/ass`
* Détails :
- Met à jour le montant journalier à taux plein de l'ASS en date du 01/04/2018
- - - -

Revalorisation de l'ASS au 1er avril 2018

---

CHANGELOG.md
openfisca_france/parameters/prestations/minima_sociaux/ppa/montant_de_base.yaml
setup.py
tests/formulas/ppa_2018.yaml

* Périodes concernées : à partir du 01/04/2018.
* Zones impactées : `prestations\minima_sociaux\ppa`.
* Détails :
- Met à jour le montant forfaitaire de base du calcul de la PPA
- - - -

Revalorisation de la PPA au 1er avril 2018

---

CHANGELOG.md
openfisca_france/scripts/performance_tests/test_circleci_builds.py
performance_tests/test_perf_circleci.py
setup.py

⚠️ Attention : cette branch est pour le moment comparée à `test_perf`
Connected to #1002
Connected to #1010
* Détails :
- Ajoute un test de performance sur les tests de CircleCI
- Ce test peut être lancé avec la commande: 
`python performance_tests/test_perf_circleci.py 1717 1716`
- - - -
- - - -

Compare les peformances d'un commit à celles de la branch Master

---

CHANGELOG.md
openfisca_france/parameters/cotsoc/taxes_sal/taux_maj.yaml
openfisca_france/parameters/cotsoc/tehr.yaml
openfisca_france/parameters/impot_revenu/bareme.yaml
openfisca_france/parameters/impot_revenu/cehr_ipp.yaml
openfisca_france/parameters/prestations/al_param_accal/bareme_loyer_minimun_lo.yaml
openfisca_france/parameters/taxation_capital/isf/bareme.yaml
setup.py

* Détails :
- Ajoute l'unité manquante à certains barèmes libellés en euros ou francs.

Renseigne l'unité de certains barèmes libellés en monnaie nominale

---

CHANGELOG.md
openfisca_france/model/prestations/logement_social.py
setup.py
tests/formulas/logement_social_zone.yaml

* Correction d'un bug
* Périodes concernées : à partir du 01/01/2017.
- `prestations/logement_social`
* Détails :
- Corrige le calcul du logement social pour la Corse dont le code INSEE n'est pas un nombre

Fix logement social in Corse

---

openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py

Erreur de noms de variable issue de la PR #1018 qui empêche le code de l'impôt de tourner

Corrige une erreur bloquante dans le code de l'impôt

---

.circleci/is-version-number-acceptable.sh
CHANGELOG.md
setup.py

* Fix du script qui détermine le besoin d'un bump de version
* Zones impactées : `.circleci/is-version-number-acceptable.sh b/.circleci/is-version-number-acceptable.sh`.
* Détails :
- Le script faisait référence a un autre script qui a été renommé
- Changement du path du script pour qu'il soit bien exécuté
- - - -
- - - -

Fix du script qui détermine le besoin d'un bump de version

---

CHANGELOG.md
openfisca_france/decompositions/decomp.xml
openfisca_france/decompositions/decomp_contrib.xml
openfisca_france/decompositions/decompositions-multiples.xml
openfisca_france/model/mesures.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prelevements_obligatoires/isf.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
openfisca_france/model/prestations/aides_logement.py
openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
openfisca_france/model/prestations/minima_sociaux/rsa.py
openfisca_france/model/prestations/prestations_familiales/base_ressource.py
openfisca_france/reforms/allocations_familiales_imposables.py
openfisca_france/reforms/landais_piketty_saez.py
tests/formulas/revenu_disponible.yaml

Depends on #1025 
* Changement de nommage.
* Zones impactées : `prelevements_obligatoires/impot_revenu/ir`.
* Détails :
- Renomme les variables
- `rev_cap_lib` en `revenus_capitaux_prelevement_liberatoire`
- `rev_cap_bar` en `revenus_capitaux_prelevement_bareme`
- - - -

Amélioration de la lisibilité de variables de la fiscalité

---

CHANGELOG.md
openfisca_france/model/prestations/logement_social.py
setup.py

* Périodes concernées : à partir du 01/01/2017.
- `prestations/logement_social`
* Détails :
- Fait commencer la variable `logement_social_eligible` au 01/01/2017

Fait commencer la variable `logement_social_eligible` au 01/01/2017

---

.circleci/config.yml
CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
openfisca_france/model/prestations/anah/eligibilite_anah.py
openfisca_france/scenarios.py
setup.py

* Zones impactées : `.circleci/config.yaml`:
* Détails :
- Corrige les appels `circleci tests glob` pour que `**` soit _effectivement_ récursif

Fix glob expressions in CI config

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/parameters/impot_revenu/plafond_qf/abat_dom/taux_GuadMarReu.yaml
openfisca_france/parameters/impot_revenu/plafond_qf/abat_dom/taux_GuyMay.yaml
setup.py
tests/impot_revenu/abattement_dom.yaml

* Périodes concernées :à partir du 01/01/2013.
* Zones impactées : `model\prelevements_obligatoires\impot_revenu\ir`.
* Détails :
- Ajoute une variable "depcom_foyer" donnant le lieu de résidence fiscale du foyer.
- Utilise cette variable pour calculer l'abattement d'impôt spécial DOM 
- - - -

Ajoute l'abattement d'IR de 30 ou 40% pour les résidents des DOM

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/charges_deductibles.py
setup.py

Jusqu'ici, toutes les charges déductibles du revenu brut global (RBG) étaient réintégrées lors du calcul du revenu fiscal de référence (RFR). 
Or, la plupart des charges déductibles le sont bien à la fois du RBG et du RFR. Seules les charges d'épargne-retraite et de souscription au capital de SOFIPECHE ne sont pas déductibles du RFR.
Référence : [Article 1417 du Code Général des Impôts](https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000027517723&cidTexte=LEGITEXT000006069577) - 1° a) du IV
* Évolution du système socio-fiscal | Changement mineur.
* Zones impactées : `openfisca_france/model/prelevements_obligatoires/impot_revenu/charges_deductibles`.
- - - -
- - --

Correction du calcul du revenu fiscal de référence

---

CHANGELOG.md
openfisca_france/assets/apl/extract_subcommunes.py
openfisca_france/scripts/cnaf/exploitation_rsa.py
openfisca_france/scripts/cnaf/formulaires_caf.py
openfisca_france/scripts/cnaf/get_tree.py
openfisca_france/scripts/measure_performances.py
openfisca_france/scripts/parameters/baremes_ipp/xls_to_yaml_raw.py
openfisca_france/scripts/parameters/baremes_ipp/yaml_raw_to_yaml_clean.py
openfisca_france/scripts/parameters/reduce_parameters_paths.py
openfisca_france/scripts/rattachement.py
setup.py

This is a very straightforward change involving mainly adding parens to the print statements.
The non-trivial changes are in openfisca_france/scripts/parameters/baremes_ipp/xls_to_yaml_raw.py and openfisca_france/scripts/parameters/baremes_ipp/yaml_raw_to_yaml_clean.py:
changing `ur` to `r` in regexes.
I'm really baffled that those tests [would pass without failing in py3 on circleCI previously](https://circleci.com/gh/openfisca/openfisca-france/2338#config/containers/0) ...

Make the scripts compatible with py3

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
openfisca_france/parameters/prestations/reduction_loyer_solidarite/fraction_baisse_aide_logement.yaml
setup.py
tests/formulas/aides_logement_2018.yaml
tests/formulas/rls_apl.yaml

- `model\prestations\aides_logement`
- `parameters\prestations\reduction_loyer_solidarite`
* Détails :
- Intégration de la réduction du loyer de solidarité dans la formule de calcul de l'APL.
- - - -

Intégration de la réduction de loyer solidarité (RLS) dans la formule de calcul de l’aide personnalisée au logement (APL)

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
openfisca_france/model/prestations/minima_sociaux/rsa.py
openfisca_france/model/revenus/capital/financier.py
setup.py
tests/formulas/asi_aspa.yaml
tests/formulas/rsa/rsa_base_ressources.yaml

- `openfisca_france\model\prestations\minima_sociaux\rsa.py`
- `openfisca_france\model\prestations\minima_sociaux\asi_aspa.py`
- `openfisca_france\model\revenus\capital\financier.py`
* Détails :
- Supprime les doubles comptes de certains revenus du capital dans les bases ressources du RSA et de l'ASI-ASPA
- Exemple : les revenus de `f2ee` étaient injectés deux fois via `rsa_base_ressources_patrimoine_individu` et via les variables `revenus_capitaux_prelevement_bareme` et `revenus_capitaux_prelevement_liberatoire`

Corrige doubles comptes revenus capital dans rsa asi aspa

---

.circleci/config.yml
CHANGELOG.md
README.md
setup.py
tests/test_api.py

Connected to openfisca/openfisca-core#641
Depends on openfisca/openfisca-core#703
* Amélioration technique **non rétro-compatibles**.
* Détails :
- Aucun impact pour les **clients** de l'API.
- Rend optionnelle l'installation de la Web API
- `pip install OpenFisca-France` n'installera _plus_ l'API.
- ~`pip install OpenFisca-France[api]` permet d'inclure l'API.~
- `pip install openfisca-france && pip install openfisca-core[web-api]` permet d'inclure l'API.
- Sert l'API Web sur le port 5000 par défault (à la place de 6000, considéré non-sûr)
- Renomme le groupe des dépendances optionnelles de développement:
- `pip install --editable .[dev]` permet de les installer (à la place de of `pip install --editable .[test]`).

Rend l'installation de la Web API optionnelle

---

.circleci/config.yml

Fixes #1054 
This PR is based on #1053 and shouldn't be merged before it.
It doesn't run the `flake8` check as it would need many fixes to many files. I've filed #1057 for that matter.

Add the missing checks to the CI

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
openfisca_france/parameters/cotsoc/sal/commun/assedic.yaml
setup.py

* Périodes concernées : à partir du 01-10-2018
* Zones impactées : prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive
* Détails :
- Annule la cotisation chômage à partir du 01-10-2018
- - - -
- - - -

Corrige cotisation chomage apres 2018-10-01

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/contributions/csg/retraite/deductible/taux_plein.yaml
setup.py

* Périodes concernées : à partir du 01/01/2018.
* Zones impactées : `prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement`.
* Détails :
- Mise à jour du taux de CSG déductible sur les retraites
- - - -
- - - -

Update csg déductible retraite for 2018

---

CHANGELOG.md
setup.py
tests/formulas/aspa.yaml

* Périodes concernées : à partir du 01/04/2018.
* Zones impactées : `tests/formulas/aspa`.
* Détails :
- Ajoute des tests pour la revalorisation de l'ASPA (voir PR #1066)
- - - -

Tests de la revalorisation de l'ASPA de 2018-04

---

.circleci/config.yml

Same deal as openfisca/openfisca-core#722
This adds a separate CircleCI job common to Python2 and Python3 for checking whether the version number has been bumped in `setup.py` and Changelog was updated.
Rationale:
- we get faster and more relevant feedback on our work while a PR is in progress
- we get highly relevant feedback when Python2 and Python3 tests behave differently
- the version check provides information of a different nature than functional tests
(It might also make sense to run the linting checks separately, as they rely purely on static properties of the code, just as the version and changelog checks.)

Check version and changelog separately

---

CHANGELOG.md
setup.py

Fixes #1113
Normalement, le fichier `__init__.py` permet de rendre découvrables des
modules Python.
Dans le cas des packages, ce qui n'est pas toujours les cas avec des
applications, il n'y a pas des modules Python à la racine faisant partie
du package.
La présence de ce fichier est donc très probablement due à une faute de frappe involontaire.
---
* Zones impactées : `__init__.py`.
* Détails :
- Efface __init.py__ de la racine.
- - - -
- - - -
> Et surtout, n'hésitez pas à demander de l'aide ! :)
👍

Efface __init.py__ de la racine

---

.circleci/config.yml

* Détails :
- Dans la même idée que #1112, déroule séparément les tests statiques
- Ajoute flake8 à la CI (#372) en mode [incrémental](https://consideratecode.com/2016/10/15/check-code-changes-with-flake8-before-committing/): seulement les *lignes* modifiées!
---
Édité par @maukoquiroga : le keyword « fixes » va automatiquement fermer une issue, donc je l'ai enlevé.

Déroule séparément les tests statiques (linting)

---

CHANGELOG.md
openfisca_france/model/prestations/prestations_familiales/asf.py
setup.py
tests/formulas/asf.yaml
tests/mes-aides.gouv.fr/test_mes_aides_559161a648433cfe2f4370f0.yaml

* Périodes concernées : à partir du 01/04/2018.
* Zones impactées : `openfisca_france/parameters/prestations/prestations_familiales/af/bmaf.yaml`.
* Détails :
- Correction du calcul de l'ASF, en cas de pension alimentaire.
- Prise en compte de la revalorisation 2018.
- Nécessite #994, lié à betagouv/mes-aides-ui#602
- - - -

Corrige le calcul de l'ASF

---

.circleci/config.yml
.circleci/lint-changed-python-files.sh
.circleci/lint-changed-yaml-tests.sh
CHANGELOG.md
setup.cfg
setup.py

Child of #372
Relates to #1039 
* Zones impactées : `.circleci`.
* Détails :
- Lint des test YAML en incrémental (`yamllint`).
- Lint des fichiers Python en incrémental (`flake8`).
- - - -
- Modifient des éléments non fonctionnels de ce dépôt (`.circleci`).
- - - -

Linte les fichiers YAML/Python en incrémental

---

CHANGELOG.md
setup.py

* Périodes concernées : n/a
* Zones impactées : n/a
* Détails :
- Supprime le fichier `openfisca-run-test` à la racine

Suppression du fichier 'openfisca-run-test'

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
setup.cfg
setup.py
tests/formulas/aides_logement_accedant_eligibilite.yaml

- `model\prestations\aides_logement`.
* Détails :
- Suppression des aides au logement dans le cadre de l'accession à la propriété, sauf exception.
- Ajout des variables:
- `TypeEtatLogement`
- `etat_logement`
- `aide_logement_date_pret_conventionne`
- `aides_logement_primo_accedant_eligibilite`

Application d'un barème spécifique à certains publics "accession" - Aides au logement (FAM_Reforme_Accession)

---

.circleci/config.yml
CHANGELOG.md
Makefile
openfisca_france/model/revenus/activite/non_salarie.py
openfisca_france/model/revenus/activite/salarie.py
openfisca_france/model/revenus/autres.py
openfisca_france/model/revenus/capital/financier.py
openfisca_france/model/revenus/capital/plus_value.py
openfisca_france/model/revenus/remplacement/chomage.py
openfisca_france/model/revenus/remplacement/indemnites_journalieres_securite_sociale.py
openfisca_france/model/revenus/remplacement/rente_accident_travail.py
setup.cfg
setup.py

Relates to #1057
Relates to #1060
Child of #372 
---
* Zones impactées : `openfisca_france/model/revenus/**/*`.
* Détails :
- - - -

Lint openfisca_france/model/revenus/**/*

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
openfisca_france/model/prestations/autonomie.py
openfisca_france/model/prestations/education.py
openfisca_france/model/prestations/minima_sociaux/aah.py
openfisca_france/model/prestations/minima_sociaux/aefa.py
openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
openfisca_france/model/prestations/minima_sociaux/ppa.py
openfisca_france/model/prestations/prestations_familiales/af.py
setup.py

Child of #372 
---
* Zones impactées : `openfisca_france/model/prestations/**/*`.
* Détails :
- Règle W504 : saut de ligne avant opérateur binaire
- - - -

Linte model/prestations (W504)

---

CHANGELOG.md
openfisca_france/model/revenus/activite/non_salarie.py
openfisca_france/model/revenus/activite/salarie.py
setup.py

Child of #372 
---
* Zones impactées : `openfisca_france/model/revenus/**/*`.
* Détails :
- Règle W504 : saut de ligne avant opérateur binaire
- - - -

Linte model/revenus (W504)

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
openfisca_france/parameters/cotsoc/pat/commun/construction_node/seuil.yaml
setup.py

* Périodes concernées : à partir du 01/01/1943
- `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py`
- `openfisca_france/parameters/cotsoc/pat/commun/construction_node/seuil.yaml`
* Détails :
- Extrait vers un paramètre le nombre de salariés au-delà duquel le prélèvement s'applique.
Fixes #432
- - - -
- - - -

Extrait en paramètre un seuil en nombre de salariés

---

CHANGELOG.md
openfisca_france/model/caracteristiques_socio_demographiques/logement.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prestations/anah/eligibilite_anah.py
openfisca_france/model/prestations/logement_social.py
setup.py
tests/test_entities.py

Connected to openfisca/openfisca-core#737
* Correction d'un crash. 
* `caracteristiques_socio_demographiques/logement.py`
* `prelevements_obligatoires/impot_revenu/ir.py`
* `prestations/anah/eligibilite_anah.py`
* `prestations/logement_social.py`
* Détails :
- Traite les codes postaux comme chaînes et non tableaux d'octets
- Corrige une différence d'encoding entre Python 2 et Python 3 pour les variables de type `str`
- - - -
- - - -

Traite les codes postaux comme chaînes et non tableaux d'octets

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/aah.py
setup.py

- `model/prestations/minima_sociaux/aah`
* Détails :
- Ajoute la variable plafond de ressources pour l'AAH

Extrait une variable explicite pour le plafond de l'AAH

---

CHANGELOG.md
openfisca_france/model/caracteristiques_socio_demographiques/logement.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prestations/anah/eligibilite_anah.py
openfisca_france/model/prestations/logement_social.py
setup.py
tests/test_entities.py

Ces changements étaient basés sur une version de Core depuis dépubliée (voir https://github.com/openfisca/openfisca-core/pull/741)

Revert le casting des variables string en unicode

---

CHANGELOG.md
setup.py
tests/formulas/irpp.yaml

* Périodes concernées : 2013
* Zones impactées : `tests/formulas/irpp.yaml`.
* Détails :
- Ajoute des tests couvrant le calcul de la décote de l'IR en 2013
Fixes #398 
- - - -
- - - -

Met à jour les tests sur la décote 2013

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/aefa.py
openfisca_france/parameters/prestations/minima_sociaux/aefa/forf2008.yaml
openfisca_france/parameters/prestations/minima_sociaux/aefa/mon_seul.yaml
openfisca_france/parameters/prestations/minima_sociaux/aefa/prime_exceptionnelle.yaml
setup.py

* Périodes concernées : à partir du 01/01/2002.
* Zones impactées : `openfisca_france/model/prestations/minima_sociaux/aefa.py`.
* Détails :
- Factorise le code dupliqué (tripliqué d'ailleurs) du calcul de l'aide exceptionnelle de fin d'année.
- Corrige le montant de base de l'AEFA
- Prolonge l'AEFA au-delà de 2015 car elle a été reconduite
- N'applique la majoration familiale que pour les bénéficiaires du RSA
Fixes #569
- - - -
- - - -

Factorise la duplication dans le calcul de la 'Prime de Noël'

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/cmu.py
openfisca_france/model/prestations/minima_sociaux/rsa.py
openfisca_france/model/revenus/autres.py
setup.py

- `openfisca_france/model/prestations/minima_sociaux/[cmu,rsa].py`.
- `openfisca_france/model/revenus/autres.py`
* Détails :
- Supprime la variable allocation_aide_retour_emploi, inutilisée
- - - -
- - - -

Supprime la variable allocation_aide_retour_emploi

---

CHANGELOG.md
setup.py
tests/formulas/asi.yaml

* Zones impactées : `tests/formulas/asi.yaml`
* Détails :
- Ajout de tests pour l'ASI afin de vérifier que la formule prend bien en compte la dégressivité au delà d'un seuil.
- - - -
- - - -
Fix #1073

Ajoute un nouveau test pour l'ASI

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/rsa.py
setup.py
tests/formulas/rsa.yaml

* Amélioration d'un calcul existant
* Zones impactées : `prestations/minima_sociaux/rsa`.
* Détails :
- Corrige un double compte de revenus du capital

Corrige un double compte des revenus du capital dans le RSA

---

CHANGELOG.md
setup.py

La PR #1190 introduit un changement majeur. Cette PR corrige le numéro de version pour passer à la version 29.0.0
* Évolution du système socio-fiscal. | Amélioration technique.
* Zones impactées : setup.py, CHANGELOG.md

Corrige le changement de version suite à PR #1190

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ass.py
openfisca_france/parameters/prestations/minima_sociaux/ass/age_max.yaml
setup.py
tests/formulas/ass_eligibilite.yaml

* Zones impactées : `prestations_sociales/ass`.
* Détails :
- Ajoute une condition d'âge sur l'ASS.
- Ajoute un test.
Fixes #791 
- - - -
- - - -

Condition d'âge pour l'ASS

---

CHANGELOG.md
openfisca_france/parameters/prestations/minima_sociaux/ppa/montant_de_base.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/pente.yaml
setup.py

Le [Décret n° 2018-836 du 3 octobre 2018](https://www.legifrance.gouv.fr/eli/decret/2018/10/3/SSAA1822062D/jo/texte) a introduit une revalorisation exceptionnelle de la prime d'activité, mais également une hausse de sa dégressivité (i.e. une baisse du paramètre `pente` de la prime d'activité).
* Périodes concernées : à partir du 01/10/2018.
* Zones impactées : `parameters/prestations/minima_sociaux/ppa`.
* Détails :
- Intègre la revalorisation exceptionnelle de la prime d'activité (+20 euros en octobre 2018)
- Intègre la hausse du taux de dégressivité de la prime d'activité (octobre 2018)
- - - -

Intégre les modifications de la prime d'activité (Octobre 2018)

---

CHANGELOG.md
openfisca_france/parameters/prestations/minima_sociaux/aah/montant.yaml
setup.py

Linked to #1188
* Périodes concernées : à partir du 01/11/2018.
* Zones impactées : `parameters/prestations/minima_sociaux/aah/montant`.
* Détails :
- Prends en compte les revalorisations à venir de l'AAH
- - - -

Met à jour le montant de l'AAH pour novembre

---

.circleci/config.yml
.circleci/has-functional-changes.sh
.circleci/publish-python-package.sh
CHANGELOG.md
MANIFEST.in
Makefile
openfisca_france/assets/apl/extract_subcommunes.py
openfisca_france/scripts/parameters/baremes_ipp/merge_ipp_xml_files_with_openfisca_parameters.py
openfisca_france/scripts/parameters/explore_parameters_unit.py
openfisca_france/scripts/parameters/reduce_parameters_paths.py
openfisca_france/scripts/performance/measure_calculations_performance.py
openfisca_france/scripts/performance/measure_tests_performance.py
setup.py
tests/test_basics.py
tests/test_decomposition_fiches_de_paie.py

Child of #1177 
* Détails :
- Lors de l'ajout d'un fichier statique requis pour le fonctionnement de la librairie, nous devons le rendre découvrable par `wheel`
- Pour éviter des soucis involontaires de packaging, on _build_ désormais la librairie, et on exécute les tests contre la version qui sera mise à disposition des usagers
- - - -
- - - -

Teste contre la version build

---

.circleci/config.yml
CHANGELOG.md
Makefile
README.md
setup.cfg
setup.py
tests/reforms/test_plf2015.py
tests/reforms/test_plf2016.py
tests/test_coefficient.py
tests/test_metadata.py
tests/test_repairs.py
tests/test_suggestions.py
tests/utils.py

Depends on openfisca/openfisca-core#746
* Détails :
- Permet d'utiliser `pytest` pour faire tourner les tests.
- La librairie actuelle, `nose`, n'est plus en développement actif.
- - - -
- - - -

Utilise PyTest

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
openfisca_france/model/revenus/activite/non_salarie.py
setup.py
tests/calculateur_impots/yaml/reduc_locmeu.yaml
tests/calculateur_impots/yaml/reduc_locmeu_plafonnee.yaml
tests/calculateur_impots/yaml/reduc_patnat.yaml
tests/calculateur_impots/yaml/reduc_scelli_dom_poly_et_reports.yaml
tests/calculateur_impots/yaml/reduc_scelli_metro_bbc_et_reports1.yaml
tests/calculateur_impots/yaml/reduc_scelli_metro_non_bbc.yaml
tests/calculateur_impots/yaml/regime_benef_reel_BIC_pro_sans_cga.yaml
tests/calculateur_impots/yaml/regime_benef_reel_agricole_sans_cga.yaml

* Zones impactées : `impot_revenu`.
* Détails :
- Nouveaux cas de tests faisant apparaitre des divergences entre OpenFisca et le calculateur DGFIP.
- Correctifs pour résoudre ces divergences.
- - - -
- - - -

Fiabilisation des calculs d'impôts

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
setup.py

* Zones impactées : `asi_aspa`.
* Détails :
- Corrige un commentaire avec une référence législative
Fixes #876 
- - - -
- - - -

Précise pourquoi on exclut l'AAH de la base ressources ASPA

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ppa.py
openfisca_france/model/prestations/minima_sociaux/rsa.py
setup.py

Connected to #629 
* Zones impactées : `openfisca_france/model/prestations/minima_sociaux/[rsa,ppa].py`.
* Détails :
- Déprécie explicitement l'usage de extra_params dans France
- - - -
- Modifient des éléments non fonctionnels du modèle (commentaires)

Déprécier extra_params

---

CHANGELOG.md
openfisca_france/parameters/cotsoc/pat/commun/assedic.yaml
setup.py

* Périodes concernées : à partir du 01/10/2017
* Zones impactées : `parameters/cotsoc/pat/commun/assedic`.
* Détails :
- Intègre la CET de 2017
Fixes #795 
- - - -
- - - -

Intègre la cotisation exceptionnelle temporaire de 2017

---

CHANGELOG.md
openfisca_france/model/prestations/cheque_energie.py
setup.py
tests/formulas/cheque_energie/montant.yaml

* Zones impactées : `model/prestations/cheque_energie`.
* Détails :
- Remplace l'utilisation de `a < b < x` par `(a < b) * (b < c)` car la première notion ne fonctionne pas avec des vecteurs `numpy`.
- - - -

Fix multidimension cheque_energie

---

CHANGELOG.md
openfisca_france/model/mesures.py
setup.py
tests/formulas/aides_logement_2018.yaml

Problème : il y' a un double compte de la CRDS logement dans la variable `aides_logement` : 
`crds_logement` => `aide_logement_montant` => `apl` => `aides_logement`
`crds_logement` => `aides_logement`
Cette PR corrige le calcul de la variable à `aides_logement` pour éviter ce double compte.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
- Corrige le double compte de la CRDS logement dans `aides_logement`
- - - -

Corrige le calcul des aides au logement

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
openfisca_france/model/revenus/capital/financier.py
setup.py

- `revenus/capital/financier.py`
* Détails :
- Enlève la variable `avoirs_credits_fiscaux` des variables de mesure de revenus du capital
- Renomme `avoirs_credits_fiscaux` en `credits_impot_sur_valeurs_etrangeres`
- Déplace l'utilisation de cette variable directement dans `assiette_csg_revenus_capital`

Améliore la gestion des crédits d'impôt sur valeurs étrangères

---

.circleci/has-functional-changes.sh
CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
setup.py

Fixes #1204 
* Périodes concernées : à partir de 2016.
* Zones impactées : `ir.py`.
* Détails :
- Cette réduction instaurée en 2016 vise à adoucir un effet de seuil d'assujettissement à l'impôt pour les foyers fiscaux les plus modestes, elle est plus à considérer comme une "décote bis" qu'une réduction fiscale.
- Simplification de la formule ip_net qui n'a pas besoin d'être dupliquée, la formule de la réduction étant datée
- - - -
- - - -

Clarifie le statut de "reduction_ss_condition_revenus"

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_totaux.py
openfisca_france/model/revenus/activite/salarie.py
setup.py

* Changement mineurs.
- `prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement`
- `prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_totaux`
- `revenus/activite/salarie`
* Détails :
- Corrige les catégories d'employés de la fonction publique disposant d'un indice majorée
- Corrige les catégories d'employés de la fonction publique disposant d'une prime
- - - -
Ces changements corrigent ou améliorent un calcul déjà existant.
- - - -
- ~[ ] Documentez votre contribution avec des références …

Fix fonction publique

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
setup.py
tests/formulas/aides_logement_2018.yaml
tests/formulas/aides_logement_foyer.yaml
tests/formulas/rls_apl.yaml

* Zones impactées : `model/prestations/aides_logement`.
* Détails :
- Remplace la notion locataire_hlm par la notion de logement_conventionne dans les formules où la variable locataire_hlm est utilisée à la place de la variable logement_conventionné.

Privilégie la notion de logement conventionné pour la détermination du secteur APL

---

CHANGELOG.md
openfisca_france/model/mesures.py
openfisca_france/model/prestations/aides_logement.py
openfisca_france/model/prestations/reduction_loyer_solidarite.py
setup.py
tests/formulas/aides_logement_2018.yaml
tests/formulas/revenu_disponible.yaml
tests/formulas/rls.yaml

Suite à la mise en place de la réduction de loyer de solidarité (RLS), les familles qui bénéficient de cette réduction voient leur montant d'aide au logement diminuer de 98% de leur RLS. 
- La RLS et la baisse d'aides au logment associée sont simulés dans OpenFisca.
- Mais la RLS n'est pas prise en compte dans le calcul du revenu disponible. Cette réforme fait donc baisser artificiellement le revenu disponible des ménages locataires (via la baisse des aides au logement) dans les simulations OpenFisca alors que dans la réalité elle est quasi neutre pour les ménages locataires.
1) Pour bien prendre en compte les effets de la mise en place de la RLS, on propose de la rajouter dans la variable `prestations_sociales`.
2) On propose également de préciser l'éligibilité à la RLS au sein de la …

Prise en compte de la RLS dans le calcul des prestations sociales

---

CHANGELOG.md
openfisca_france/parameters/prestations/minima_sociaux/ppa/montant_de_base.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/pente.yaml
setup.py

* Correction mineure.
* Périodes concernées : à partir du 01/08/2018
- `parameters/prestations/minima_sociaux/ppa/montant_de_base`
* Détails :
- Corrige la date d'effet de paramètres de la prime d'activité
La date de mise à jour des paramètres dans [#1192](https://github.com/openfisca/openfisca-france/pull/1192/files) était 01/10/2018 mais le décret indique 01/08/2018 (enfin il indique août 2018).

Corrige la date d'application des nouveaux barèmes de la PPA

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ppa.py
openfisca_france/parameters/prestations/minima_sociaux/ppa/age_min.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/bonification/seuil_bonification.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/bonification/seuil_max_bonification.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/bonification/taux_bonification_max.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/majoration_isolement_enf_charge.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/majoration_isolement_femme_enceinte.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/montant_de_base.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/pente.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/seuil_aah_activite.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/seuil_non_versement.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/taux_deuxieme_personne.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/taux_forfait_logement/foyer_1_personne.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/taux_forfait_logement/foyer_2_personnes.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/taux_forfait_logement/foyer_3_personnes.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/taux_personne_supp.yaml
openfisca_france/parameters/prestations/minima_sociaux/ppa/taux_troisieme_personne.yaml
setup.py
tests/formulas/ppa.yaml
tests/formulas/ppa_2018.yaml
tests/formulas/ppa_index_mois_trimestre_reference.yaml
tests/formulas/ppa_offset.yaml

* Périodes concernées : toutes pour la PPA c'est à dire à partir du 01/10/2015.
* Zones impactées : `prestations/minima_sociaux/ppa`.
* Détails :
- Supprime la distinction en mois de demande et mois de ressource dans les calculs de la PPA.
- - -

Amélioration des calculs de prime d'activité

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prestations/minima_sociaux/aah.py
setup.py

- `prestations/minima_sociaux/aah.py`
* Détails :
- Supprime les variables `revenu_activite`, `revenu_activite_salariee` et `revenu_activite_non_salariee` qui incorporaient juste `salaire_imposable` et `rpns_individu` et n'étaient utilisées que pour l'AAH.

Supprime trois variables de revenu d'activité

---

CHANGELOG.md
setup.py

* Changement majeur
- `prestations/minima_sociaux/aah.py`
* Détails :
- Corrige le changement de version de la PR [#1250](https://github.com/openfisca/openfisca-france/pull/1250) qui est un changement majeur car suppression de variables.

Corrige la version

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ass.py
setup.py

* Zones impactées : `prestations/minima_sociaux/ass`.
* Détails :
- Ajoute des références pour l'allocation de solidarité spécifique
- - - -
Je laisse l'équipe Core modifier `setup.py` à partir ces éléments ici et en fonction des intégrations qui précèdent celle-ci.

Ajoute des références législatives pour l'ASS

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
setup.py

* Zones impactées : `prestations_sociales/aides_logement.py`.
* Détails :
- Affine une condition concernant le loyer plafond dans le calcul de L .
- - - -
- - - -

Corrige un calcul des aides au logement

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ppa.py
setup.py
tests/formulas/ppa.yaml
tests/formulas/ppa/ppa_ressources_hors_activite_individu.yaml

Fixes #1242.
* Amélioration d'un calcul existant
* Périodes concernées : toutes pour la prime d'activité, ie. à partir de janvier 2016.
* Zones impactées : `prestations/minima_sociaux/ppa`.
* Détails :
- Prise en compte des revenus du capital dans le calcul de la prime d'activité
- - - -
- - - -
Je laisse l'équipe Core modifier `setup.py` à partir ces éléments ici et en fonction des intégrations qui précèdent celle-ci.

 Prends en compte les ressources du capital dans le calcul de la prime d'activité

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/rsa.py
setup.py
tests/formulas/rsa/rsa_jeune.yaml

*  Correction d'un crash.
* Zones impactées : `prestations/minima_sociaux/rsa`.
* Détails :
- Gestion de la variable `rsa_eligibilite` pour la période du RMI qui a été endomagée lors de l'introduction du paramètre `rsa_jeune`.
- Problème de type constaté lors de la mutiplication d'un scalaire égal à 1 avec des vecteurs numpy booléens révélé lors d'un usage au CASD (potentiellement dépendant du système d'exploiattion etc)
- - - -
- - - -
- ~[ ] …

Eligibilite rsa jeune

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ppa.py
setup.py
tests/formulas/ppa_index_mois_trimestre_reference.yaml

* Zones impactées : `model/prestations/minima_sociaux/ppa.py`.
* Détails :
- Répare la variable de la prime d'activité versée

 Répare la variable PPA versée 

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/aah.py
openfisca_france/parameters/prestations/minima_sociaux/aah/majoration_du_plafond_pour_un_couple.yaml
openfisca_france/parameters/prestations/minima_sociaux/aah/montant.yaml
setup.py
tests/formulas/aah_couple.yaml

* Périodes concernées : à partir du 01/11/2018.
- `model/prestations/minima_sociaux/aah`.
- `parameters/prestations/minima_sociaux/aah/majoration_du_plafond_pour_un_couple`.
* Détails :
- Diminution du plafond de ressources à 89% (au lieu de 100%) pour les bénéficiaires de l'allocation adulte handicapé en couple.
- Utilisation du paramètre "majoration_du_plafond_pour_un_couple" qui existe déjà dans openfisca, dans la formule de calcul du plafond des ressources.

Modification du calcul du plafond de ressources pour les bénéficiaires de l’allocation adulte handicapé en couple

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ppa.py
setup.py

* Détails :
- Ajoute des références législatives à une variable de la prime d'activité

Ajoute des références législatives à la PPA

---

CHANGELOG.md
openfisca_france/model/prestations/prestations_familiales/af.py
openfisca_france/parameters/prestations/prestations_familiales/af/modulation/majoration_plafond_par_enfant_supplementaire.yaml
openfisca_france/parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_1.yaml
openfisca_france/parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_1_base.yaml
openfisca_france/parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_2.yaml
openfisca_france/parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_2_base.yaml
setup.py

* Évolution du système socio-fiscal.mineur.
* Périodes concernées : à partir du 01/01/2019.
* Zones impactées : `prestations/prestations_familiales/af/modulation`.
* Détails :
- Revalorisation des plafonds de ressources et de la majoration du plafond par enfant dans le calcul de l'Allocation Familiale.

Revalorisation des allocations familiales au 1er janvier 2019

---

CHANGELOG.md
openfisca_france/model/mesures.py
openfisca_france/model/prestations/minima_sociaux/rsa.py
setup.py

- `prestations/minima_sociaux/rsa.py`
- `mesures.py`
* Détails :
- Actualise la formule de la variable `crds_mini`
- Introduit `crds_mini` et `crds_pfam` dans la chaîne de calcul du revenu disponible
Fixes #1108

Corrige la CRDS sur les prestations

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
setup.py
tests/impot_revenu/cotsyn.yaml

Contexte : *Les cotisations syndicales ouvraient droit à une réduction d'impôt jusqu'à l'imposition des revenus 2011 puis à un crédit d'impôt à partir de l'imposition des revenus 2012. Le mode de calcul reste le même. Sources : [Article 119 quarter C du CGI](https://www.legifrance.gouv.fr/affichCode.do?idSectionTA=LEGISCTA000006191827&cidTexte=LEGITEXT000006069577)*
Dans la version actuelle d'OpenFisca, le calcul des crédits d'impôt utilise la variable `cotsyn` (réduction d'impôt pour cotisations syndicales) dont l'attribut `end` était fixé au 31/12/2011. Par conséquent, le calcul des crédits d'impôt est faux : il ne prend pas en compte le crédit d'impôt pour cotisations syndicales.
Je propose de créer une nouvelle variable `cotsyn2` spécifique à ce crédit d'impôt et utilisée dans le …

Réactive le crédit d'impôt pour cotisations syndicales

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py
setup.py
tests/formulas/revenu_disponible.yaml

* Périodes concernées : 2018
- `prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique`
* Détails: Corrige l'application d'un abattement sur les produits d'assurance-vie
Fixes #1084

Corrige l'application d'un abattement sur produits d'assurance-vie

---

CHANGELOG.md
openfisca_france/parameters/prestations/minima_sociaux/aspa/montant_annuel_couple.yaml
openfisca_france/parameters/prestations/minima_sociaux/aspa/montant_annuel_seul.yaml
openfisca_france/parameters/prestations/minima_sociaux/aspa/plafond_ressources_couple.yaml
openfisca_france/parameters/prestations/minima_sociaux/aspa/plafond_ressources_seul.yaml
setup.py

* Revalorisation périodique
* Périodes concernées : à partir du 01/01/2019.
* Zones impactées : `parameters/prestations/minima_sociaux/aspa`.
* Détails :
- Revalorise l'allocation de solidarité aux personnes âgées au 1er janvier 2019 et au 1er janvier 2020.

Revalorisation de l'allocation de solidarité aux personnes âgées au 1er janvier 2019

---

CHANGELOG.md
openfisca_france/model/mesures.py
setup.py

Le calcul des revenus bruts dans le module `mesures.py` se fait en partant des revenus nets et en y ajoutant l'ensemble des prélèvements retranchés des revenus bruts. La contribution additionnelle de solidarité et d'autonomie (CASA) fait partie des prélèvements appliqués aux revenus bruts de remplacement (retraite). Elle doit donc être intégrée à ce calcul.
* Zones impactées : `openfisca_france/model/mesures.py`.
* Détails :
- Ajoute la CASA dans le calcul de `revenus_remplacement_pensions_bruts_menage`
- - - -

Corrige le calcul des revenus bruts

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
setup.py
tests/formulas/aides_logement_fiabilisation.yaml
tests/mes-aides.gouv.fr/test_mes_aides_54d396fd4ec19fce4422725e.yaml
tests/mes-aides.gouv.fr/test_mes_aides_559d204131741cd84c323303.yaml
tests/mes-aides.gouv.fr/test_mes_aides_55f02b141e52de32043695f7.yaml

- `model/prestations/aides_logement`.
* Détails :
- Ajoute la variable 'date_debut_chomage'.
- Corrige une double application des coefficients 'coloc' et 'chambre' dans aides_logement.
- Corrige l'application de la règle des 2/3 du montant du loyer pour l'AL et l'APL.

Fiabilisation générale du calcul des aides au logement 

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie.py
openfisca_france/parameters/cotsoc/tehr.yaml
setup.py

* Périodes concernées : à partir du 01/01/2015.
* Zones impactées : `prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite`.
* Détails :
- Supprime la taxe exceptionnelle sur les hauts revenus à partir de 2015 (variable `tehr`), car taxation en vigueur seulement sur les revenus de 2013 et 2014.

Supprime la TEHR à partir de 2015

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/revenus/capital/plus_value.py
setup.py

Contexte : 
- La case 3SA était utilisée dans le formulaire de déclaration de l'IR sur revenus 2012. Ensuite elle disparait.
- La case 3SA est réintroduite (nouvelle signification) en 2016.
- Problème : La variable `f3sa` dans OF avait une end date en 2012 et n'était pas réintroduite en 2016. Le calcul de l'impôt sur le revenu (depuis les revenus 2016) était donc incorrect puisqu'il faisait appel à une variable "neutralisée".
* Périodes concernées : à partir du 01/01/2012
* Zones impactées : `openfisca_france/model/prelevements_obligatoires/impot_revenu`.
* Détails :
- Crée une variable `f3sa` correspondant à la case 3SA réintroduite à partir de 2016
- Renomme la variable `f3sa` (existant précédemment et correspondant à la case en 2012) en `f3sa_2012` …

Réintroduit la case 3SA à partir de 2016

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
openfisca_france/model/prestations/minima_sociaux/rsa.py
setup.py
tests/formulas/rsa.yaml
tests/formulas/rsa/rsa_2017.yaml

* Évolution du système socio-fiscal **non rétrocompatible**
* Périodes concernées : à partir de 2017.
* Zones impactées : `prestations/minima_sociaux/rsa.py`.
* Détails :
- Supprime `extra_param` du calcul du RSA. Le RSA est calculé au titre d'un mois donné (correspondant à l'argument `period`), en fonction des paramètres en vigueur durant ce mois-ci, et en fonction des ressources de `period.last_3_months`. On supprime la variable `rsa_fictif`, qui devient redondante.
- Implique la suppression de la distinction des revenus d'activités moyennés et non-moyennés dans la base ressources : suppression des variables `indemnite_fin_contrat_net`, `primes_salaires_net` et `salaire_net_hors_revenus_exceptionnels`.
- Autres variables impactées : `rsa_base_ressources`, …

Supprime extra_param du calcul du RSA

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ppa.py
setup.py
tests/formulas/ppa.yaml
tests/formulas/ppa/ppa_ressources_hors_activite_individu.yaml

* Zones impactées : `prestations\minima_sociaux\ppa`.
* Détails :
- Ajoute les rentes foncières à titre onéreux dans la base ressources de la PPA
- Appelle dans les revenus du capital le douzième de l'année N-2, et pas le mois d'il y a deux ans.

Améliore la base ressources des revenus du capital de la PPA

---

CHANGELOG.md
openfisca_france/parameters/cmu/plafond_base.yaml
openfisca_france/parameters/prestations/minima_sociaux/asi/montant_couple.yaml
openfisca_france/parameters/prestations/minima_sociaux/asi/montant_seul.yaml
openfisca_france/parameters/prestations/minima_sociaux/asi/plafond_ressource_couple.yaml
openfisca_france/parameters/prestations/minima_sociaux/asi/plafond_ressource_seul.yaml
openfisca_france/parameters/prestations/prestations_familiales/af/bmaf.yaml
setup.py

* Revalorisation périodique.
* Périodes concernées : à partir du 01/04/2019.
- `parameters/prestations/prestations_familiales/af`.
- `parameters/cmu`.
- `parameters/prestations/minima_sociaux/asi`.
* Détails :
- Revalorise l'allocation familiale (AF) au 1er avril 2019 en métropole .
- Revalorise l'aide CMU-c et ACS au 01 avril 2019 en métropole .
- Revalorise l’allocation supplémentaire d’invalidité (ASI) au 1er avril 2019.

Revalorisations PFs au 1er Avril 2019

---

CHANGELOG.md
openfisca_france/model/prestations/prestations_familiales/base_ressource.py
openfisca_france/model/prestations/prestations_familiales/cf.py
setup.py
tests/formulas/cf.yaml

- `prestations/prestations_familiales/base_ressources`
- `prestations/prestations_familiales/cf`
* Détails :
- Injecte les revenus fiscaux non individualisables dans la base ressources du CF
- Crée une variable `prestations_familiales_base_ressources_communes` pour mutualiser cette opération pour les différentes bases ressources des prestations familiales
- Renomme `cf_ressources` par `cf_base_ressources` et `cf_ressources_individu` par `cf_base_ressources_individu`.
Résout #1299

Ajoute les revenus non individualisables dans la base ressources du CF

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
setup.py

* Périodes concernées : depuis 2002.
* Zones impactées : `credits_impots`.
* Détails :
- Factorise la formule générale des crédits d'impôt
- - - -
- - - -
Fixes #1202

Factorise la formule des crédits d'impôt

---

CHANGELOG.md
setup.py

* Détails :
- Exige `flake8 >= 3.7` (et pycodestyle transitivement; la double spécification était nécessaire avant la version 3.7 de flake8 mais ce n'est plus le cas)
- - - -
- - - -

Exige flake8 >= 3.7 et pycodestyle implicitement

---

CHANGELOG.md
openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
openfisca_france/model/mesures.py
openfisca_france/model/prestations/minima_sociaux/cmu.py
openfisca_france/model/prestations/prestations_familiales/base_ressource.py
setup.py

* Détails :
- Transforme les références aux rôles de la forme `famille.PARENT` en `Famille.PARENT`.
- (Ces changements sont rétro-compatibles et n'exigent pas d'ajuster la version de Core requise par France)
- - - -
- - - -

Adapte France au remaniement des classes Entity/Population

---

.circleci/config.yml
CHANGELOG.md
Makefile
openfisca_france/parameters/cotsoc/tehr.yaml
setup.py
tests/reforms/test_plf2016.py
tests/test_api.py
tests/test_basics.py

* Détails :
- Adapte les tests de France à l'utilisation de Pytest
- Déclare le paquet compatible avec Core 34

Exécute tous les tests avec Pytest

---

CHANGELOG.md
openfisca_france/parameters/prestations/minima_sociaux/rsa/montant_de_base_du_rsa.yaml
setup.py

* Revalorisation périodique.
* Périodes concernées : à partir du 01/04/2019.
* Zones impactées : `parameters/prestations/minima_sociaux/rsa/montant_de_base_du_rsa`.
* Détails :
- Revalorise le montant de base du rsa au 1 avril 2019.

Revalorisation du Revenu de solidarité active (RSA) au 1er avril 2019 en métropole

---

CHANGELOG.md
openfisca_france/model/base.py
openfisca_france/model/caracteristiques_socio_demographiques/logement.py
openfisca_france/model/patrimoine/livret_epargne_populaire.py
openfisca_france/parameters/epargne/livret_epargne_populaire.yaml
setup.py
tests/patrimoine/livret_epargne_populaire/eligibilite.yml
tests/patrimoine/livret_epargne_populaire/plafond.yml

* Zones impactées : `model/patrimoine/livret_epargne_populaire.py`.
* Détails :
- Ajoute l'éligibilité au Livret d'épargne populaire
- - - -

Ajoute l'éligibilité au Livret d'épargne populaire

---

CHANGELOG.md
openfisca_france/model/revenus/remplacement/rente_accident_travail.py
setup.py
tests/formulas/rente_at.yaml

* Zones impactées : `revenus/remplacement/rente_accident_travaill`.
* Détails :
- Les formules de la rente accident du travail fonctionne pour des personnes de plus de 100 ans

Limite l'âge à 100 ans pour rentrer dans le barème rente AT

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ass.py
setup.py
tests/formulas/ass_abbattement.yaml
tests/mes-aides.gouv.fr/test_mes_aides_556ece2d1619d23d68b91e46.yaml

* Correction d'un calcul existant
* Zones impactées : `prestations/minima_sociaux/ass`.
* Détails :
- Application de l’abattement sur les revenus de substitution pour l’allocation de solidarité spécifique (ASS).
- Factorise le calcule de l’abattement des ressources pour les variables ass_base_ressources_individu et ass_base_ressources_conjoint.

Implémentation de l’abattement sur le revenu de substitution pour l’ASS

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ada.py
setup.py
tests/formulas/ada.yaml

* Zones impactées : `prestations/minima_sociaux/ada`.
* Détails :
- Utilise numpy `not` à la place du `not` de Python qui ne gère pas les vecteurs
- - - -

Vectorise la formule de l'ADA

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
openfisca_france/parameters/impot_revenu/reductions_impots/rpinel/plafond.yaml
openfisca_france/parameters/impot_revenu/reductions_impots/rpinel/seuil.yaml
openfisca_france/parameters/impot_revenu/reductions_impots/rpinel/taux.yaml
openfisca_france/parameters/impot_revenu/reductions_impots/rpinel/taux12.yaml
openfisca_france/parameters/impot_revenu/reductions_impots/rpinel/taux18.yaml
openfisca_france/parameters/impot_revenu/reductions_impots/rpinel/taux23.yaml
openfisca_france/parameters/impot_revenu/reductions_impots/rpinel/taux29.yaml
setup.py
tests/calculateur_impots/yaml/reduc_malraux.yaml
tests/calculateur_impots/yaml/reduc_pinel_dom.yaml
tests/calculateur_impots/yaml/reduc_pinel_metro.yaml

* Périodes concernées : à partir du 01/01/2018.
* Zones impactées : `model/prelevements_obligatoires/impot_revenu/`.
* Détails :
- Ajoute comme inputs variables les nouvelles cases de la déclaration IR 2018 liée à la réduction Pinel.
- Renomme les anciennes inputs variables du même nom, selon la méthode habituelle 
- Mets à jour la formule de calcul de la réduction (introduction des investissements réalisés en 2018 et ajout du report des investissements 2017)
- Factorise les formules de la réduction Pinel
- Renomme le paramètre `seuil`en `plafond`
- Ajoute 2 tests issus des résultats du [calculateur en ligne du site impots.gouv](https://www3.impots.gouv.fr/simulateur/calcul_impot/2019/index.htm)
Cf. la [brochure …

Mets à jour la réduction d'impôt "Pinel" pour 2018 (IR 2019 sur revenus 2018)

---

CHANGELOG.md
openfisca_france/model/mesures.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
openfisca_france/model/revenus/capital/plus_value.py
setup.py
tests/formulas/revenu_disponible.yaml

**Contexte** : Le PFU a été codé avant la publication du nouveau formulaire de l'IR et des règles précises concernant son application. Désormais, le formulaire est disponible et les règles connues. Cette PR vient donc corriger la partie "taxation des plus-values". (Cf. #1083). 
Par ailleurs, elle s'appuie sur la disponibilité du [simulateur de l'IR 2019 sur revenus 2018](https://www3.impots.gouv.fr/simulateur/calcul_impot/2019/index.htm).
3 régimes de taxation possible :
- PFU : Une grande partie des plus-values est concernée par le PFU (et l'option au barème sur choix) : 3VG, 3UA
- Autres taxes forfaitaires : L'ancien système de taxe forfaitaire à des taux particuliers (différents du taux de 12,8% comme le PFU) perdure pour certaines plus-values : 3VM, 3VT, 3SK, 3SJ, 3WI, 3WJ, 3VI, 3VF, …

Corrige la taxation des plus-values

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
setup.py
tests/calculateur_impots/yaml/credit_quaenv.yaml

* Périodes concernées : à partir du 01/01/2018
* Zones impactées : `model/prelevements_obligatoires/impot_revenu/`.
* Détails :
- Ajoute comme inputs variables les nouvelles cases de la déclaration IR 2018 liée au CITE.
- Renomme les anciennes inputs variables du même nom, selon la méthode habituelle
- Mets à jour la formule de calcul du crédit (2 types de dépenses sont désormais éligibles seulement au taux réduit de 15)
- - - -

Mets à jour le crédit d'impôt pour la transition energétique (IR 2019 sur revenus 2018)

---

.circleci/config.yml
CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/aah.py
setup.py

* Zones impactées : `aah.py`.
* Détails :
- Corrige des erreurs de formatage bloquantes pour suivre les instructions du README
Fixes #1348 
- - - -
- - - -

Corrige les erreurs de formatage bloquantes

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/parameters/impot_revenu/decote/taux.yaml
setup.py

* Périodes concernées : Aucune (formule équivalente)
* Zones impactées : `model\prelevements_obligatoires\impot_revenu\ir.py`.
* Détails : 
- passage du 0.75 en paramètre, pour permettre d'éventuelles réformes.
- - - -
Ces changements (effacez les lignes ne correspondant pas à votre cas) : 

Passage du pourcentage de la décote en paramètre

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ass.py
setup.py

* Détails :
- Ajoute une référence à l'ASS

Ajoute une référence à l'ASS

---

CHANGELOG.md
openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
setup.py
tests/formulas/nationalite.yaml

* Zones impactées : `caracteristiques_socio_demographiques/demographie.py`.
* Détails :
- Ajoute une variable pour la nationalité des individus
- Rend `ressortissant_eee` calculable à partir de la `nationalite`

Ajoute une variable pour la nationalité des individus

---

CHANGELOG.md
openfisca_france/model/prestations/autonomie.py
setup.py

Fix #1363
Fix #1359
* Zones impactées : `openfisca_france/model/prestations/autonomie.py`
* Détails :
- Corrige erreur sur 'apa_domicile', 'apa_etablissement' et 'apa_urgence_domicile'
- Il s'agit d'une double comparaison, incompatible avec `numpy`
- - - -
- - - -

Corrige double comparaison incompatible avec Numpy

---

CHANGELOG.md
openfisca_france/conf/cache_blacklist.py
openfisca_france/model/prestations/minima_sociaux/ppa.py
setup.py

* Zones impactées : `prestations/minima_sociaux/ppa`.
* Détails :
- Améliore les conditions d'éligibilité à la PPA pour les couples avec étudiant
Aujourd'hui un couple avec un étudiant dont les revenus d'activité sont inférieurs au plancher est tout de même considéré comme éligible à la PPA si son conjoint n'est pas étudiant.
Cette PR vérifie que son conjoint a des revenus d'activité non nuls.

Améliore les conditions d'éligibilité à la PPA pour les couples avec étudiant

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ppa.py
setup.py

* Zones impactées : `prestations/minima_sociaux/ppa`.
* Détails :
- Change l'entité associée à `ppa_plancher_revenu_activite_etudiant`
- - - -

Corrige la nouvelle variable ppa_plancher_revenu_activite_etudiant

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/aah.py
setup.py
tests/formulas/complement_aah.yaml

* Périodes concernées : à partir du 01/12/2019.
* Zones impactées : `model/prestations/minima_sociaux/aah`.
* Détails :
- Supprime le complément de ressources au profit de la MVA à compter du 1er décembre 2019.

Fusion des aides des compléments de ressources à l’AAH au 1er Décembre 2019

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/taxe_habitation/taxe_habitation.py
setup.py

* Zones impactées : `openfisca_france/model/prelevements_obligatoires/taxe_habitation/taxe_habitation.py`.
- - - -
Avec le test suivant :
```py
from openfisca_core import periods
from openfisca_core.simulation_builder import SimulationBuilder
from openfisca_france import FranceTaxBenefitSystem
tax_benefit_system = FranceTaxBenefitSystem()
COUNT = 100
MIN = 0
MAX = 100000
PERIOD = 2018
test_case = {
"individus": {
"Michel": {
'date_naissance': {'ETERNITY': '1980-01-01'},
},
},
"familles": {
"famille_1": {
"parents": ["Michel"]
}
},
"foyers_fiscaux": {
"foyer_fiscal_1": {
"declarants": ["Michel"],
},
},
"menages": {
"menage_1": {
"personne_de_reference": ["Michel"],
}},
"axes": [[
{
"name": 'salaire_de_base',
"count": COUNT,
"min": MIN,
"max": MAX,
"period": PERIOD, …
```

Corrige la comparaison entre un array et un nombre

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/parameters/impot_revenu/rvcm/abatmob.yaml
setup.py

* Périodes concernées : à partir du 01/01/2012.
* Zones impactées : `prelevements_obligatoires/impot_revenu/ir.py`.
* Détails :
- Enlève des lignes mettant en dur à zéro à partir de 2012 des termes dépendant de `abatmob`, lui-même à zéro dans les paramètres à partir de cette date. Fait que pas possible de simuler des réformes relatives à cet abattement.

Corrige le code relatif à l'abattement fixe sur RVCM

---

CHANGELOG.md
openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
openfisca_france/model/prestations/minima_sociaux/rsa.py
openfisca_france/parameters/prestations/minima_sociaux/rsa/duree_min_titre_sejour.yaml
setup.py
tests/formulas/rsa/rsa_condition_nationalite.yaml

* Périodes concernées : à partir du 01/06/2009.
`openfisca_france/model/prestations/minima_sociaux/rsa.py`
`openfisca_france/parameters/prestations/minima_sociaux/rsa/duree_min_titre_sejour.yaml`
`openfisca_france/tests/formulas/rsa/rsa_condition_nationalite.yaml`
* Détails :
- Avant cette modification, un ressortissant de l'EEE était considéré comme ayant toujours droit au RSA, alors qu'en réalité il doit être en France depuis au moins 3 mois pour y avoir droit.
- Ce changement est lié à une évolution de l'interface Mes Aides : on y pose désormais une question sur la durée de résidence en France pour les ressortissants étrangers, et on souhaite donc se servir de cette donnée pour fiabiliser les résultats.
- - - - …

Intègre la condition d'obtention du RSA pour les ressortissants de l'EEE

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py
openfisca_france/model/prestations/autonomie.py
setup.py
tests/formulas/autonomie.yaml

Fix #1364
* Périodes concernées : à partir du 01/01/2002.
* Zones impactées : `prestations/autonomie.py`.
* Détails :
- Corrige `apa_urgence_institution`
- Corrige une date manquant dans l'appel de l'arbre de paramètres
- - - -
Ces changements (effacez les lignes ne correspondant pas à votre cas) corrigent ou améliorent un calcul déjà existant.
- - - -

Corrige la formule APA urgence (institution)

---

CHANGELOG.md
openfisca_france/model/prestations/autonomie.py
setup.py
tests/formulas/autonomie.yaml

* Périodes concernées : à partir du 01/01/2002.
* Zones impactées : `model/prestations/autonomie.py`.
* Détails :
- Améliore formule pour déterminer le tarif établissement pour le GIR de la personne dépendante.
- - - -
- - - -

Améliore calcul identifier tarif GIR de personne APA

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/cs/css.py
setup.py

* Correction d'un crash. 
* Périodes concernées : à partir du 01/11/2019
* Zones impactées : `model/prestations/minima_sociaux/cs/css`
* Détails :
- Répare une erreur de renommage dans une formule de la Complémentaire Santé Solidaire
- - - -

Utilise le bon nom de variable dans la CSS

---

CHANGELOG.md
setup.py

* Périodes concernées : N/A.
* Zones impactées : `setup.py`, `CHANGELOG.md`.
* Détails :
- La pull request #1388 a été intégrée sans modifier les fichiers `setup.py` et `CHANGELOG.md`
- Ceci fait que les déploiements PyPi soient rejetés.
- À son tour, cela fait tomber le script de vérification de version.
- - - -
- - - -

Corrige le déploiement PyPi

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
setup.py
tests/calculateur_impots/yaml/reduc_sous_conditions_ressources.yaml

* Évolution / Correction du système socio-fiscal.
* Périodes concernées : à partir du 01/01/2016.
* Zones impactées : `prelevements_obligatoires/impot_revenu/ir.py`.
* Détails :
- Corrige le calcul de la réduction dans le cas d'un couple au-dessus du premier seuil.
Fix #1390

Corrige le calcul de la réduction d'impôt sous conditions de ressources

---

CHANGELOG.md
openfisca_france/model/prestations/logement_social.py
setup.cfg
setup.py

Fixes #1394 
* Zones impactées : `model/prestations/logement_social.py`.
* Détails :
- La formule zone_logement_social retournait un scalar `numpy.ndarray[int]`.
- Corrige zone_logement_social pour retourner un vecteur `numpy.ndarray[bool]`.
- Note : à partir de Numpy 1.18, l'utilisation de `select` avec un valeur non `bool` est dépréciée.
- - - -
- - - -

Corrige zone_logement_social pour retourner un vecteur

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
setup.py
tests/formulas/csa.yaml

* Zones impactées : `/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre`.
* Détails :
- Correction d'une formula gérant la période en dur dans le code.
- - - -
- - - -
- ~[ ] Documentez votre contribution avec des références législatives~.

Suppression de période en dur dans la CSA

---

CHANGELOG.md
openfisca_france/parameters/cotsoc/gen/smic_h_b.yaml
setup.py

Fixes #1405
* Périodes concernées : à partir du 01/01/2020
* Zones impactées : `openfisca_france/parameters/cotsoc/gen/smic_h_b.yaml`.
* Détails :
- Mise à jour du smic horaire brut suite au décret n° 2019-1387 du 18 décembre 2019 portant relèvement du salaire minimum de croissance 
- - - -
> D'où un `smic_proratise` de `1539.4166 €` cohérent avec les `1 539,42 €` mensuels pour 35h du décret. 
- - - -

Ajoute le smic horaire brut 2020

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
setup.py
tests/formulas/ir_taux_marginal.yaml
tests/formulas/ir_tranche.yaml

Fixes #1386 
Depends on openfisca/openfisca-core#920
* Zones impactées : `prelevements_obligatoires/impot_revenu/ir`.
* Détails :
- Ajout du calcul du taux marginal et de la tranche applicable pour l'impôt sur le revenu
- - - -
- Ajoutent une fonctionnalité (voir #1386) :
- ajout de la variable `ir_tranche`.
- ajout de la variable `ir_taux_marginal`.
- - - -

Calcule la tranche et le taux marginal IR

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
setup.py
tests/calculateur_impots/yaml/abat_dividendes.yaml

**Contexte** 
Avant 2013, il existait deux systèmes d'imposition des dividendes à l'impôt sur le revenu : au barème progressif ou au prélèvement forfaitaire libératoire (PFL). Dans la déclaration de revenus, un contribuable doit déclarer ses dividendes en case 2DA si il a opté pour le PFL et en case 2DC si il a opté pour le barème. En pratique, il est possible de choisir une option "mixte", c'est-à-dire d'imposer une partie de ses dividendes à un des régimes d'imposition et une autre partie à l'autre régime. Cependant, si un contribuable opte pour une option "mixte", il perd le bénéfice de l'abattement de 40% applicable aux dividendes imposés au barème.
**Bug constaté**
Dans Openfisca, on simule bien l'abattement de 40% sur les dividendes pour les contribuables au barème mais on fait …

Corrige l'application de l'abattement sur dividendes

---

CHANGELOG.md
setup.py

Connected to openfisca/openfisca-core#958
⚠️ Fixation d'un bug spécifique à France suite à la dernière PR Core mergée openfisca/openfisca-core#958.
* Détails :
- Met à jour la librairie `pytest` employée pour les tests Python et YAML via la commande `openfisca test` héritée d'openfisca-core, pour les cibles d'installation `dev` et `casd-dev`.
- Corrige le décalage de version de `pytest` entre `Core` et `France`.
**Corrige ce bug :** 
Bug dû à la situation particulière de France qui spécifiait un `pytest < 5.0` avec OpenFisca-Core `34.7.5` spécifiant un `pytest >= 5.0` : 
```shell
$ openfisca test --country-package openfisca_france tests
========================================================= test session starts …
```

Met à jour la dépendance pytest

---

CHANGELOG.md
openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/couples.yaml
openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/famille_1pac.yaml
openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/majoration_par_pac_supp.yaml
openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/personnes_seules.yaml
openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/couples.yaml
openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/famille_1pac.yaml
openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/majoration_par_pac_supp.yaml
openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/personnes_seules.yaml
openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/couples.yaml
openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/famille_1pac.yaml
openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/majoration_par_pac_supp.yaml
openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/personnes_seules.yaml
setup.py

📍 Cette PR intègre les commits MSA de la branche `msa_fork_al_css_v1_7_1` concernant le dispositif de réduction de loyer de solidarité (RLS). À l'ouverture de cette PR, elle équivaut à l'intégration du commit 1463766e5cce5df0e6c921b5e5b85f9af334af4d  à `master` sans autre altération.
Noter qu'il s'agit aussi à ce jour du dernier commit (le plus récent) de `msa_fork_al_css_v1_7_1`.
---
* Périodes concernées : à partir du 01/01/2020.
* Zones impactées : `openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/`.
* Détails :
- Mise à jour des montants de réduction de loyer de solidarité (RLS) pour janvier et octobre 2020.
- - - -
- - - -
Quelques conseils à …

Revalorisation des paramètres RLS pour janvier et octobre 2020

---

CHANGELOG.md
openfisca_france/model/prestations/prestations_familiales/af.py
setup.py
tests/formulas/af_2019_1_dom_complement.yaml
tests/formulas/af_2020_04.yaml

* Zones impactées : `openfisca_france/model/prestations/prestations_familiales/af.py`.
* Détails :  Le deuxième alinéa de l'article L. 755-12 du code de la sécurité sociale dispose :
> "Toutefois, les quatre derniers alinéas de l’article L. 521-1 ne sont pas applicables lorsque le ménage ou la personne a un seul enfant à charge.
Cet article s'applique dans le cas des allocations familiales dans les DOM hors Mayotte. Or, le dernier alinéa de l'article L. 521-1 correspond au complément dégressif des allocations familiales et de leur majoration. Le complément dégressif ne devrait donc pas s'appliquer dans le cas d'un ménage résidant en DOM hors Mayotte et ayant un enfant à charge.
- - - -
Ces changements (effacez les lignes ne correspondant …

Corrige la non applicabilité du complément dégressif

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/rsa.py
openfisca_france/parameters/prestations/minima_sociaux/rsa/montant_de_base_du_rsa.yaml
setup.py
tests/formulas/rsa.yaml

📍 Cette PR intègre les commits MSA de la branche `msa_fork_al_css_v1_7_1` concernant le RSA.
Elle équivaut à l'intégration des commits suivants à `master` sans autre altération : dfc2d5717c9ea474de8b3b61a36746539b9aacd0, 48051dd312ee4993bfb784987cd286107d2b59d7 et 5423f92ff1938685ee9eabd984510ef5345cf72b.
---
* Périodes concernées : à partir de 06/2009 (base ressources).
- `openfisca_france/model/prestations/minima_sociaux/rsa.py`
- `openfisca_france/parameters/prestations/minima_sociaux/rsa/montant_de_base_du_rsa.yaml`
* Détails : 
- Met à jour le montant de base du RSA pour avril 2020.
- Ajoute les ressources de l'apprenti à la base de ressources du RSA via `rsa_revenu_activite_individu` et le teste.
- - - -
Ces changements : 
- …

Ajoute la revalorisation RSA d'avril 2020 et fiabilise le cas apprenti

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
setup.py
tests/impot_revenu/nombre_de_parts/celibataire_ou_divorce.yaml
tests/impot_revenu/nombre_de_parts/maries_ou_pacses.yaml
tests/impot_revenu/nombre_de_parts/parent_isole.yaml
tests/impot_revenu/nombre_de_parts/veufs.yaml

Fixes #1418 
* Zones impactées : `prelevements_obligatoires/impot_revenu/ir.py`.
* Détails :
- Corrige le calcul du nombre de parts pour un·e veuf·ve
- Dans le cas où un·e veuf·ve aurait au moins un·e enfant à charge en garde alternée
- - - -
- - - -

Corrige calcul nombre de parts veuf·ve

---

CHANGELOG.md
setup.py

Connected to openfisca/openfisca-core#924
⚠️  Branche de référence sur CircleCI définie sur les travaux Core de mise à jour de numpy.
Documentation : 
* Changements apportés par [numpy 1.18](https://numpy.org/devdocs/release/1.18.0-notes.html)
* Évolution de [numpy.select()](https://github.com/openfisca/openfisca-core/issues/924#issuecomment-615512006)
---
* Amélioration technique non rétro-compatible.
* Détails :
- Adapte OpenFisca-France à [numpy v1.18](https://numpy.org/devdocs/release/1.18.0-notes.html#expired-deprecations) au travers de la mise à jour à Core v35.
- Impacte les syntaxes des formules de calcul possibles du dépôt et de ses extensions.
- - - -
- Modifient l'_API …

Met à jour la dépendance numpy à sa version 1.18

---

CHANGELOG.md
openfisca_france/model/revenus/capital/financier.py
setup.py

* Zones impactées : `model/revenus/capital/financier.py`.
* Détails :
- Rend les variables de valeur de patrimoine indépendantes de la taille de la période.

Ajoute is_period_size_independent = True pour les variable de patrimoine

---

CHANGELOG.md
openfisca_france/model/prestations/alimentation.py
setup.py
tests/formulas/crous_repas_un_euro.yaml
tests/formulas/repas_crous.yaml

* Périodes concernées : à partir de 01/2021.
- `prestations/alimentation.py`
* Détails :
- Ajoute l'éligibilité à l'aide repas CROUS à 1€ pour tout étudiant.
- - - -
- - - -
---
Informations complémentaires : 
* L'aide _tout étudiant_ est entrée en application entre le 22 et le 25 janvier de cette année.
* Une aide équivalente mais réservée aux _étudiants boursiers_ existait à partir de septembre 2020 d'après [service-public](https://www.service-public.fr/particuliers/actualites/A14614) mais elle n'est pas représentée ici.
* L'aide est conditionnée à la création d'un compte Izly (CROUS). La condition est …

Ajoute l'éligibilité au repas CROUS à 1€ pour tout étudiant

---

CHANGELOG.md
openfisca_france/model/prestations/transport.py
openfisca_france/parameters/prestations/transport/pret_formation_permis.yaml
setup.py
tests/formulas/pret_formation_permis.yaml

- `prestations/transport.py`
* Détails :
- Ajoute l'éligibilité au prêt à la formation au permis de conduire à 1€ par jour
- Le prêt est un prêt à taux zéro dont les intérêts sont pris en charge par l'État
- - - -
- - - -
---
Informations complémentaires : 
* L'existence d'un prêt à la formation au permis de conduire est antérieure à cette année. Mais je n'ai pas retrouvé depuis quand il permettait un permis à 1€ par jour.
* Les conditions d'attribution suivantes n'ont pas été intégrées parce qu'elles ne semblaient pas nécessaire à l'évaluation d'éligibilité en simulateur …

Ajoute l'éligibilité au prêt pour la formation au permis de conduire

---

CHANGELOG.md
Makefile
setup.py

Fixes #1494 
* Détails :
- Force la réinstallation d'OpenFisca France lors de la création du fichier de distribution d'OpenFisca France
- Erreur constatée lors du lancements des tests sur CircleCI :
- CircleCI utilise ce fichier pour faire tourner les tests
- Or, si de commits ont déjà été poussés sur un branch, CircleCI ne réinstalle pas OpenFisca France
- Ce qui est inattendu puisque si l'on ajoute par exemple un paramètre ou une variable après avoir poussé les changements une première fois, CircleCI va échouer car la version utilisée pour lancer les tests ne contient pas ces derniers changements
- - - -
- - - -

Force la réinstallation du build

---

.gitignore

* Zones impactées : `.gitignore`.
* Détails :
- Empêche le versionnement des environnements virtuels.
- - - -

Ignore virtual environment folder

---

CHANGELOG.md
openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
openfisca_france/model/prestations/garantie_pret_etudiant.py
openfisca_france/parameters/demographie/age_majorite.yaml
setup.py
tests/formulas/demographie/majeur.yaml
tests/formulas/garantie_pret_etudiant.yaml

* Périodes concernées : à partir de 1579 (XVIᵉ siècle).
- `parameters/demographie/age_majorite.yaml`
* Détails :
- Ajoute la variable `majeur` qui calcule si la personne a atteint la majorité civile par son âge on son émancipation.
- Ajoute la variable `mineur_emancipe`.
- Ajoute le paramètre `demographie.age_majorite` qui donne l'âge d'obtention de la majorité civile.
- Améliore le calcul de `garantie_pret_etudiant` en utilisant une condition de majorite et non d'âge.
- - - -
- - - -
Followup of #1489.

Calcule la majorité civile et améliore le calcul de l'éligibilité au prêt étudiant garanti par l'État

---

CHANGELOG.md
openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
openfisca_france/model/divers/gratuite_musees_monuments.py
openfisca_france/parameters/divers/gratuite_musees_monuments.yaml
openfisca_france/parameters/geopolitique/ue.yaml
setup.py
tests/formulas/divers/gratuite_musees_monuments.yaml
tests/formulas/nationalite.yaml

* Périodes concernées : à partir du 01/01/1958.
- `parameters/geopolitique/ue.yaml`
- `parameters/divers/gratuite_musees_monuments.yaml`
- `model/demographie.py`
- `model/divers/gratuite_musees_monuments.py`
* Détails :
- Ajoute la variable `gratuite_musees_monuments`, qui indique l'éligibilité à la gratuité d'accès aux musées et monuments nationaux pour les jeunes résident·e·s de l'Union européenne.
- Ajoute la variable `resident_ue`, qui calcule la résidence dans un pays de l'Union européenne à partir de la `nationalite` et peut être écrasée si l'information est obtenue de manière plus précise.
- Ajoute le paramètre `geopolitique.ue`, qui donne l'évolution de la liste des pays de l'Union européenne de 1958 à 2021.
- - - -
Ces …

Ajoute la gratuité d'entrée aux musées et monuments nationaux et la liste des pays des l'Union européenne

---

CHANGELOG.md
setup.py

Fixes #1458 
* Détails :
- Supprime option d'internationalisation du `setup.py`
- On utilise `python setup.py --version` pour vérifier la version
- Le fichier `setup.py` contenait l'option `message_extractors`
- Cette option d'internationalisation n'est pas reconnue par `distutils`
- Puisqu'aucune internationalisation n'est prévue, il semblerait être une option qui n'est plus valide ni nécessaire
- La suppression de l'option `message_extractors` corrige aussi le script de vérification de version
- - - -
- - - -
- - - -

Supprime option d'internationalisation du setup.py

---

CHANGELOG.md
openfisca_france/conf/cache_blacklist.py
openfisca_france/model/prestations/aide_permis_demandeur_emploi.py
openfisca_france/parameters/allocation_retour_emploi/montant_minimum.yaml
openfisca_france/parameters/prestations/transport/aide_permis_demandeur_emploi.yaml
setup.py
tests/formulas/aide_permis_demandeur_emploi.yaml

* Périodes concernées : À partir du 11/04/2011.
* Zones impactées : `prestations/aide_permis_demandeur_emploi.py`.
* Détails :
-  Ajoute l'aide à l’obtention du permis de conduire automobile pour les demandeurs d’emploi.
- - - -
Cette PR repose sur #1502 
- - - -

 Ajoute l'aide à l’obtention du permis de conduire automobile pour les demandeurs d’emploi

---

CHANGELOG.md
openfisca_france/model/prestations/mobili_jeune.py
openfisca_france/parameters/prestations/mobili_jeune.yaml
setup.py
tests/formulas/mobili_jeune.yaml

* Périodes concernées : à partir du 01/07/2012.
* `prestations/mobili_jeune.py`
* `parameters/prestations/mobili_jeune.yaml`
* Détails :
- Ajoute la variable `mobili_jeune` qui calcule le montant de l'aide Mobili-jeune.
- - - -

Calcule le montant de l'aide Mobili-jeune

---

CHANGELOG.md
openfisca_france/model/prestations/enseignement_superieur/bourse_criteres_sociaux.py
setup.py
tests/formulas/bourses_superieur/bourse_criteres_sociaux.yaml

* Zones impactées : `prestations/enseignement_superieur/bourse_criteres_sociaux.py`.
* Détails :
- Corrige le calcul de l'échelon des bourses sur critères sociaux.
- - - -
- - - -

Corrige le calcul bourse_criteres_sociaux_echelon suite au refactoring

---

CHANGELOG.md
openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
setup.py

* Zones impactées
* `caracteristiques_socio_demographiques/demographie`.
* `prelevements_obligatoires/impot_revenu/ir`.
* Détails :
- Renomme `caseH`, dont le nom prêtait à confusion. Car il s'agit de l'année de naissance des enfants déclarés dans la case H, cette dernière renvoyant à la variable `nbH`.

Renomme caseH

---

CHANGELOG.md
openfisca_france/parameters/bourses_enseignement_superieur/criteres_sociaux/points_de_charge.yaml
openfisca_france/parameters/bourses_enseignement_superieur/criteres_sociaux/seuil_ressources_etudiant_autonome.yaml
setup.py

**Contexte** : En essayant d'appliquer une réforme de type [`asof`](https://github.com/openfisca/openfisca-survey-manager/blob/master/openfisca_survey_manager/utils.py#L121) au tax benefit system d'Openfisca-France, je suis tombée sur une erreur concernant le format de certaines dates dans le tax benefit system.
NB : Je vois qu'il y a beaucoup de travaux en cours sur d'autres branches concernant les aides pour les jeunes donc peut-être que cette MR fait doublon. Si c'est le cas désolée et n'hésitez pas à la fermer :) 
* Périodes concernées : à partir du 31/03/2006.
* Zones impactées : `parameters/bourses_enseignement_superieur/criteres_sociaux`.
* Détails :
- Correction du format de dates dans des paramètres liés aux bourses du supérieur
- - - -
Ces changements …

Corrige le format de certaines dates

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
setup.py

Connected to issue #1479
* Zones impactées : `/model/prelevements_obligatoires/impot_revenu/ir.py`.
* Détails :
- Ajout du libellé et de la description du taux_effectif
**Attention** : cette formule ne semble pas couverte par un test. Le BOFIP présente un détail de calcul qui pourrait servir pour un test : [Exemple_dapplication](https://bofip.impots.gouv.fr/bofip/4616-PGP.html/identifiant=BOI-IR-LIQ-20-30-30-20120912#Exemple_dapplication_210)

Ajout de doc sur taux_effectif

---

openfisca_france/model/prestations/cheque_energie.py
tests/formulas/cheque_energie/eligibilite_logement.yaml

* Zones impactées : `prestations/cheque_energie.py`.
* Détails :
- Limite l'éligiblite du chèque énergie aux ménages avec déclarants fiscaux.
- - - -
- - - -

Limite l'éligiblite du chèque énergie aux ménages avec déclarants fiscaux

---

CHANGELOG.md
openfisca_france/parameters/autonomie/mtp/mtp.yaml
setup.py

* Périodes concernées : à partir du 01/04/2021.
* Zones impactées : `autonomie.mtp.mtp`.
* Détails :
- Mise à jour d'après circulaire CNAV.
- - - -
- - - -
Corrige #1554.

Mise à jour du montant de la majoration tierce personne

---

README.md

* Périodes concernées : à partir du 01/01/2019
* Zones impactées : `README.md`
* Détails :
- Supprime l'information de rétro-compatibilité à Python 2.7
- - - -
- - - -

Supprime l'information de rétro-compatibilité python 2.7

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie.py
openfisca_france/model/prestations/minima_sociaux/aah.py
openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
openfisca_france/model/prestations/prestations_familiales/af.py
openfisca_france/model/prestations/prestations_familiales/base_ressource.py
setup.py

closes #1403
* Amélioration technique 
- `model/prelevements_obligatoires/impot_revenu/ir.py`
- `model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie.py`
- `model/prestations/minima_sociaux/aah.py`
- `model/prestations/minima_sociaux/asi_aspa.py`
- `model/prestations/prestations_familiales/af.py`
- `model/prestations/prestations_familiales/base_ressource.py`
* Détails :
- Enlève les opérateurs unaires '+' des formules qui génèrent les warnings Numpy.
- - - -

Fix Numpy warnings

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general/ss/salaire_sous_pss/cotisation_ouvriere/moins_de_65_ans.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general/ss/salaire_sous_pss/cotisation_ouvriere/plus_de_65_ans.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general/ss/salaire_sous_pss/cotisation_patronale.yaml
setup.py

* Zones impactées : `openfisca_france/parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general/ss/salaire_sous_pss/`.
* Détails :
- Correction de format de dates dans les metadata de paramètres.
- Erreurs détectées par le validateur Leximpact.
- - - -
- Modifient des metadata.

Correction du format des dates dans official_journal_date

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/apprentissage/apprentissage.yaml
openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/apprentissage/apprentissage_250.yaml
openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/apprentissage/apprentissage_add.yaml
openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/apprentissage/apprentissage_alsace_moselle.yaml
setup.py

* Zones impactées : `parameters`.
* Détails :
- Dans les metadonnées des paramètres, renommage de `date_parution_jo` en `official_journal_date`
- Modifient l'API publique d'OpenFisca France, mais seulement dans les metadata et ce sont des corrections.

Renommage de date_parution_jo en official_journal_date

---

CHANGELOG.md
openfisca_france/model/prestations/depart1825.py
openfisca_france/parameters/prestations/depart1825.yml
setup.py
tests/formulas/depart1825.yaml

* Périodes concernées : à partir du 05/09/2014.
* Zones impactées : `prestations/depart1825.py`.
* Détails :
- Ajoute une première version du dispositif départ 18-25
- - - -
- - - -

Ajoute une première version du dispositif départ 18-25

---

CHANGELOG.md
CONTRIBUTING.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
pat_sal_harmonisation_cotsoc_d51a4555d.txt
pat_sal_master_f59d01ec9.txt
setup.py

* Zones impactées : `openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py`.
* Détails : Dans la formule de calcul de "rnps_imposable", une des clés semble avoir une faute de frappe (revevenus_non_salaries)
Cette clé est uniquement dans cette formule.
- - - -
Ces changements (effacez les lignes ne correspondant pas à votre cas)  corrigent ou améliorent un calcul déjà existant.

Correction d'une faute de frappe

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
setup.py

* Périodes concernées : jusqu'au 31/12/2005
* Zones impactées : /model/prestations/minima_sociaux/asi_aspa.py
* Détails :
- L'aspa n'existe pas avant 2006

aspa n'existe pas avant 2006

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
setup.py

* Zones impactées : `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py`.
* Détails :
- Ajout des set_input manquants empêchant la saisie de montant annuels.
- - - -
- Ajoutent une fonctionnalité

Ajout de set_input manquants.

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique.py
openfisca_france/model/revenus/activite/salarie.py
setup.py

* `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py`
* `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique.py`
* `openfisca_france/model/revenus/activite/salarie.py`
* Détails :
- En tout et pour tout, il y avait 3 fonctions appelées par des formules OpenFisca, qui recevaient la racine des paramètres en argument.
- Or, ces 3 fonctions n'utilisent chacune qu'une partie bien spécifique de l'arbre des paramètres.
- Ce patch modifie l'appel de ces 3 fonctions afin de leur fournir uniquement la partie spécifique de l'arbre qui les concerne.
- Cela facilite la détection automatique des paramètres …

Affine les paramètres passés aux fonctions appelés par des formules.

---

Makefile

Closes #1644 
* Zones impactées : `Makefile`.
* Détails :
- Retire les doublons des tests Python dans `make test` en retirant l'appel à `pytest`.

Retire le doublon pytest

---

CHANGELOG.md
openfisca_france/model/prestations/mon_job_mon_logement.py
openfisca_france/parameters/prestations/mon_job_mon_logement.yaml
setup.py
tests/formulas/mon_job_mon_logement.yaml

- `/prestations/mon_job_mon_logement.py`
- `/parameters/prestations/mon_job_mon_logement.yaml`
* Détails :
- Ajoute la variable `mon_job_mon_logement` qui calcule l'aide mon job mon logement d'action logement.
- - - -
- Ajoute une variable `mon_job_mon_logement` qui calcule l'aide.
- Ajoute les variables `mon_job_mon_logement_eligibilite`, `mon_job_mon_logement_eligibilite_jeunes_actifs`, `mon_job_mon_logement_eligibilite_logement` qui vérifie l'éligibilité à l'aide `mon_job_mon_logement`.
- Ajoute une variable `date_entree_logement` pour récupérer la date d'entrée du ménage dans un logement. Cette variable est nécessaire pour calculer `mon_job_mon_logement`.
- - - -

Ajoute l'aide mon job mon logement

---

.circleci/config.yml
.circleci/lint-changed-python-files.sh
.circleci/lint-changed-yaml-tests.sh
CHANGELOG.md
setup.py

Closes #1643 
* Zones impactées : `.circleci/config.yml`.
* Détails :
-  Sépare les jobs `test-python` et `test-yaml` du `build`.
-  Regroupe les deux jobs `lint_python_files` et `lint_yaml_files` dans un seul job.
-  Rend le job `check-version-and-changelog` dépendant de tous les autres jobs.

Restructure la configuration CircleCI

---

CHANGELOG.md
openfisca_france/parameters/marche_travail/salaire_minimum/smic_h_b.yaml
setup.py

* Périodes concernées : 1995 - 2001
* `parameters/marche_travail/salaire_minimum/smic_h_b.yaml`
* Détails :
- Ajoute quelques années au SMIC horaire brut
- Les valeurs sont en francs avant 2001
- Elles sont prises des barèmes IPP: https://www.ipp.eu/ipp-tax-and-benefit-tables/en/labour-market/salaire_minimum/smic
- Je m'arrête à 1995 car je souhaite faire tourner les données ERFS et elles commencent en 1996

ajoute des valeurs aux smic horaire brut

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general/cnav/salarie/vieillesse_deplafonnee.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general/mmid/taux.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general/mmid_am/maladie_alsace_moselle.yaml
setup.py

* Zones impactées : `openfisca_france/parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general`.
* Détails :
- Correction d'erreurs sur les `unit` dans les metadata de paramètres YAML.

Parameters metadata fixes

---

CHANGELOG.md
openfisca_france/model/prestations/alimentation.py
setup.py

* Périodes concernées : à partir du 01/07/2021.
* Zones impactées : `prestations/alimentation.py`.
* Détails :
- Limite le dispositif repas à 1€ aux étudiants boursiers
- - - -

Limite le dispositif repas à 1€ aux étudiants boursiers

---

CHANGELOG.md
openfisca_france/model/prestations/alimentation.py
openfisca_france/model/prestations/education.py
openfisca_france/parameters/prestations/carte_des_metiers.yaml
setup.py
tests/formulas/crous_repas_un_euro.yaml

* Périodes concernées : à partir du 01/01/2021.
- `model/prestations/alimentation.py`
- `parameters/crous_repas_un_euro.yaml`.
- `model/prestations/education.py`
* Détails :
- Ajoute une condition d'éligibilité sur l'âge des alternants pour l'aide `crous_repas_un_euro_eligibilite`.
- - - -
- - - -

Ajoute une condition d'éligibilité sur l'âge des alternants pour le repas à un euro du crous

---

.github/workflows/workflow.yml

**Problèmes :**
1. Problème de cold-start. La première exécution du workflow sur une nouvelle branche qui ne modifie pas le `setup.py` fait appel au dernier cache du `build` sur la `master`.  Le cache de la dernière exécution sur la `master`est restauré et par conséquent le `build` qui contient les modifications de la nouvelle branche n'est pas exécuté.
2. La version de Python entre le `build` et les `tests` changent parfois de `3.7.11` à `3.7.12`, ce qui change la clé du cache et par conséquent les jobs de test n'arrivent pas à récupérer le bon cache.
**Solutions :**
1. Rajouter le nom de la branche à la clé de cache pour s'assurer qu'on récupère toujours le bon `build`.
2. Préciser le patch de la version Python à utiliser `3.7.12`
**Détails:**
*  Correction d'un bug sur la CI
* Zones …

Résoudre les fails de récupération de cache sur la CI

---

.github/check-api-version.py
.github/workflows/workflow.yml
CHANGELOG.md
setup.py

Related to #1663 
**Problème:**
L'API n'est pas mise à jour après le publication du package.
**Solution proposée:**
Ajouter un test automatisé pour vérifier que la version de l'API déployée est bien celle qui vient d'être publiée avec GitHub Actions.
**Détails:**
* Zones impactées : configuration de l'intégration continue.
* Détails :
- Ajoute la vérification de la version du package de l'api web

Vérifier la version de l'API déployée

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
setup.py

* Périodes concernées : jusqu'au 31/12/2018 (inclus) à partir du 21/12/2018 (inclus)
* Zones impactées : `model/prelevements_obligatoires/prelevements_sociaux/travail_prive.py`.
* Détails :
- Erreur dans l'end_date de 8 cotisation sociales concernées par la fusion Agirc Arrco (agff, agirc, arrco, cet, employeur et salarié)
- - - -
- - - -

Corrige les end date de 8 cotisations touchees par fusion agirc arrco

---

CHANGELOG.md
openfisca_france/parameters/cs/cmu/plafond_base.yaml
setup.py

* Périodes concernées : à partir du 01/04/2021.
* Zones impactées : `openfisca_france\parameters\cs\cmu\plafond_base.yaml`.
* Détails :
- Ajoute le montant du plafond de base de la Complementaire Santé Solidaire revalorisé pour Avril 2021

Ajoute la revalorisation du plafond de base de la CSS pour Avril 2021

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/ensemble_des_entreprises/reduction_maximale/entreprises_de_20_salaries_et_plus.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/ensemble_des_entreprises/reduction_maximale/entreprises_de_moins_de_20_salaries.yaml
setup.py

* Zones impactées : `parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/ensemble_des_entreprises/reduction_maximale/`.
* Détails :
- Corrige des références de paramètres qui contenaient par erreur l'attribut "ref" au lieu de "href".

Corrige 'ref' en 'href' dans les références de paramètres.

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/apprentissage/apprentissage_contribution_supplementaire/plus_de_250_entre_3_et_4pc.yaml
setup.py

* Zones impactées : `openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/apprentissage/apprentissage_contribution_supplementaire/plus_de_250_entre_3_et_4pc.yaml`.
* Détails :
- Correction d'une erreur de copier/coller : une date était dupliquée.

Suppression d'une date qui n'a rien à faire là.

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/versement_transport/bareme/taux_maximal/sous_pss.yaml
openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/versement_transport/bareme/taux_maximal/tout_salaire.yaml
setup.py

* Zones impactées : `openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/versement_transport/bareme/taux_maximal/`.
* Détails :
- Corrige date_parution_jo en official_journal_date.

Corrige date_parution_jo en official_journal_date.

---

.github/workflows/workflow.yml
CHANGELOG.md
setup.py

Fixes #1724 (selon ce qui est décrit par [ce commentaire](https://github.com/openfisca/openfisca-france/issues/1724#issuecomment-994837562))
* Zones impactées : `.github/workflows/workflow.yml`
* Détails :
- Corrige le statut du déploiement d'`openfisca-france`.
* Supprime de GitHub Action un mode de déploiement obsolète pour l'API Web.
- - - -
Question complémentaire 🙂 :
Chers reviewers,  À l'issue du merge de cette PR, pensez-vous qu'il faille conserver le `secrets.FRANCE_API_DEPLOY_KEY` des Settings d'openfisca-france ? J'envisage de le supprimer.
- - - -
- - - -

Retire de la CI le déploiement obsolète de l'API Web

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/cont_sur_options/employeur/index.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/cont_sur_options/employeur/taux_attributions_gratuites_options.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/cont_sur_options/employeur/taux_plein.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/cont_sur_options/employeur/taux_reduit.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/cont_sur_options/employeur/taux_stock_options.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/cont_sur_options/index.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/cont_sur_options/salarie/index.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/cont_sur_options/salarie/taux_plein.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/cont_sur_options/salarie/taux_reduit.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/forfait_social/index.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/forfait_social/seuil_effectif_prevoyance_complementaire.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/forfait_social/taux_plein.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/forfait_social/taux_reduit.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/forfait_social/taux_reduit_1.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/forfait_social/taux_reduit_2.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/forfait_social/taux_reduit_3.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/index.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/prevoyance/index.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/prevoyance/taux.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/retraites_chapeau/droits_certains.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/retraites_chapeau/index.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/retraites_chapeau/majoration.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/retraites_chapeau/taux_1.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/retraites_chapeau/taux_2.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/retraites_chapeau/taux_3.yaml
setup.py

* Zones impactées : `parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire`.
* Détails :
- Harmonisation des fichiers avec les barèmes-ipp
- Tous les chemins sont updatés pour ne pas casser le code
- - - -
- Modifient l'API publique d'OpenFisca France
- - - -

Harmonisation - Prelevements Sociaux - contributions_assises_specifiquement_accessoires_salaire (Partie 2)

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/reductions_impots/rpinel/taux.yaml
setup.py

* Périodes concernées : 01/2014.
* Zones impactées : `openfisca_france/parameters/impot_revenu/reductions_impots/rpinel/taux.yaml`.
* Détails :
- Corrige les dates des paramètres afin qu'elles aient toutes un jour. Dans tout OpenFisca-France seuls les taux de Pinel avaient ce problème.

Corrige les dates des paramètres afin qu'elles aient toutes un jour.

---

CHANGELOG.md
Makefile
setup.py

Bonjour,
Ce changement mineur permet de publier une archive tar.gz sur PyPi comme c'est le cas pour OpenFisca-Core.
Ceci permettra de la réutiliser pour publier OpenFisca-France sur Conda-Forge pour Anaconda. https://github.com/openfisca/openfisca-core/issues/1039
* Périodes concernées : aucune.
* Zones impactées : aucune.
* Détails :
- Pour pouvoir publier sur Conda-Forge, publie une archive des sources en tar.gz sur PyPi en plus du .whl.
- - - -
- Modifient des éléments non fonctionnels de ce dépôt (Makefile).
- - - -

tar.gz sur PyPi en plus du .whl

---

CHANGELOG.md
setup.py

Connecté à https://github.com/openfisca/openfisca-france/pull/1731 (Merci pour l'alerte @guillett !)
* Zones impactées : `CHANGELOG.md`.
* Détails :
- Indique que la version 80.4.6 comporte des changements non rétrocompatibles et les détaille.
- - - -
- - - -

Informe de l'erreur de versionnement sémantique en 80.4.6

---

CHANGELOG.md
openfisca_france/parameters/chomage/allocation_retour_emploi/montant_minimum_hors_mayotte.yaml
openfisca_france/parameters/chomage/allocation_retour_emploi/montant_minimum_mayotte.yaml
setup.py

* Zones impactées : `openfisca_france/parameters/chomage/allocation_retour_emploi/`.
* Détails :
- Corrige la structure des références dans les metadata.

Corrige le format des références dans les metadata de l'ARE afin que les dates soient à l'intérieur.

---

CHANGELOG.md
openfisca_france/model/prestations/prestations_familiales/ars.py
setup.py

* Évolution du système socio-fiscal. Correction d'un crash.
* Zones impactées : `prestations/prestations_familiales/ars.py`.
* Détails :
- Corrige les conditions en termes d'âge des enfants. Avant, tous les enfants ayant 5 ans en septembre était comptés. Les enfants ayant 18 ans en septembre étaient aussi comptés (alors qu'éligibilité jusqu'à 17 ans), et les montants majorés étaient définis en fonction de l'âge de septembre au lieu de décembre
- Corrige la formule de l'ARS différentielle : la déduction d'aide due à ce dispositif était divisée par le nombre d'enfants (dans la loi, cette division est mentionnée, mais pour la réduction due PAR enfant, pas pour la réduction totale).
- …

Corrige l'ARS

---

CHANGELOG.md
openfisca_france/model/prestations/prestations_familiales/cf.py
setup.py

* Évolution du système socio-fiscal. Correction d'un crash.
* Zones impactées : `prestations/prestations_familiales/cf.py`.
* Détails :
- Corrige les règles de cumul entre CF et les autres prestations

Corrige règle de cumul complément familial

---

CHANGELOG.md
openfisca_france/model/mesures.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/csg_crds.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie.py
openfisca_france/model/prestations/visale.py
setup.py
tests/formulas/travail_non_salarie/artisan_commercant_profession_liberale.yaml

- `openfisca_france/model/mesures.py`
- `openfisca_france/model/prestations/visale.py`
- `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py`
- `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/csg_crds.py`
- `tests/formulas/travail_non_salarie/artisan_commercant_profession_liberale.yaml`
* Détails :
- Divise la variable `csg_non_salarie` en deux variables : `csg_dedutible_non_salarie` et `csg_imposable_non_salarie`. En effet il existe bien une part déductible et une part imposable de la csg pour les revenus des travailleurs non salariés mais elle n'était pas codé jusque maintenant.
- Adapte les variables qui …

Correction prelevements sociaux independants

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py
openfisca_france/parameters/impot_revenu/prelevement_forfaitaire_unique_ir/index.yaml
openfisca_france/parameters/impot_revenu/prelevement_forfaitaire_unique_ir/seuil_taux_reduit_av.yaml
openfisca_france/parameters/impot_revenu/prelevement_forfaitaire_unique_ir/taux.yaml
openfisca_france/parameters/impot_revenu/prelevement_forfaitaire_unique_ir/taux_reduit_av.yaml
openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/partir_2018/taux_prelevement_forfaitaire_rev_capital_eligibles_pfu_interets_dividendes_etc.yaml
openfisca_france/parameters/taxation_capital/prelevement_forfaitaire/partir_2018/taux_prelevement_produits_assurance_vie_non_eligibles_prelevement_forfaitaire_unique.yaml
setup.py

* Périodes concernées : après 2018-01-01
- `parameters.impot_revenu.prelevement_forfaitaire_unique_ir`
- `parameters.taxation_capital.prelevement_forfaitaire.partir_2018`
* Détails : 
- Fusionne les doublons du PFU dans l'IR avec ceux qui sont dans Taxation du capital, sur le modèle IPP

Harmonisation - Impôt sur le Revenu - Prélèvement Forfaitaire Libératoire (Partie 2) 

---

.github/get_pypi_info.py
CHANGELOG.md
openfisca_france/model/mesures.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
openfisca_france/scripts/performance/measure_spiral_performances.py
setup.py
tests/formulas/revenu_disponible.yaml

* Correction de législation.
- `mesures.py`.
- `prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py`
- `prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py`
* Détails :
- Corrige des variables de bases taxables de revenus du capital
- Rationalise et corrige la variable `plus_values_base_large`

Corrige et rationalise certaines variables de revenus du capital

---

CHANGELOG.md
openfisca_france/model/mesures.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
openfisca_france/model/revenus/capital/plus_value.py
openfisca_france/parameters/impot_revenu/calcul_impot_revenu/pv/plus_values.yaml
setup.py

* Correction d'une erreur de législation
* Périodes concernées : 2017
- `prelevements_obligatoires/impot_revenu/ir.py`.
- `mesures.py`
- `prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py`.
* Détails :
- Ajoute en 2017 la case 3PI, créée cette année-là, et qui était présente seulement à partir de 2018

Ajoute case 3PI (plus-values sur instruments financiers taxables à 50%) en 2017

---

CHANGELOG.md
openfisca_france/model/caracteristiques_socio_demographiques/capacite_travail.py
openfisca_france/model/prestations/minima_sociaux/anciens_ms.py
setup.py

* Zones impactées : `caracteristiques_socio_demographiques/capacite_travail.py`.
* Détails :
- Ajoute `is_period_size_independent` pour `taux_capacite_travail` et `taux_incapacite`: sans cet argument, on avait des problèmes dans nos survey scenarios quand on rentrait cette variable en input. Ex: si on entrait 0.8, pour chaque mois de l'année des années, on avait 12*0.8, pour les mois de l'année d'après, on avait 12*12*0.8, etc. Et ce malgré le `set_input_dispatch_by_period`.

Correction caractéristiques variables handicap

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/deces_ac/artisans/sous_pss.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/cotisations_prestations/cipav.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/cotisations_prestations/servi.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/cotisations_prestations/vente.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/artisans_alsace_chiffre_affaires.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/artisans_hors_alsace_chiffre_affaires.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/professions_liberales_chiffre_affaires.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/servicecom_chiffre_affaires.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/ventecom_chiffre_affaires.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/formation_pl/sous_pss.yaml
setup.py

* Périodes concernées : à partir de 2021.
* Zones impactées : `openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales`.
* Détails :
- last_review + reference :  auto_entrepreneur.cotisations_prestations
Il y a un changement de valeur dans: auto_entrepreneur.cotisations_prestations.cipav en  2021-06-14
- last_review + reference : auto_entrepreneur.formation_professionnelle
- last_reviw + reference: formation_pl
Question pour formation_pl.sous_pss :  Depuis 2005, supplément de 0,9 % si leur conjoint a le statut de conjoint collaborateur. cela ne semble pas être pris en compte et est juste en note.

cotisations_taxes_professions_liberales : Ajout de valeurs manquantes et de last_review.

---

CHANGELOG.md
openfisca_france/model/prestations/jeunes/mobili_jeune.py
openfisca_france/parameters/prestations_sociales/aides_jeunes/mobilite/mobili_jeune/montant/maximum.yaml
setup.py
tests/formulas/mobili_jeune.yaml

* Zones impactées : `model/prestations/jeunes/mobili_jeune.py`.
* Détails :
- Corrige la date de formule de la variable `mobili_jeune`
- - - -
- - - -

Corrige la date de `mobili_jeune`

---

CHANGELOG.md
openfisca_france/model/prestations/transport.py
setup.py
tests/formulas/carte_sncf_eleve_apprenti.yaml

* Zones impactées : `openfisca_france/model/prestations/transport.py`.
* Détails :
- Limite l'éligibilité de l'aide `carte_sncf_eleve_apprenti` aux résidents de la métropole.
- - - -
- - - -

Met à jour l'aide `carte_sncf_eleve_apprenti`

---

CHANGELOG.md
openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/forfait_mobilier/nonbat/seuil.yaml
setup.py

* Périodes concernées : sans objet
* Zones impactées : aucune variable impactée.
* Détails :
- Corrige l'identation d'une référence d'un paramètre YAML.

Corrige l'identation d'une référence.

---

CHANGELOG.md
openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/plaf_rfr_degrev.yaml
openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/plaf_rfr_degrev_degressif.yaml
openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/taux_sup_plaf.yaml
openfisca_france/parameters/taxation_indirecte/taxe_habitation/exon_plaf_rfr.yaml
setup.py

* Périodes concernées : 2022.
- `openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/plaf_rfr_degrev.yaml`
- `openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/plaf_rfr_degrev_degressif.yaml`
- `openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/taux_sup_plaf.yaml`
- `openfisca_france/parameters/taxation_indirecte/taxe_habitation/exon_plaf_rfr.yaml`
* Détails :
- Met à jour les taux de la taxe d'habitation pour 2022.
- - - -

Met à jour les paramètres de la taxe d'habitation

---

openfisca_france/parameters/epargne/livret_epargne_populaire.yaml

…08/2022
* Périodes concernées : à partir du 01/08/2022.
* Zones impactées : `parameters/epargne/livret_epargne_populaire.yaml`.
* Détails :
- Revalorisation du taux du livret d'épargne populaire au 1er août 2022.
- - - -

Ajoute la revalorisation du taux du livret d'épargne populaire au 01/08/2022

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/abatpen/max.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/abatpen/min.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/abatpro/max.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/abatpro/min.yaml
setup.py

* Périodes concernées : à partir du 01/01/2020 au 31/12/2022.
- `openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/abatpen/max.yaml` ;
- `openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/abatpen/min.yaml` ;
- `openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/abatpro/min.yaml` ;
- `openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/abatpro/min.yaml` ;
* Détails :
- Mise à jour des montants minimum et maximum d'abattement pour les traitements et salaires et pour les pensions (cf. #1837)
- - - -
- - - -

Ajoute les limites d'abattement sur les salaires et pensions pour 2020 et 2021

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/ensemble_des_entreprises/entreprises_de_20_salaries_et_plus.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/ensemble_des_entreprises/entreprises_de_moins_de_20_salaries.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/ensemble_des_entreprises/plafond.yaml
setup.py

* Périodes concernées : à partir du 01/01/2022
- `parameters/prelevements_sociaux/reductions_cotisations_sociales/fillon/ensemble_des_entreprises/*`
* Détails :
- Revalorise les paramètres de la réduction Fillon (`entreprises_de_20_salaries_et_plus`, `entreprises_de_moins_de_20_salaries` et `plafond`)
- - -

Revalorise les paramètres de la réduction Fillon

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prestations/aides_logement.py
openfisca_france/model/revenus/remplacement/chomage.py
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/abatpro/min2.yaml
openfisca_france/parameters/indemnite_inflation.yaml
setup.py

* Périodes concernées : à partir du 01/01/2018.
- `openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py`
- `openfisca_france/model/prestations/aides_logement.py`
- `openfisca_france/model/revenus/remplacement/chomage.py`
- `openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/abatpro/min2.yaml`
- `openfisca_france/parameters/indemnite_inflation.yaml`
* Détails :
- Améliore la prise en compte d'une réforme.
- Ne devrait pas changer de calcul.
- Met un end date à une variable (une case concrètement) qui n'existe plus.
- Corrige des formules à partir de 2018.
- Petit bug fix dans un autre fichier (met des guillemets).
- - - -
- Corrigent ou …

Met en propre la réforme de l'abattement minimum pour les chomeurs de longue durée

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/abatpen/max.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/abatpen/min.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/abatpro/max.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/abatpro/min.yaml
setup.py

* Changement mineur dans les métadonnées des paramètres
* Zones impactées : `openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/tspr/`
* Détails :
- Renomme le champ "details" dans les référence en "note".

Renomme  "details" dans les références des paramètres par "note"

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/aide_mobilite.yaml
setup.py

* Périodes concernées : à partir du 01/12/2022.
* Zones impactées : `parameters/prestations_sociales/aide_mobilite.yaml`.
* Détails :
- Revalorisation des montants (+ ~4%) de l'Aide à la mobilité suite à la [délibération n° 2022-56 du 23 novembre 2022 du conseil d'administration de Pôle emploi](https://www.bo-pole-emploi.org/bulletinsofficiels/deliberation-n-2022-56-du-23-novembre-2022-bope-n-2022-79.html?type=dossiers/2022/bope-n-2022-79-du-30-novembre-2022)
- - - -

Revalorisation des montants de l'aide à la mobilité

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/charges_deductibles.py
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/pensions_alimentaires/taux_jgt_2006.yaml
setup.py

Correction suite issue: https://github.com/openfisca/openfisca-france/issues/1954
* Périodes concernées : 2002-2006
- `model/prelevements_obligatoires/impot_revenu/charges_deductibles.py`.
-`parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/pensions_alimentaires/taux_jgt_2006`
* Détails :
- Correction de la date d'entrée en vigueur de la déduction d'impôt pour pensions alimentaires
- - - -

Correction de la date d'entrée en vigueur de la déduction d'impôt pour pensions alimentaires

---

CHANGELOG.md
openfisca_france/scripts/parameters/unfold_parameters.py
setup.py

* Zones impactées : `/openfisca_france/scripts/parameters/unfold_parameters.py`.
* Détails :
- Ajoute `encoding = 'utf-8'` par défaut dans la fonction `write_parameter`  de `unfold_parameters`
- - - -

fix encoding in unfold_parameters

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/reduction_ss_condition_revenus/majoration_plafond_par_demi_parts_supp.yaml
openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/reduction_ss_condition_revenus/plafond_rfr_celib.yaml
openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/reduction_ss_condition_revenus/plafond_rfr_couple.yaml
setup.py

* Périodes concernées : 2019.
* Zones impactées 
-`openfisca_france\parameters\impot_revenu\calcul_impot_revenu\plaf_qf\reduction_ss_condition_revenus\plafond_rfr_couple.yaml`
- `openfisca_france\parameters\impot_revenu\calcul_impot_revenu\plaf_qf\reduction_ss_condition_revenus\plafond_rfr_celib.yaml`
- `openfisca_france\parameters\impot_revenu\calcul_impot_revenu\plaf_qf\reduction_ss_condition_revenus\majoration_plafond_par_demi_parts_supp.yaml`
* Détails :
- Rajoute la valeurs des plafonds de la réduction sous condition de ressources de l'impôt sur le revenu, pour les revenus 2019.

Ajout valeur manquante dans la série pour 2019

---

openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/montant_plein.yaml
openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/montant_plein_mayotte.yaml

* Périodes concernées : à partir du 01/07/2022.
```
parameters/chomage/allocations_assurance_chomage/ass/montant_plein.yaml
parameters/chomage/allocations_assurance_chomage/ass/montant_plein_mayotte.yaml
```
* Détails :
- Mise à jour du montant de base de l'ASS (y compris Mayotte) dans le cadre de la loi n° 2022-1158 du 16 août 2022 portant mesures d'urgence pour la protection du pouvoir d'achat.
- - - -

Revalorisation de l'ASS au 01/07/2022, rattrapage au 01/04/2022

---

CHANGELOG.md
openfisca_france/model/prestations/enseignement_superieur/bourse_criteres_sociaux.py
setup.py
tests/formulas/bourses_superieur/bourse_criteres_sociaux.yaml

* Zones impactées : `openfisca_france/model/prestations/enseignement_superieur/bourse_criteres_sociaux`.
* Détails :
- Les individus en année d'étude de doctorat ne peuvent plus recevoir de bourse sur critère sociaux
- Le doctorat ne fait pas partie des diplômes concernés pour l'obention de la bourse sur critères sociaiux, cf. (source)[https://www.enseignementsup-recherche.gouv.fr/fr/bo/22/Hebdo13/ESRS2209377C.htm?cbo=1&cid_bo=160009].
- - - -
- - - -

Maj des critères d'obtention de la bourse sur critères sociaux

---

CHANGELOG.md
openfisca_france/parameters/taxation_capital/epargne/taux_inflation.yaml
setup.py

Avec #1881 j'ai cassé le calcul de l'éligibilité au livret d'épargne populaire avant la disponibilité du taux d'inflation dans les paramètres c'est à dire août 2022.
* Périodes concernées : jusqu'au 08/2022.
* Zones impactées : `parameters/taxation_capital/epargne/taux_inflation.yaml`.
* Détails :
- Ajoute un taux d'inflation par défaut à zéro pour permettre les calculs avant août 2022
- - - -
- - - -

Ajoute un taux d'inflation par défaut à zéro

---

openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1/couples.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1/famille_1pac.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1/majoration_par_pac_supp.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1/personnes_seules.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2/couples.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2/famille_1pac.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2/majoration_par_pac_supp.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2/personnes_seules.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3/couples.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3/famille_1pac.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3/majoration_par_pac_supp.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3/personnes_seules.yaml

* Périodes concernées : à partir du 01/01/2023.
- `openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1`.
- `openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2`.
- `openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3`.
* Détails :
- Mise à jour des montants de la Réduction de Loyer de Solidarité (RLS) pour 2023, d'après l'arrêté du 30/12/2022 relatif à la revalorisation des plafonds de ressources et des montants de réduction de loyer de solidarité applicables.
- - - -
- …

Revalorisation de la Réduction de Loyer de Solidarité (RLS) au 01/01/2023 pour les zones 1 à 3

---

CHANGELOG.md
openfisca_france/parameters/taxation_capital/epargne/taux_inflation.yaml
setup.py

* Périodes concernées : à partir du 01/02/2023.
* Zones impactées : `parameters/taxation_capital/epargne/taux_inflation.yaml`
* Détails :
- Revalorisation du taux du livret d'épargne populaire au 1er février 2023.
- - - -

Revalorisation taux LEP au 01/02/2023

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
setup.py

* Zones impactées : `parameters/cotsoc`.
* Détails :
- Suppression des valeurs superflues dans les `order` des cotsocs après passage dans le preprocessing.

Supprime des order superflus dans le preprocessing

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/montants.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_0bis.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_1.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_2.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_3.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_4.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_5.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_6.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_7.yaml
setup.py

* Évolution du système socio-fiscal..
* Périodes concernées : à partir du 27/07/2021
- `openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux
/montants.yaml`.
- `openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_*.yaml
* Détails :
- Revalorisation du 18 juillet 2022 fixant les plafonds et montants de ressources relatifs aux bourses d'enseignement supérieur du ministère de l'enseignement supérieur et de la recherche pour les années universitaire 2021-2022 et 2022-2023
- - - -
- - - -

Mise a jour criteres bourse criteres sociaux pour les années 2021-2022 et 2022-2023

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
setup.py

* Zones impactées : `model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py`.
* Détails :
- Corrige un CERFA field qui a malencontreusement sauté.
- - - -
- - - -
@benoit-cty @lukas-puschnig @clallemand @NolwennLoisel 
est-ce que ça vous paraît corriger ce qu'il faut corriger d'après [#1996](https://github.com/openfisca/openfisca-france/issues/1996) ?

corrige typo cerfa field

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
openfisca_france/model/revenus/activite/salarie.py
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/agricole/tode/index.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/agricole/tode/plafond.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/agricole/tode/plafond_exoneration_integrale.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/agricole/tode/seuil.yaml
setup.py
tests/formulas/exoneration_cotisations_employeur_tode.yaml
tests/formulas/maladie_mmid_employeur.yaml

- `model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py`
- `model/revenus/activite/salarie.py`
- `parameters/prelevements_sociaux/reductions_cotisations_sociales/agricole/tode`
* Détails :
- Ajoute à partir de 2019 l'exonération pour travailleur occasionnel demandeur d'emploi (TO-DE) du secteur agricole `exoneration_cotisations_employeur_tode` et la référence dans `exonerations_et_allegements`
- Ajoute des caractéristiques du salarié : `contrat_duree_determinee_type`, `taches_salarie_type` et `travailleur_occasionnel_agricole`
- Adapte `allegement_cotisation_allocations_familiales` et ajoute `allegement_cotisation_allocations_familiales_base` pour le non cumul avec …

Ajoute l'exonération TO-DE du secteur agricole

---

.github/workflows/workflow.yml

Ticket sur le Trello Aides-Jeunes : https://trello.com/c/vP3jn9tk/1200-corriger-les-warning-nodejs-12-actions-are-deprecated-de-la-ci-sur-le-d%C3%A9p%C3%B4ts-openfisca-france
Les actions utilisées dans le workflow sont en parties deprecated car utilisant nodejs 12 
> `build (ubuntu-20.04, 3.7.9, maximal)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2, actions/cache@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.`
Le passage de ces actions à leur dernière versions fix les deprecation sans casser la CI.
Actions changées
- `actions/checkout@v2` -> `actions/checkout@v3`
- `actions/setup-python@v2` -> …

Mise à jour des actions génériques utilisées dans la CI

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/montants.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_0bis.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_1.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_2.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_3.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_4.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_5.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_6.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_7.yaml
setup.py

* Évolution du système socio-fiscal : Changement mineur.
* Périodes concernées : à partir du 15/03/2023 (En attente de publication legifrance)
- `openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/*`.
- `openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/montants.yaml`.
* Détails :
- Revalorisation des plafonds et montants de la Bourse aux Critères Sociaux pour tous les échelons.
- Les données nous viennent d'une correspondance avec le CNOUS, les dates et le sources seront éditées dès publication sur Legifrance.
- - - -
- - - -
Quelques conseils à …

Revalorisation montants bourse criteres sociaux 2023-2024

---

openfisca_france/model/prestations/minima_sociaux/aah.py
openfisca_france/reforms/aah_deconjugalisee.py
tests/formulas/aah/aah_couple.yaml

* Périodes concernées : à partir du 01/09/2023.
* Zones impactées : `tests\formulas\aah\aah_couple.yaml`, `openfisca_france\model\prestations\minima_sociaux\aah.py`.
* Détails :
- Déconjugalisation des plafonds des ressources pour l'AAH
- - - -

Règle de deconjugalisation du plafond de ressources pour l'aah

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/aides_jeunes/contrat_engagement_jeune/montants/montant_majeurs_1ere_tranche_ir.yml
openfisca_france/parameters/prestations_sociales/aides_jeunes/contrat_engagement_jeune/montants/montant_majeurs_non_imposables.yml
openfisca_france/parameters/prestations_sociales/aides_jeunes/contrat_engagement_jeune/montants/montant_mineurs.yml
setup.py

* Actualisation de paramètres.
* Zones impactées : `prestations/jeunes/contrat_engagement_jeune.py`.
* Détails :
- Introduit la revalorisation de l'allocation du CEJ du 1er avril 2023.

Introduit la revalorisation CEJ du 1er avril 2023

---

CHANGELOG.md
openfisca_france/model/mesures.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
openfisca_france/model/prestations/jeunes/contrat_engagement_jeune.py
openfisca_france/model/prestations/visale.py
setup.py

* Crée une nouvelle variable intermédiaire
* Zones impactées: 
- `mesures.py`
- `prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py`
- `prestations/jeunes/cotrat_engagement_jeune.py`
- `prestations/visale.py`
* Détails :
- Crée une variable `revenus_non_salarie_nets`, plutôt que de copier-coller sa définition dans plusieurs formules.

Crée revenus non salarie nets pour simplifier

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/aefa.py
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/index.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/nb_enfants_min_pour_allocation.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/crds.yaml
openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/aefa/index.yaml
openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/aefa/montant_prime.yaml
openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/aefa/taux_majoration/index.yaml
openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/aefa/taux_majoration/tx_2p.yaml
openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/aefa/taux_majoration/tx_3pac.yaml
openfisca_france/parameters/prestations_sociales/solidarite_insertion/autre_solidarite/aefa/taux_majoration/tx_supp.yaml
setup.py
tests/formulas/aefa.yaml

* `prestations_sociales/solidarite_insertion/autre_solidarite/aefa`.
* `prestations_sociales/prestations_familiales/prestations_generales/af/crds`
* Détails : clarifie les labels des paramètres de la prime de Noël
- - - -
Ces changements modifient l'API publique d'OpenFisca France

Label reference prime noel

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/calcul_reductions_impots/pme/souscription_capital/taux.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_3.yaml
openfisca_france/parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources/echelon_4.yaml
setup.py

* `parameters/impot_revenu/calcul_reductions_impots/pme/souscription_capital/taux.yaml`
* `parameters/prestations_sociales/aides_jeunes/bourses/bourses_enseignement_superieur/criteres_sociaux/plafond_ressources`
* Détails :
- Renommage d'un last_review en last_value_still_valid_on
- Suppression de href invalides dans des références

Correction de métadonnées invalides dans parameters

---

CHANGELOG.md
openfisca_france/parameters/geopolitique/ue.yaml
setup.py

Corrige la liste des pays de l'Union Européenne : "SV" correspond au Salvador (SV/SLV), et non pas à la Slovenie (SI/SVN).
---
* Zones impactées : `openfisca_france/parameters/geopolitique/ue.yaml`.
* Détails :
- Corrige la liste des pays de l'Union Européenne : "SV" correspond au Salvador (SV/SLV), et non pas à la Slovenie (SI/SVN).
- - - -
- - - -

Corrige la liste des pays de l'Union Européene

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/abat_dom/plaf_GuadMarReu.yaml
openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/abat_dom/plaf_GuyMay.yaml
openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/abat_dom/taux_GuadMarReu.yaml
openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/abat_dom/taux_GuyMay.yaml
openfisca_france/parameters/impot_revenu/calcul_reductions_impots/dons/dons_assoc_cult.yaml
openfisca_france/parameters/impot_revenu/calcul_reductions_impots/dons/dons_coluche/plafond.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/enfant_marie/montant.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/personne_agee_ou_invalide/index.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/personne_agee_ou_invalide/montant_1.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/personne_agee_ou_invalide/montant_2.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/personne_agee_ou_invalide/plafond_1.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/personne_agee_ou_invalide/plafond_2.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/accueil_personne_agee/plafond.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/pensions_alimentaires/plafond.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/max.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/min.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/max.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/min.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/microentreprise/regime_micro_ba/plafond_recettes.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/microentreprise/regime_micro_bnc/marchandises/plafond.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/microentreprise/regime_micro_bnc/services/plafond.yaml
setup.py

* Périodes concernées : à partir du 01/01/2022
* Zones impactées : `openfisca_france/parameters/impot_revenu/`.
* Détails :
- Mets à jour certains paramètres de l'IR qui ont été revalorisés par le Décret n° 2023-422 du 31/05/2023
-  Mets à jour certains paramètres qui n'avaient pas été mis à jour pour les revenus 2021
- Ajoute de la documentation sur la règle de revalorisation automatique des paramètres lorsqu'elle existe
- - - -
Ces changements (effacez les lignes ne correspondant pas à votre cas) : 
- - - -

Maj parametres ir

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/aah.py
setup.py
tests/formulas/aah/aah.yaml

* Correction d'une erreur de calcul
* Zones impactées : `openfisca_france/model/prestations/minima_sociaux/aah.py`.
* Détails :
- Correction du calcul  de `base_ressources_aah` : pensions alimentaires versées soustraites au lieu d'être ajoutées
- Lorsque que quelqu'un paie une pension alimentaire elle est considérée comme une ressource entrante
- - - -
- - - -

Correction calcul base ressources aah : pensions alimentaires versées soustraites au lieu d'être ajoutées

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/aides_jeunes/sante_psy/etudiant/seances_max.yaml
setup.py

* Périodes concernées : à partir du 06/01/2023.
* Zones impactées : `openfisca_france/parameters/prestations_sociales/aides_jeunes/sante_psy/etudiant/seances_max.yaml`.
* Détails :
- Le dispositif santé psy étudiants passe de 6 à 8 séances.
- - - -

Met à jour le nombre de séances du dispositif Santé Psy Etudiant

---

CHANGELOG.md
openfisca_france/model/caracteristiques_socio_demographiques/capacite_travail.py
setup.py

- `/model/caracteristiques_socio_demographiques/capacite_travail.py`
* Détails :
- Ajoute unité ratio à cette variable taux d'incapacité prise en compte dans l'AAH, permet d'éviter d'entrer une valeur telle que 80 alors que la valeur doit être entre 0 et 1.

Ajoute l'unité ratio au taux d'incapacité pris en compte pour l'AAH

---

CHANGELOG.md
setup.py

* Zones impactées : toutes.
* Détails :
- Met à jour la version d'Openfisca-core en `41.0.0`

Met à jour openfisca-core en version 141.0.0

---

.github/get_minimal_version.py
.github/workflows/workflow.yml

* Zones impactées : `.github/workflows/workflow.yml`
* Détails :
- Ajoute une pipeline de build et de test à la CI pour tester le logiciel avec les version minimale des dépendances `OpenFisca-France` et `OpenFisca-Core` dans le but d'en assurer la validité.
- - - -
- - - -

CI Ajout d'un pipeline de test pour les versions minimales des dépendances OpenFisca

---

CHANGELOG.md
openfisca_france/model/prestations/jeunes/contrat_engagement_jeune.py
setup.py
tests/formulas/contrat_engagement_jeune.yaml

- `model/prestations/jeunes/contrat_engagement_jeune.py`.
- `tests/formulas/contrat_engagement_jeune.yaml`
* Détails :
Dans le cas de données d'entrée exprimant les revenus avec un RNI sur une période annuelle, le RNI était équivalent à 0 peut importe le montant.
Le calcul se fait sur une période annuelle mais là formule actuelle effectue le calcule avec une période mensuelle (un offset de 12 mois).
- - - -

Corrige calcul contrat engagement jeune

---

CHANGELOG.md
openfisca_france/model/prestations/agepi.py
openfisca_france/model/prestations/aide_mobilite.py
setup.py

- `openfisca_france/model/prestations/agepi.py`
- `openfisca_france/model/prestations/aide_mobilite.py`
- `tests/test_basics.py`
* Détails :
- La release de la version 6.1.0 ajoute de nouvelles règles de lint qui mettent en erreur notre CI.
- - - -

Corrige les nouvelles erreurs de lint du à la montée de version du linter flake8 en v6.1.0 

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/majoration_plafond_par_enfant_supplementaire.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_1.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_1_base.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_2.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_2_base.yaml
setup.py

* Zones impactées : `parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/`.
* Détails :
- Fusionne des last_review qui étaient en doublon avec des last_value_still_valid_on

Renomme des last_review en last_value_still_valid_on

---

CHANGELOG.md
openfisca_france/model/prestations/prestations_familiales/base_ressource.py
setup.py

* Correction d'une erreur de formule
* Zones impactées : `prestations/prestations_familiales/base_ressource`.
* Détails :
- La variable `prestations_familiales_base_ressources_individu` contenait les variables `glo` et `assiette_csg_plus_values`, alors que la variable `rev_coll`, utilisée dans `prestations_familiales_base_ressources_communes`, contenait `plus_values_prelevement_forfaitaire_unique_ir` et `revenu_categoriel_plus_values`. On corrige de ceci, et on met un commentaire pour expliquer le choix fait en termes de variable de plus-values.

Corrige des doubles comptes plus-values

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/rsa.py
setup.py
tests/formulas/rsa/rsa_majore.yaml
tests/mes-aides.gouv.fr/test_mes_aides_55b8811af0f7e3ac6b8f4d7a.yaml
tests/mes-aides.gouv.fr/test_mes_aides_55e6c2b70587579f04649960.yaml

* Zones impactées : [
`openfisca_france/model/prestations/minima_sociaux/rsa.py`,
`tests/formulas/rsa/rsa_majore.yaml`
]
* Détails :
- Avec l'expérience du terrain, nous constatons que le "RSA majoré pour personne isolé" n'est pas accordé pour une personne célibataire mais qui est elle-même à la charge de ses parents.
- - - -

Ajoute la condition d'indépendance fiscale dans le calcul d'eligibilite au rsa pour parent isole (`rsa_majore_eligibilite`)

---

CHANGELOG.md
openfisca_france/parameters/taxation_societes/impot_societe/index.yaml
openfisca_france/parameters/taxation_societes/impot_societe/plafond_ca_taux_reduit.yaml
openfisca_france/parameters/taxation_societes/impot_societe/seuil_superieur_benefices_taux_intermediaire.yaml
openfisca_france/parameters/taxation_societes/impot_societe/seuil_superieur_benefices_taux_reduit.yaml
openfisca_france/parameters/taxation_societes/impot_societe/taux_intermediaire.yaml
openfisca_france/parameters/taxation_societes/impot_societe/taux_reduit.yaml
openfisca_france/parameters/taxation_societes/index.yaml
setup.py

* Correction de paramètres.
* Zones impactées : `parameters/taxation_societe`.
* Détails :
- Correction de la valeur du taux réduit qui a été prolongée au-delà de la période initialement prévue.
- Pas d'impact sur les variables, car elles ne sont  affectées par ces paramètres.
- Voir aussi [Barèmes IPP](https://gitlab.com/ipp/partage-public-ipp/baremes-ipp/baremes-ipp-yaml/-/merge_requests/424).

Corrige la durée de validité du taux réduit de l'impôt sur les sociétés

---

openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/plafond_base.yaml

* Zones impactées : `openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/plafond_base.yaml`
* Détails :
- Changement du plafond de base de la css
- - - -
* Corrigent ou améliorent un calcul déjà existant.

feat(css): revalorisation plafond cmu, arrete du 2023-03-31 a effet le 2023-04-01

---

CHANGELOG.md
openfisca_france/model/mesures.py
setup.py
tests/formulas/plus_values.yaml

* Correction d'une formule.
* Zones impactées : `measures.py`.
* Détails :
- Corrige `plus_values_base_large` suite à une modification de `assiette_csg_plus_values` introduite dans la PR #2126.

Corrige plus_values_base_large

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/asi_aspa.py
setup.py

* Corrige une erreur.
* Zones impactées : `prestations/minima_sociaux/asi_aspa`.
* Détails :
- Corrige un double compte des plus-values dans la base ressources de l'ASPA et de l'ASI.

Corrige un double compte des plus-values dans ASPA et ASI

---

CHANGELOG.md
openfisca_france/model/mesures.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/csg_crds.py
openfisca_france/model/prestations/aides_logement.py
openfisca_france/model/revenus/capital/plus_value.py
openfisca_france/parameters/prelevements_sociaux/contribution_salariale_glo.yaml
openfisca_france/parameters/prelevements_sociaux/index.yaml
setup.py
tests/calculateur_impots/yaml/pv_pfu.yaml
tests/formulas/glo.yaml
tests/formulas/irpp.yaml

* Correction et complétion de la législation
- `mesures.py`
- `prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py`
- `prelevements_obligatoires/prelevements_sociaux/contributions_sociales/csg_crds.py`
- `prestations/aides_logement.py`
- `revenus/capital/plus_values.py`
* Détails :
- Ajoute les GLO taxés forfaitairement dans le revenu disponible (dans `plus_values_base_large`). Supprime ces GLO avant 2016 (car code faux).
- Ajoute ces GLO dans l'assiette CSG pour les années où ils n'y étaient pas injectés.
- Injecte dans le revenu disponible les GLO assimilés salaires et code les prélèvements associés à ces revenus. Il faut distinguer les GLO assimilés salaires …

Complète et corrige le traitement des gains de levée d'options

---

CHANGELOG.md
openfisca_france/model/prestations/depart1825.py
openfisca_france/model/prestations/enseignement_superieur/aide_merite.py
openfisca_france/model/prestations/jeunes/service_civique.py
setup.py
tests/formulas/bourses_superieur/aide_merite.yaml
tests/formulas/depart1825.yaml

- `openfisca_france/model/prestations/jeunes/service_civique.py`
- `openfisca_france/model/prestations/depart1825.py`
- `openfisca_france/model/prestations/enseignement_superieur/aide_merite.py`
- `openfisca_france/parameters/prestations_sociales/education/service_civique/`
- `tests/formulas/bourses_superieur/aide_merite.yaml`
- `tests/formulas/depart1825.yaml`
* Détails :
- Ajoute une variable pour modéliser le service civique
- Modélise le cas du service_civique dans la variable `aide_merite_eligibilite`
- Modélise le cas du service_civique dans la variable `depart1825_eligibilite`
- - - -

Ajoute la variable `service_civique`

---

CHANGELOG.md
openfisca_france/model/prestations/alimentation.py
openfisca_france/parameters/prestations_sociales/education/alimentation/montant_repas_non_boursier.yaml
setup.py
tests/formulas/crous_repas_montant.yaml
tests/formulas/crous_repas_tarif_non_boursiers_eligibilite.yaml

* Périodes concernées : à partir du 07/2021.
* Zones impactées : `openfisca_france/model/prestations/alimentation.py`.
* Détails :
- Ajoute le dispositif permettant aux étudiant du supérieur de béneficier de repas à 3,30 euros dans les restaurant du crous.
- - - -

Ajoute la variable crous_repas_montant

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/calcul_impot_revenu/recouvrement/index.yaml
openfisca_france/parameters/impot_revenu/calcul_impot_revenu/recouvrement/min.yaml
openfisca_france/parameters/impot_revenu/calcul_impot_revenu/recouvrement/seuil.yaml
setup.py

* Zones impactées : `impot_revenu/calcul_impot_revenu/recouvrement`.
* Détails :
- Change libellé en suivant celui proposé par l'Insee dans cette étude : https://www.insee.fr/fr/statistiques/3584540
- Ajoute référence législative

[IR] Libellé et référence des minimums de mise en recouvrement de l'IR

---

CHANGELOG.md
openfisca_france/model/revenus/activite/salarie.py
setup.py

* Zones impactées : `openfisca_france/model/revenus/activite/salarie.py`.
* Détails :
- Ajoute l'option `is_period_size_independent = True` à la variable effectif_entreprise
- - - -

ajout is_period_size_independent à effectif_entreprise

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/plafond_base.yaml
setup.py

* Zones impactées : `openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/plafond_base.yaml`.
* Détails :
- Changement du plafond de base de la css
- - - -

Revalorisation du plafond de ressources pour la css au 01/04/2023

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/cga_taux2.yaml
setup.py

* Périodes concernées :  à partir du 01/01/2020.
* Zones impactées : `parameters/impot_revenu/calcul_revenus_imposables/rpns/cga_taux2.yaml`.
* Détails :
- Le taux de pénalité associé à l'absence de CGA appliqué a évolué depuis 2020, et devrait être supprimé en 2023
- - - -
- - - -

Mise à jour calcul du RNI

---

CHANGELOG.md
openfisca_france/model/mesures.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py
openfisca_france/model/prelevements_obligatoires/isf.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
setup.py
tests/formulas/revenu_disponible.yaml

* Corrections/mises à jour
* Zones impactées: 
- `measures.py`
- `prelevements_obligatoires/impots_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py`
- `prelevements_obligatoires/isf.py`
- `prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py`
* Détails :
- Lors du code des variables des PEL/CEL, on n'avait pas la brochure de l'IR sur les revenus 2018, ce qui nous avait amené à coder ces variables en fonction de la nomenclature des cases de la déclaration d'IR sur les revenus 2017. Cette PR actualise cela.

Corrige/actualise variables PEL/CEL

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
openfisca_france/model/revenus/autres.py
setup.py

* Corrections/mises à jour.
- `openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py`
- `openfisca_france/model/revenus/autres.py`
* Détails :
- Ajoute des end-date pour certains crédits d'impôt qui n'existent plus et donc les cases CERFA on été réutilisée depuis
- Corrige la case cerfa de la variable `f8ti`
- Corrigent ou améliorent un calcul déjà existant

Ajoute des end dates pour certains crédits d'impôts

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/prestations_familiales/bmaf/index.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aeeh/cpl3b.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aeeh/cpl3c.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aeeh/cpl4b.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aeeh/cpl4c.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aeeh/cpl4d.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aeeh/cpl5a.yaml
setup.py

-  `parameters/prestations_sociales/prestations_familiales`
* Détails :
- Retrait de paramètres inutilisés

Nettoie paramètres inutilisés

---

.github/workflows/workflow.yml
CHANGELOG.md
setup.py

* Périodes concernées : non applicable.
* Zones impactées : `.github/workflows/workflow.yml`.
* Détails :
- Améliore la récupération d'[artifacts](https://docs.github.com/fr/actions/using-workflows/storing-workflow-data-as-artifacts) en intégration continue pour le `build` de librairie conda
-  Permet de trouver le paquet même si le merge de la PR est fait sans avoir réalisé de commit après son ouverture.
Cette PR répond à une problématique sur la publication de librairies conda : lorsque tous les évènements de commits sont réalisés avant l'événement d'ouverture de PR, la librairie n'était pas trouvée. Avec cette PR la librairie conda est bien retrouvée.
- - - -
- Modifient des éléments non …

Améliore la récupération de l'artifact conda

---

CHANGELOG.md
openfisca_france/model/prestations/jeunes/pass_sport.py
openfisca_france/parameters/prestations_sociales/education/pass_sport/critere_age/age_maximum_profil_aah.yaml
openfisca_france/parameters/prestations_sociales/education/pass_sport/critere_age/age_maximum_profil_aeeh.yaml
openfisca_france/parameters/prestations_sociales/education/pass_sport/critere_age/age_maximum_profil_ars.yaml
openfisca_france/parameters/prestations_sociales/education/pass_sport/critere_age/age_maximum_profil_boursier.yaml
openfisca_france/parameters/prestations_sociales/education/pass_sport/critere_age/age_minimum_profil_aah.yaml
openfisca_france/parameters/prestations_sociales/education/pass_sport/critere_age/age_minimum_profil_aeeh.yaml
openfisca_france/parameters/prestations_sociales/education/pass_sport/critere_age/age_minimum_profil_ars.yaml
openfisca_france/parameters/prestations_sociales/education/pass_sport/critere_age/index.yaml
openfisca_france/parameters/prestations_sociales/education/pass_sport/index.yaml
openfisca_france/parameters/prestations_sociales/education/pass_sport/montant.yaml
setup.py
tests/formulas/pass_sport.yaml

* Périodes concernées : à partir du 2022/08/02.
- `openfisca_france/model/prestations/jeunes/pass_sport.py`
- `openfisca_france/parameters/prestations_sociales/education/pass_sport/*`
* Détails :
- Ajoute le dispositif du Pass'Sport, dispositif de réduction des frais d'inscription à un club sportif.
- - - -

Ajoute le Pass'Sport

---

.github/workflows/workflow.yml
CHANGELOG.md
setup.py

* Périodes concernées : non applicable.
* Zones impactées : `.github/workflows/workflow.yml`.
* Détails :
- La récupération d'[artifacts](https://docs.github.com/fr/actions/using-workflows/storing-workflow-data-as-artifacts) en intégration continue pour le `build` de librairie conda dans https://github.com/openfisca/openfisca-france/pull/2211 ne fonctionne malheureusement pas.
-  Cette PR reconstruit le parquet sur la branche `master` avant de l'envoyer sur `conda`.
- - - -
- - - -

Rebuild conda on master

---

.github/workflows/workflow.yml
CHANGELOG.md
setup.py

Amélioration technique.
* Zones impactées : `.github/workflows/workflow.yml`.
* Détails :
- Modifie l'authentification à Pypi pour se connecter via un token
- - - -

Modifie la manière de s'authentifier à Pypi pour la publication de paquets

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/pss/plafond_securite_sociale_annuel.yaml
openfisca_france/parameters/prelevements_sociaux/pss/plafond_securite_sociale_horaire.yaml
openfisca_france/parameters/prelevements_sociaux/pss/plafond_securite_sociale_mensuel.yaml
setup.py

* Périodes concernées : à partir du 01/01/2024
* Zones impactées : `openfisca_france/parameters/prelevements_sociaux/pss`.
* Détails :
- Met à jour les montant du plafond de la sécurité sociale pour 2024
- - - -

Met à jour PSS pour 2024

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/montant_maximum_annuel/couples.yaml
openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/montant_maximum_annuel/personnes_seules.yaml
openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/plafond_ressources/couples.yaml
openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/plafond_ressources/personnes_seules.yaml
setup.py

* Périodes concernées : à partir du 01/01/2024.
* Zones impactées : `openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa`.
* Détails :
- Met à jour les montant de l'aspa à partir du 01/01/2024
- - - -

Met à jour les montants d'aspa pour 2024

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/deductible/taux_median.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/deductible/taux_plein.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/deductible/taux_reduit.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/imposable/taux_median.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/imposable/taux_plein.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/imposable/taux_reduit.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/taux_median.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/taux_plein.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/taux_reduit.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/seuils/seuil_rfr1/demi_part_suppl_rfr1.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/seuils/seuil_rfr1/seuil_rfr1.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/seuils/seuil_rfr2/demi_part_suppl_rfr2.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/seuils/seuil_rfr2/seuil_rfr2.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/seuils/seuil_rfr3/demi_part_suppl_rfr3.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/seuils/seuil_rfr3/seuil_rfr3.yaml
setup.py

* Périodes concernées : à partir du 01/01/2024
* Zones impactées : `openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/`.
* Détails :
- Met à jour les seuils de rfr pour le calcul de la csg sur les retraites à partir de 2024
- - - -

Mets à jour les seuils de rfr pour la csg retraite pour 2024

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/maj_age_deux_enfants/taux1.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/maj_age_deux_enfants/taux2.yaml
setup.py

*  Changement mineur.
- `openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/maj_age_deux_enfants/taux1.yaml`.
- `openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/maj_age_deux_enfants/taux2.yaml`.
* Détails :
- Corrige deux changements d'unités ajouter par erreur dans la PR #2235
- - - -

FIx 2 unit: pourcentage_de_bmaf en BMAF

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prelevements_obligatoires/isf.py
openfisca_france/model/revenus/activite/non_salarie.py
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/cga_taux2.yaml
setup.py
tests/calculateur_impots/yaml/regime_benef_reel_BIC_location_avec_cga.yaml

* Périodes concernées :  à partir du 01/01/2023.
* Zones impactées : `model/prelevements_obligatoires/impot_revenu/ir`.
* Détails :
- La pénalité pour absence de CGA pour les revenus non-salariaux prend fin en 2023. Le taux associé prend donc fin, et de nombreuses formules sont reformulées dans une version 2023 un peu allégée. De nombreuses cases fiscales sont supprimées en conséquence.
- Renomme `nacc_defs`, qui n'était pas un déficit et dont le nom portait donc à confusion, en  `nacc_imps`.
- - - -
- Corrigent ou …

Suppression CGA 2023

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/aah.py
openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/majoration_plafond/majoration_plafond_couple.yaml
setup.py
tests/formulas/aah/aah.yaml
tests/formulas/aah/aah_couple.yaml
tests/formulas/aah/aah_famille.yaml

* Périodes concernées : à partir du 01/10/2023.
* Zones impactées : `prestations_sociales/prestations_etat_de_sante/invalidite/aah/majoration_plafond`
- `model/prestations/minima sociaux/aah`
* Détails :
- La déconjugalisation de l'aah ne prenait pas encore en compte la déconjugalisation du plafond
- Ajout de l'option de conjugalisation après octobre 2023. Renomme en conséquence `aah_base_ressource `et `aah `selon leur statut de conjugalisation. 
- - - -
- - - -

Corrige déconjugalisation du aah_plafond_ressource + test

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/rsa.py
setup.py

* Zones impactées : `model/prestations/minima sociaux/rsa`.
* Détails :
- La base ressources du RSA comprenait l'ASS du mois de référence, et pas de la moyenne des trois mois précédents. Or, selon la caf (voir [#2257](https://github.com/openfisca/openfisca-france/issues/2257)), le calcul est bien effectué comme pour l'aah par exemple, sur cette moyenne. 
- - - -
- - - -

ASS pour RSA dépendant des mois précédents

---

CHANGELOG.md
openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/plaf_coup.yaml
openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/plaf_seul.yaml
setup.py

- `openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/plaf_seul.yaml`
- `openfisca_france/parameters/chomage/allocations_assurance_chomage/ass/plaf_coup.yaml`
* Détails :
- Supprime l'unité "/1" pour deux paramètres qui n'était pas des taux
- - - -

fix unit parametres ASS

---

CHANGELOG.md
openfisca_france/model/revenus/activite/salarie.py
setup.py

Cette prime s'est terminée le 31 décembre 2023, seule la version non exceptionnelle persiste
* Périodes concernées : à partir du 31/12/2023.
* Zones impactées : `openfisca_france/model/revenus/activite/salarie.py`.
* Détails : Ajoute end date dans les formules

Ajoute date de fin prime exceptionnelle pouvoir d'achat

---

CHANGELOG.md
openfisca_france/model/prestations/jeunes/pass_sport.py
setup.py
tests/formulas/pass_sport.yaml

* Zones impactées : `openfisca_france/model/prestations/jeunes/pass_sport`.
* Détails :
- Corrige le calcul du montant de l'aide Pass Sport pour les bénéficiaires de l'aah
- - - -
- - - -

Corrige le montant du pass sport pour les bénéficiaires de l'aah

---

CHANGELOG.md
openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taxes_specifiques/montants_apres_2015/autres_tabacs_a_chauffer.yaml
openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taxes_specifiques/montants_apres_2015/tabac_rouler.yaml
openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taxes_specifiques/montants_apres_2015/tabacs_batonnets.yaml
setup.py

* Périodes concernées : aucune.
* /parameters/taxation_indirecte/taxes_tabacs/taxes_specifiques/montants_apres_2015/autres_tabacs_a_chauffer.yaml
* /parameters/taxation_indirecte/taxes_tabacs/taxes_specifiques/montants_apres_2015/tabac_rouler.yaml
* /parameters/taxation_indirecte/taxes_tabacs/taxes_specifiques/montants_apres_2015/tabacs_batonnets.yaml
* Détails :
- Mise à jour des `last_value_still_valid_on` sur les paramètres de l'impôt sur le revenu après vérification automatique de la validité de l'article en référence.
- - - -
- - - -
Méthodologie :
1. Récupére les paramètres …

Mise à jour des last_value_still_valid_on pour la taxation indirecte

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatviag/index.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatviag/taux1.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatviag/taux2.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatviag/taux3.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatviag/taux4.yaml
setup.py

- `openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatviag/*`
* Détails :
- Met à jour la description
- Ajoute une référence, le `short_label` et `last_value_still_valid_on`

Mise à jour des paramètres d'imposition des rentes viagères

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie.py
setup.py

* Périodes concernées : à partir du 01/01/2020
* Zones impactées : `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie.py`.
* Détails :
- Corrige une division par zero dans la formule de `maladie_maternite_artisan_commercant_taux`
- - - -

fix divide by zero

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/taux_salaires_pensions.yaml
setup.py

- `openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/taux_salaires_pensions.yaml`
* Détails :
- Ajoute une référence et le `last_value_still_valid_on`

Ajout d'une référence pour l'abattement pour frais professionnels

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/credits_impots/assloy/taux.yaml
setup.py
tests/calculateur_impots/yaml/credit_assloy.yaml

* Périodes concernées : A partir de 2017-01-01.
* Zones impactées : `openfisca_france/parameters/impot_revenu/credits_impots/assloy/taux.yaml`.
* Détails :
- Neutralise le crédit impôt pour assurance loyer impayé qui n'existe plus depuis la LF 2017.
- - - -

Neutralise crédit impôt pour assurance loyer impayé `assloy`

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique.py
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/indemnite_compensatrice_fonctionnaires/index.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/indemnite_compensatrice_fonctionnaires/taux.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/exonerations_geographiques_cotis/index.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/exonerations_geographiques_cotis/zrd/index.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/exonerations_geographiques_cotis/zrd/plafond_exoneration_integrale_part_remuneration.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/exonerations_geographiques_cotis/zrd/plafond_part_remuneration.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/exonerations_geographiques_cotis/zrr/index.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/exonerations_geographiques_cotis/zrr/plafond_exoneration_integrale_part_remuneration.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/exonerations_geographiques_cotis/zrr/plafond_part_remuneration.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/jei/index.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/jei/plafond_part_remuneration.yaml
setup.py

* Évolution du système socio-fiscal. | Amélioration technique.
* Périodes concernées : à partir du 01/01/2011.
* Modification formules dans `prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py`.
* Modification formules dans `prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique.py`
* Création d'un nouveau dossier de paramètre dans `prelevements_sociaux/contributions_sociales/csg/activite` pour l'`indemnite_compensatrice_fonctionnaires`
* Création d'un nouveau dossier de paramètre dans `prelevements_sociaux/reductions_cotisations_sociales` pour les `exonerations_geographiques_cotis` et `jei`
* Détails : Retire une partie des paramètres en dur de l'indémnité compensatrice CSG, de l'exonération JEI, …

Enlève des paramètres en dur dans certaines formules

---

CHANGELOG.md
openfisca_france/model/revenus/activite/salarie.py
setup.py

* Changement mineur : Modification d'un label
* Zones impactées : `openfisca_france/model/revenus/activite/salarie.py`.
* Détails : La variable `contrat_de_travail` et la variable `contrat_de_travail_type` ont le même label, pourtant elles ne représentent pas la même chose. La première concerne les types de durées de travail du contrat (Temps plein, partiel, convention, etc.) ; la seconde, le type de contrat (CDD,CDI). Cette PR change le label de la première et propose de parler de "Type de durée de travail" pour les distinguer.
[Service-Public.fr](https://www.service-public.fr/particuliers/vosdroits/F19261) en parle aussi sous cette forme.
- - - -
- Modifient des éléments non …

Renomme label contrat de travail

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/bareme_ir_depuis_1945/bareme.yaml
setup.py

* Évolution du système socio-fiscal changement mineur.
* Périodes concernées :  01/01/2023.
* Zones impactées : `openfisca_france/parameters/impot_revenu/bareme_ir_depuis_1945/bareme.yaml`.
* Détails : Ajoute référence 2024 article codifié impôt sur le revenu

Ajoute référence 2024 article codifié impôt sur le revenu

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/alleg_gen/mmid/plafond_smic_2023_12_31.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/alleg_gen/mmid/plafond_smic_courant.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/allegement_cotisation_allocations_familiales/plafond_smic_2023_12_31.yaml
openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/allegement_cotisation_allocations_familiales/plafond_smic_courant.yaml
setup.py
tests/formulas/allegement_cotisation_allocations_familiales.yaml
tests/formulas/allegement_cotisation_maladie.yaml

* Périodes concernées : à partir du 01/01/2024
* Zones impactées : `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py`
* Détails :
- Correction du calcul introduit de la version 168.1.0 : la variable `coefficient_de_proratisation` ne doit pas être appelée en décembre 2023 mais au moment du calcul
- Cette modification a entraîné des modifications de calcul car la variable `coefficient_de_proratisation` ne peut être calculée que pour un mois 
- - - -

Fix calcul allegements

---

CHANGELOG.md
openfisca_france/model/caracteristiques_socio_demographiques/logement.py
openfisca_france/model/prestations/minima_sociaux/ppa.py
openfisca_france/model/prestations/minima_sociaux/rsa.py
setup.py
tests/formulas/ppa/ppa.yaml
tests/formulas/rsa.yaml

* Évolution du système socio-fiscal. | Correction d'un crash.
* Périodes concernées :  à partir du 01/10/2024.
* Zones impactées : `model/prestations/minima_sociaux/ppa`.
* Détails :
- Une expérimentation sur le pré-remplissage des revenus pour calculer la prime d'activité et le RSA n'était pas limitée aux départments concernés dans https://github.com/openfisca/openfisca-france/pull/2337/files.
- - - -
- - - -

Limite expérimentation à départements associés

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ppa.py
setup.py
tests/formulas/ppa/ppa.yaml

Prise en compte des statuts apprenti stagiaire dans le calcul de l'eligibilite a la prime d'activite
* Zones impactées : `openfisca_france/model/prestations/minima_sociaux/ppa.py`.
* Détails :
Selon ces articles:
- https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031087615
- https://www.service-public.fr/particuliers/vosdroits/F33375
Les apprenants (etudiants, apprentis et stagiaires) ne sont éligibles à la prime d'activité que s'ils ont des revenus professionnels qui dépassent un seuil. Cet aspect était bien pris en compte pour les étudiants, mais non pour les apprentis et les stagiaires.
Cette PR ajoute juste la prise en compte de ce seuil pour les apprentis et les stagiaires.
- - - -
Ces changements (effacez les lignes …

Prise en compte des statuts apprenti et des stagiaire dans calcul de l'éligibilité à la PPA

---

CHANGELOG.md
openfisca_france/model/prestations/minima_sociaux/ppa.py
pyproject.toml
tests/formulas/ppa/ppa.yaml

Prise en compte des statuts apprenti stagiaire dans le calcul de l'eligibilite a la prime d'activite
Correction d'un crash
Périodes concernées : toutes.
Zones impactées : openfisca_france/model/prestations/minima_sociaux/ppa.py.
Détails :
Selon ces articles:
- https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031087615
- https://www.service-public.fr/particuliers/vosdroits/F33375
Les apprenants (etudiants, apprentis et stagiaires) ne sont éligibles à la prime d'activité que s'ils ont des revenus professionnels qui dépassent un seuil. Cet aspect était bien pris en compte pour les étudiants, mais non pour les apprentis et les stagiaires.
Cette PR ajoute juste la prise en compte de ce seuil pour les apprentis et les stagiaires.
- - - -
Ces changements (effacez les lignes ne …

Prise en compte des statuts apprenti et stagiaire dans le calcul de l'éligibilité à la PPA

---

CHANGELOG.md
openfisca_france/parameters/marche_travail/salaire_minimum/smic/smic_b_horaire.yaml
openfisca_france/parameters/marche_travail/salaire_minimum/smic/smic_b_mensuel.yaml
pyproject.toml

* Périodes concernées : à partir du 01/11/2024.
* Zones impactées : `openfisca_france/parameters/marche_travail/salaire_minimum/smic`.
* Détails :
- Met à jour les montants du smic horaire et mensuel à partir de novembre 2024
- - - -

met à jour smic

---

.conda/recipe.yaml
.github/workflows/workflow.yml
CHANGELOG.md
openfisca_france/scripts/check_path_length.py
pyproject.toml

* Périodes concernées : aucune.
* Zones impactées : `workflow.yml`.
* Détails :
- La publication conda ne fonctionnait plus suite au passage à `pyproject.toml` : `C:\hostedtoolcache\windows\Python\3.9.13\x64\python3.exe: can't open file 'D:\a\openfisca-france\openfisca-france\setup.py': [Errno 2] No such file or directory`
- - - -
Fait suite à https://github.com/openfisca/openfisca-france/pull/2369 dans laquelle il y avait des manques sur Conda. La CI a donc été mise à jour pour refléter https://github.com/openfisca/country-template/pull/157
- Passage de `build-conda-${{ hashFiles('.conda/recipe.yaml') }}-${{ github.sha }}` à `build-conda-${{ hashFiles('pyproject.toml') }}-${{ github.sha }}` car …

Fix conda upload

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
pyproject.toml
tests/formulas/temps_partiel/renonciation_ajustement_pss.yaml

Suite de la PR 2373.
* Périodes concernées : à partir du 01/09/2023
* Zones impactées : `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py`.
* Détails :
- Ajout d'une variable booléenne permettant d'indiquer l'option de renonciation à l'ajustement du PSS prévue par la loi pour un salarié à temps partiel
- Fixation du maximum en sortie de la formule d'ajustement, qui ne peut pas dépasser la valeur légale du PSS
- - - -
- - - -

Modifications mineures du calcul d'ajustement PSS

---

.github/workflows/workflow.yml
CHANGELOG.md
pyproject.toml

* Zones impactées : `.github/workflows/workflow.yml`.
* Détails :
- Contournement d'une erreur qui empêchait la CI Conda de fonctionner.
- - - -
_edit @sandcha_ : 
Corrige [test-conda](https://github.com/openfisca/openfisca-france/actions/runs/11680517825/job/32523881244?pr=2377) détecté sur https://github.com/openfisca/openfisca-france/pull/2377 (alors que l'erreur n'est pas survenue sur la branche `master` 🤔) ; la première lettre 'c' semble avoir été supprimée : 
```shell
> Install package
Run mamba install --channel file:///${RUNNER_TEMP//\\//}/conda-bld --channel openfisca openfisca-france
mamba install --channel file:///${RUNNER_TEMP//\\//}/conda-bld --channel openfisca openfisca-france
shell: C:\Program Files\Git\bin\bash.EXE …
```

Fix CI `test-conda` qui ne fonctionnait plus

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/credits_impot.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py
openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/couple_ou_pers_a_charge/index.yaml
openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/index.yaml
openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/sans_pers_a_charge/index.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rvcm/produits_assurances_vies_assimiles/abattement_celib.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rvcm/produits_assurances_vies_assimiles/abattement_couple.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rvcm/produits_assurances_vies_assimiles/index.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rvcm/revenus_capitaux_mobiliers_dividendes/abattement_forfaitaire.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rvcm/revenus_capitaux_mobiliers_dividendes/index.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rvcm/revenus_capitaux_mobiliers_dividendes/taux_abattement.yaml
pyproject.toml

* Périodes concernées :  à partir de 1978.
* `impot_revenu/credits_impot.py`
* `impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py`
* `impot_revenu/ir.py`
* `impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/couple_ou_pers_a_charge/index.yaml`
* `impot_revenu/calcul_revenus_imposables/rvcm/produits_assurances_vies_assimiles`
* Détails :
- Crée un nouveau paramètre spécifique pour l'abattement des couples pour produit d'assurance vie dans le calcul des revenus imposables à l'IR
- Modifie les formules en conséquence (qui utilisaient l'abattement pour célibataire en le multipliant par 2)

Impôt sur le revenu : ajoute le paramètre couple manquant pour l'abattement d'assurance-vie

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot_plafonnees.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py
openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/pme/index.yaml
openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/pme/souscription_capital/index.yaml
openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/pme/souscription_capital/seuil.yaml
openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/pme/souscription_capital/seuil_tpe.yaml
openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/pme/souscription_capital/taux.yaml
openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/pme/souscription_capital/taux18.yaml
openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/pme/souscription_capital/taux22.yaml
openfisca_france/parameters/impot_revenu/calcul_reductions_impots/souscriptions/pme/souscription_capital/taux25.yaml
pyproject.toml

* Évolution intermédiaire du système socio-fiscal.
* `model/prelevements_obligatoires/impot_revenu/reductions_impot_plafonnees.py`,
* `parameters/impot_revenu/calcul_reductions_impots/souscriptions`,
* `model/prelevements_obligatoires/impot_revenu/variables_reductions_credits.py`,
* `parameters/impot_revenu/calcul_impot_revenu/pv/bspce/taux_moins_3_ans.yaml`,
* Détails :  Réorganisation du dossier concernant la réduction Madelin IR-PME des versements pour souscription au capital des PME.
- Ajoute label et références
- Utilise dans les formules les derniers paramètres plus génériques
- Met à jour la variable de la case 7CQ qui change d'objet à partir de 2012

Paramètre réduction souscription capital PME

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot_plafonnees.py
pyproject.toml

* Périodes concernées : à partir du 31/12/2023.
* Zones impactées : `model/prelevements_obligatoires/impot_revenu/reductions_impot_plafonnees.py`.
* Détails :
- Met fin à la réduction d'impôt sur la réhabilitation de résidences de tourisme, abrogée en 2023 ([Article 199 decies G bis](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033781921/))
- - - -
- - - -

Met fin à la réduction d'impôt sur la réhabilitation de résidences de tourisme

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
pyproject.toml

* Zones impactées : `openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py`.
* Détails :
- La formule de calcul de l'impôt restant à payer contient des termes à zéro qui peuvent être supprimés sans modifier le résultat (simplification de la formule)
- - - -
- - - -

Simplifie la formule de l'impôt sur le revenu restant à payer

---

openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py

Test de formule à partir de la branche clarification-formule-ir

Proposition avec création d'une formule minimum_recouvrement_ir

---

.github/workflows/workflow.yml
CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py
pyproject.toml
tests/calculateur_impots/yaml/pv_pfu.yaml
tests/calculateur_impots/yaml/rvcm.yaml
tests/formulas/irpp_prets_participatifs.yaml
tests/formulas/revenu_disponible.yaml
tests/formulas/taxation_capital.yaml
tests/impot_revenu/pfu_bareme.yaml

* Amélioration technique et métier de la formule de l'impôt sur le revenu restant à payer
- `openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py`.
- `openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py`.
- `tests/calculateur_impots/yaml/pv_pfu.yaml`.
- `tests/calculateur_impots/yaml/rvcm.yaml`.
- `tests/formulas/irpp_prets_participatifs.yaml`.
- `tests/formulas/revenu_disponible.yaml`.
- `tests/formulas/taxation_capital.yaml`.
- `tests/impot_revenu/pfu_bareme.yaml`.
* Détails :
- Améliore la lisibilité de la formule de l'impôt sur le revenu
- Objectif : séparer de la formule `impot_revenu_restant_a_payer` les complexités inhérentes au seuils de mise …

Simplification de la formule de l'impôt sur le revenu

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/pss/plafond_securite_sociale_annuel.yaml
openfisca_france/parameters/prelevements_sociaux/pss/plafond_securite_sociale_mensuel.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/ars/ars_plaf/plafond_ressources.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel/biactifs_parents_isoles.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel/plafond_ressources_0_enfant.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_plein/biactifs_parents_isoles.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_plein/plafond_ressources_0_enfant.yaml
pyproject.toml

* Périodes concernées :  à partir du 01/01/2025.
- `openfisca_france/parameters/prelevements_sociaux/pss`
- `openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/ars/ars_plaf`
- `openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel`
- `openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_plein`
* Détails :
- Met à jour les paramètres revalorisés au premier janvier 2025
- - - - …

Met à jour les paramètres revalorisés le 1e janvier 2025

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/seuils/seuil_rfr1/demi_part_suppl_rfr1.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/seuils/seuil_rfr1/seuil_rfr1.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/seuils/seuil_rfr2/demi_part_suppl_rfr2.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/seuils/seuil_rfr2/seuil_rfr2.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/seuils/seuil_rfr3/demi_part_suppl_rfr3.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/seuils/seuil_rfr3/seuil_rfr3.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux1pac.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux2pac.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux3pac.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux4pac.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux5pac.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux6pac.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux_couple.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux_pac_supp.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0/taux_seul.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/ressources/dar_11.yaml
openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/ressources/dar_4.yaml
pyproject.toml

* Périodes concernées : à partir du 01/01/2025
- `openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/ressources`.
- `openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0`
- `openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/seuils`
* Détails :
- Mets à jour les paramètres qui ont évolué au premier janvier 2025
- - - -

Revalorisation janvier suite

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
pyproject.toml

* Périodes concernées : à partir du 01/01/2020.
* Zones impactées : `openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py`.
* Détails :
- Enlève de la formule de l'IR net la réfaction foyers modestes (reduction_ss_condition_revenus) à partir de son abrogation en 2020

Simplifie la formule de l'impôt sur le revenu net suite à l'abrogation de la "réfaction foyers modestes"

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
pyproject.toml

* Zones impactées : `openfisca_france/model/prestations/aides_logement.py`.
* Détails :
- Supprime une condition de non cumul des aides au logement qui est redondante par rapport aux conditions dans les variables en amont
- - - -

supprime condition inutile

---

CHANGELOG.md
openfisca_france/parameters/taxation_societes/impot_societe/seuil_superieur_benefices_taux_reduit.yaml
openfisca_france/parameters/taxation_societes/impot_societe/taux_normal.yaml
pyproject.toml

* openfisca_france/parameters/taxation_societes/impot_societe/seuil_superieur_benefices_taux_reduit.yaml
* openfisca_france/parameters/taxation_societes/impot_societe/seuil_superieur_benefices_taux_reduit.yaml
* Détails :
- Mise à jour des `last_value_still_valid_on`, des valeurs et des références sur les paramètres qui n'étaient plus à jour et dont la nouvelle valeur a pu être trouvé avec un bon niveau de fiabilité.
- - - -
- - - -
Méthodologie :
1. Récupére les paramètres OpenFisca depuis [leximpact-socio-fiscal-openfisca-json](https://git.leximpact.dev/leximpact/leximpact-socio-fiscal-openfisca-json/-/raw/master/raw_pr …

MAJ `last_value_still_valid_on` pour les taxation_societes

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/modulation/taux_tranche_1.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/modulation/taux_tranche_2.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/modulation/taux_tranche_3.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/majoration_enfants/allocation_forfaitaire/taux.yaml
pyproject.toml

* Périodes concernées : à partir du 10/02/2025.
* Zones impactées : `openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/modulation`.
* Détails :
- Met à jour la last value des modulateurs allocations familiales
- - - -
- - - -

Met à jour la last value des modulateurs allocations familiales

---

CHANGELOG.md
openfisca_france/model/prestations/prestations_familiales/af.py
pyproject.toml

* Zones impactées : `openfisca_france/model/prestations/prestations_familiales/af.py`.
* Détails :
- Ajoute un calculate_output à crds_af
- - - -

Ajoute un calculate_output à crds_af

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/indemnites_journalieres/deductible/taux.yaml
openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/indemnites_journalieres/taux_global.yaml
pyproject.toml

- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/indemnites_journalieres/deductible/taux.yaml
- openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/indemnites_journalieres/taux_global.yaml
* Détails :
- Mise à jour des `last_value_still_valid_on`, des valeurs et des références sur les paramètres qui n'étaient plus à jour et dont la nouvelle valeur a pu être trouvée avec un bon niveau de fiabilité.
- - - -
- - - -
Méthodologie :
1. Récupére les paramètres OpenFisca depuis [leximpact-socio-fiscal-openfisca-json](https://git.leximpact.dev/leximpac …

MAJ contributions_sociales

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/majoration_plafond/majoration_par_enfant_supplementaire.yaml
openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/caah/majoration_vie_autonome.yaml
pyproject.toml

- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/caah/majoration_vie_autonome.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/majoration_plafond/majoration_par_enfant_supplementaire.yaml
* Détails :
- Mise à jour des `last_value_still_valid_on`, des valeurs et des références sur les paramètres qui n'étaient plus à jour et dont la nouvelle valeur a pu être trouvé avec un bon niveau de fiabilité.
- - - -
- - - -
Méthodologie :
1. Récupére les paramètres OpenFisca depuis [leximpact-socio-fiscal-openfisca-json](https://git.leximpact.dev/le …

MAJ prestations_etat_de_sante

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/forfait_social/taux_reduit_1.yaml
pyproject.toml

- openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/forfait_social/taux_reduit_1.yaml
* Détails :
- Mise à jour des `last_value_still_valid_on`, des valeurs et des références sur les paramètres qui n'étaient plus à jour et dont la nouvelle valeur a pu être trouvé avec un bon niveau de fiabilité.
- - - -
- - - -
Méthodologie :
1. Récupére les paramètres OpenFisca depuis [leximpact-socio-fiscal-openfisca-json](https://git.leximpact.dev/leximpact/leximpact-socio-fiscal-openfisca-json/-/raw/master/raw_processed_parameters.json?ref_type=heads) et les exportent dans un …

MAJ last_value_still_valid_on contributions_assises_specifiquement_accessoires_salaire

---

CHANGELOG.md
openfisca_france/parameters/chomage/allocations_assurance_chomage/alloc_base_taux/pourcentage_sjr.yaml
openfisca_france/parameters/chomage/allocations_assurance_chomage/complement_are/taux_remuneration_retenue.yaml
pyproject.toml

- openfisca_france/parameters/chomage/allocations_assurance_chomage/complement_are/taux_remuneration_retenue.yaml
- openfisca_france/parameters/chomage/allocations_assurance_chomage/alloc_base_taux/pourcentage_sjr.yaml
* Détails :
- Mise à jour des `last_value_still_valid_on`, des valeurs et des références sur les paramètres qui n'étaient plus à jour et dont la nouvelle valeur a pu être trouvé avec un bon niveau de fiabilité.
- - - -
- - - -
Méthodologie :
1. Récupére les paramètres OpenFisca depuis [leximpact-socio-fiscal-openfisca-json](https://git.leximpact.dev/leximpact/leximpact-socio-fiscal-openfisca-json/-/raw/mast …

MAJ des last_value_still_valid_on de chomage.allocations_assurance_chomage

---

CHANGELOG.md
openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/decote/parametre_calcul_decote.yaml
openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/forfait_mobilier/majoration_forfaitaire.yaml
openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/forfait_mobilier/non_bati/seuil.yaml
openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/forfait_mobilier/non_bati/taux_biens_ruraux.yaml
openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/forfait_mobilier/non_bati/taux_bois_forets.yaml
openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/reduc_impot/reduction_dons_certains_organismes_interet_general/limite_reduction.yaml
openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/reduc_impot/reduction_dons_certains_organismes_interet_general/taux.yaml
pyproject.toml

- openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/reduc_impot/reduction_dons_certains_organismes_interet_general/taux.yaml
- openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/reduc_impot/reduction_dons_certains_organismes_interet_general/limite_reduction.yaml
- openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/forfait_mobilier/non_bati/seuil.yaml
- openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/forfait_mobilier/majoration_forfaitaire.yaml
- openfisca_france/parameters/taxation_capital/impot_fortune_immobiliere_ifi_partir_2018/forfait_mobilier/non_bati/taux_bois_forets.y …

MAJ des `last_value_still_valid_on` de l'IFI

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/age1.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/age2.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/facteur_garde_alternee.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/modulation/taux_tranche_2.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/modulation/taux_tranche_3.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/nb_enfants_min_pour_allocation.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/taux/enf2.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/maj_age_deux_enfants/age1.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/maj_age_deux_enfants/taux1.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/majoration_enfants/allocation_forfaitaire/nb_enfants_min.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/majoration_enfants/allocation_forfaitaire/taux.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/allocations_familiales_un_enfant.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/majoration_premier_enfant/taux_tranche_1.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/majoration_premier_enfant/taux_tranche_2.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/tranches_age/age_debut_deuxieme_tranche.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/tranches_age/age_debut_premiere_tranche.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_cm/age_max.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_cm/age_min.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_cm/complement_familial/taux_cf_base.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_cm/complement_familial/taux_cf_majore.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/deux_premiers_enf.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/troisieme_enf_et_plus.yaml
pyproject.toml

- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/age2.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/facteur_garde_alternee.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/nb_enfants_min_pour_allocation.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/taux/enf2.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/taux/enf3.yaml
- openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/a …

MAJ last_value_still_valid_on prestations familialles

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/accueil_personne_agee/plafond.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/pensions_alimentaires/plafond.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/max.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/min.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/taux.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/max.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/min.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/taux.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatviag/taux1.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatviag/taux2.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatviag/taux3.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatviag/taux4.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/microentreprise/regime_micro_ba/plafond_recettes.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/microentreprise/regime_micro_ba/taux.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rvcm/majoration_revenus_reputes_distribues.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rvcm/produits_assurances_vies_assimiles/abattement_celib.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rvcm/produits_assurances_vies_assimiles/abattement_couple.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rvcm/revenus_capitaux_mobiliers_dividendes/taux_abattement.yaml
pyproject.toml

- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/accueil_personne_agee/plafond.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/pensions_alimentaires/taux_jgt_2006.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/max.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/min.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/taux.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/max.yaml
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpr …

MAJ impot_revenu.calcul_revenus_imposables

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/contributions_assises_specifiquement_accessoires_salaire/forfait_social/taux_reduit_3.yaml
openfisca_france/parameters/prelevements_sociaux/professions_liberales/auto_entrepreneur/formation_professionnelle/artisans_alsace_chiffre_affaires.yaml
openfisca_france/parameters/prelevements_sociaux/professions_liberales/auto_entrepreneur/formation_professionnelle/artisans_hors_alsace_chiffre_affaires.yaml
openfisca_france/parameters/prelevements_sociaux/professions_liberales/auto_entrepreneur/formation_professionnelle/professions_liberales_chiffre_affaires.yaml
openfisca_france/parameters/prelevements_sociaux/professions_liberales/auto_entrepreneur/formation_professionnelle/servicecom_chiffre_affaires.yaml
openfisca_france/parameters/prelevements_sociaux/professions_liberales/auto_entrepreneur/formation_professionnelle/ventecom_chiffre_affaires.yaml
openfisca_france/parameters/prelevements_sociaux/professions_liberales/formation_pl/sous_pss.yaml
pyproject.toml

- openfisca_france/parameters/prelevements_sociaux/professions_liberales/formation_pl/sous_pss.yaml
- openfisca_france/parameters/prelevements_sociaux/professions_liberales/auto_entrepreneur/formation_professionnelle/professions_liberales_chiffre_affaires.yaml
- openfisca_france/parameters/prelevements_sociaux/professions_liberales/auto_entrepreneur/formation_professionnelle/artisans_hors_alsace_chiffre_affaires.yaml
- openfisca_france/parameters/prelevements_sociaux/professions_liberales/auto_entrepreneur/formation_professionnelle/ventecom_chiffre_affaires.yaml
- openfisca_france/parameters/prelevements_sociaux/professions_liberales/auto_entrepreneur/formation_professionnelle/servicecom_chiffre_affaires.yaml
- …

MAJ prelevements_sociaux.professions_liberales

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/bareme_ir_depuis_1945/bareme.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/max.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/min.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/max.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/min.yaml
pyproject.toml

* Périodes concernées : à partir du 01/01/2024.
* Zones impactées : `openfisca_france/parameters/impot_revenu/`.
* Détails :
- Mise à jour des barèmes et seuils pour le calcul de l'IR 2025 sur les revenus 2024.
- - - -
- - - -
Comme chaque année, je sais que ma PR ne sera pas acceptée car il n'y a pas encore de publication au journal officiel, mais les éléments utilisés se basent sur le site du gouvernement : <https://www.economie.gouv.fr/particuliers/tranches-imposition-impot-revenu#>
Personnellement, je ne peux pas me permettre de faire un calcul de l'IR faux pendant 8 mois.

IR 2025 sur les revenus 2024

---

CHANGELOG.md
openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/indice_majore_minimal.yaml
openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/sft/im_plafond.yaml
openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/sft/im_plancher.yaml
openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/sft/part_fixe/deux_enfants.yaml
openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/sft/part_fixe/enfant_supplementaire.yaml
openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/sft/part_fixe/un_enfant.yaml
openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/sft/part_proportionnelle/deux_enfants.yaml
openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/sft/part_proportionnelle/enfant_supplementaire.yaml
openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/sft/part_proportionnelle/trois_enfants.yaml
pyproject.toml

* Zones impactées : `openfisca_france/parameters/marche_travail/remuneration_dans_fonction_publique/sft/*`.
* Détails :
- Mise à jour des références
- - - -
- - - -

[paramètres] last_value_still_valid_on et références pour le SFT

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/microfoncier/plafond_recettes.yaml
openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/microfoncier/taux.yaml
openfisca_france/parameters/marche_travail/primes_exceptionnelles/prime_partage_valeur/plafond_exoneration_avec_accord_interessement.yaml
openfisca_france/parameters/marche_travail/primes_exceptionnelles/prime_partage_valeur/plafond_salaire.yaml
pyproject.toml

- openfisca_france/parameters/marche_travail/primes_exceptionnelles/prime_partage_valeur/*
- openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/microfoncier/*
* Détails :
- Mise à jour des `last_value_still_valid_on`, sur les paramètres dont la nouvelle valeur a pu être trouvée avec un bon niveau de fiabilité.
----
----
Méthodologie :
1. Récupère les paramètres OpenFisca depuis [leximpact-socio-fiscal-openfisca-json](https://git.leximpact.dev/leximpact/leximpact-socio-fiscal-openfisca-json/-/raw/master/raw_processed_parameters.json?ref_type=heads) et les exportent dans un fichier CSV avec une ligne par paramètres.
1. Filtre sur les paramètres qui …

[paramètres] last_value_still_valid_on et références de la PPV et du micro-foncier

---

CHANGELOG.md
openfisca_france/parameters/taxation_capital/prelevements_sociaux/crds/produits_de_placement.yaml
openfisca_france/parameters/taxation_capital/prelevements_sociaux/crds/revenus_du_patrimoine.yaml
openfisca_france/parameters/taxation_capital/prelevements_sociaux/csg/taux_deductible/produits_de_placement.yaml
openfisca_france/parameters/taxation_capital/prelevements_sociaux/csg/taux_deductible/revenus_du_patrimoine.yaml
openfisca_france/parameters/taxation_capital/prelevements_sociaux/csg/taux_global/produits_de_placement.yaml
openfisca_france/parameters/taxation_capital/prelevements_sociaux/csg/taux_global/revenus_du_patrimoine.yaml
pyproject.toml

* Périodes concernées : aucunes.
* Zones impactées : `openfisca_france/parameters/taxation_capital/prelevements_sociaux/*`.
* Détails :
- Mise à jour de la last_value_still_valid_on et des références.
- - - -
- - - -

[paramètres] last_value_still_valid_on pour la CSG et la CRDS

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot_deplafonnees.py
pyproject.toml
tests/calculateur_impots/yaml/reduc_dfppce.yaml

* Périodes concernées : à partir du 01/01/2026.
* Zones impactées : `openfisca_france/model/prelevements_obligatoires/impot_revenu/reductions_impot_deplafonnees.py`.
* Détails :
- Les dons au patrimoine religieux prennent fin le 31 décembre 2025. Le paramètre était bien éteint mais pas dans la variable.
- - - -
- - - -

Date de fin pour dons_patrimoine_religieux

---

.github/lint-changed-yaml-parameters.sh
.github/workflows/workflow.yml
CHANGELOG.md
Makefile
openfisca_france/parameters/marche_travail/salaire_minimum/minstage/taux_gratification_min.yaml
openfisca_france/parameters/marche_travail/salaire_minimum/smic/nb_heures_travail_mensuel.yaml
openfisca_france/parameters/marche_travail/salaire_minimum/smic/smic_b_horaire.yaml
openfisca_france/parameters/marche_travail/salaire_minimum/smic/smic_b_mensuel.yaml
pyproject.toml

- `openfisca_france/parameters/marche_travail/salaire_minimum/smic/smic_b_horaire.yaml`
- `openfisca_france/parameters/marche_travail/salaire_minimum/smic/nb_heures_travail_mensuel.yaml`
- `openfisca_france/parameters/marche_travail/indemnite_fin_contrat/taux.yaml`
- `openfisca_france/parameters/marche_travail/primes_exceptionnelles/prime_partage_valeur/plafond_exoneration.yaml`
* Détails :
- Mise à jour des `last_value_still_valid_on`, des valeurs et des références sur les paramètres qui n'étaient plus à jour et dont la nouvelle valeur a pu être trouvée avec un bon niveau de fiabilité.
- - - -
- - - -
Méthodologie :
1. …

[paramètres] last_value_still_valid_on marché du travail

---

CHANGELOG.md
openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/complementaire_sante/part_employeur.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_secteur_public/retraite/ati/ati.yaml
openfisca_france/parameters/prelevements_sociaux/cotisations_secteur_public/retraite/pension/employeur/civils/pension.yaml
openfisca_france/parameters/prelevements_sociaux/professions_liberales/ret_pl/assurance_vieillesse/entre_1_et_5_pss.yaml
openfisca_france/parameters/prelevements_sociaux/professions_liberales/ret_pl/assurance_vieillesse/sous_1_pss.yaml
pyproject.toml

- `openfisca_france/parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general/casa/pensions_retraite_preretraite_invalidite.yaml`
- `openfisca_france/parameters/prelevements_sociaux/cotisations_secteur_public/retraite/ati/ati.yaml`
- `openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/complementaire_sante/part_employeur.yaml`
- `openfisca_france/parameters/prelevements_sociaux/cotisations_secteur_public/retraite/ati/ati.yaml`
- `openfisca_france/parameters/prelevements_sociaux/cotisations_secteur_public/retraite/pension/employeur/civils/pension.yaml`
- `openfisca_france/parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general/casa/pensions_r …

[paramètres] prélèvements sociaux

---

CHANGELOG.md
openfisca_france/parameters/impot_revenu/calcul_reductions_impots/outremer_investissement/domsoc/retrocession_taux.yaml
openfisca_france/parameters/prestations_sociales/education/bourses/bourses_education/bourse_college/montant_taux_1.yaml
openfisca_france/parameters/prestations_sociales/education/bourses/bourses_education/bourse_college/montant_taux_2.yaml
openfisca_france/parameters/prestations_sociales/education/bourses/bourses_education/bourse_college/montant_taux_3.yaml
openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/abattement_conjoint/abattement_forfaitaire/base.yaml
openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/abattement_conjoint/abattement_forfaitaire/majoration_pac.yaml
openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/travail_ordinaire/abattement_30.yaml
openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/travail_ordinaire/abattement_sup.yaml
openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/travail_ordinaire/plafond_ressources.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_cm_dom/complement_familial_dom/taux_base_dom.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_cm_dom/complement_familial_dom/taux_majore_dom.yaml
openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/patrimoine/abattement_valeur_locative_terrains_non_loues.yaml
openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/patrimoine/taux_interet_forfaitaire_epargne_non_imposable.yaml
pyproject.toml

- openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/patrimoine/abattement_valeur_locative_terrains_non_loues.yaml
- openfisca_france/parameters/prestations_sociales/education/bourses/bourses_education/bourse_college/montant_taux_1.yaml
- openfisca_france/parameters/prestations_sociales/education/bourses/bourses_education/bourse_college/montant_taux_3.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/abattement_conjoint/abattement_forfaitaire/base.yaml
- openfisca_france/parameters/prestations_sociales/prestations_etat_de_sante/invalidite/aah/abattement_conjoint/abattement_forfaitaire/majoration_pac.yaml
- …

[paramètres] Prestations sociales

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
openfisca_france/model/prestations/minima_sociaux/anciens_ms.py
openfisca_france/model/prestations/minima_sociaux/ppa.py
openfisca_france/model/prestations/minima_sociaux/rsa.py
openfisca_france/model/prestations/prestations_familiales/ars.py
openfisca_france/model/prestations/prestations_familiales/asf.py
openfisca_france/model/prestations/prestations_familiales/cf.py
openfisca_france/model/prestations/prestations_familiales/paje.py
pyproject.toml

- `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py`
- `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py`
- `openfisca_france/model/prestations/minima_sociaux/anciens_ms.py`
- `openfisca_france/model/prestations/minima_sociaux/ppa.py`
- `openfisca_france/model/prestations/minima_sociaux/rsa.py`
- `openfisca_france/model/prestations/prestations_familiales/ars.py`
- `openfisca_france/model/prestations/prestations_familiales/asf.py`
- `openfisca_france/model/prestations/prestations_familiales/cf.py`
- `openfisca_france/model/prestations/prestations_familiales/paje.py`
* Détails :
- Ajoute un attribut de classe …

Ajoute un attribut de classe calculate_output_add aux diverses classes crds

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/foyer/al/index.yaml
pyproject.toml

* Périodes concernées : 2025
* Zones impactées : `openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/foyer/al/index.yaml`.
* Détails :
- Corrige le short label des paramètres spécifiques AL en secteur foyer
- - - -
- - - -

Corrige le short label des paramètres spécifiques AL en secteur foyer

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_m/montant_de_base_du_rsa.yaml
pyproject.toml

* Périodes concernées : 2025
- `openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_m/montant_de_base_du_rsa.yaml`.
* Détails :
- Corrige la date de la référence législative pour le RSA (avril 2025)

Corrige la date de la référence législative pour le RSA (avril 2025)

---

openfisca_france/model/prestations/prestations_familiales/paje.py
tests/formulas/paje/paje_cmg.yaml
tests/formulas/paje/paje_cmg_couple.yaml

Dans le simulateur CMG, lorsque les frais de garde sont égaux à 0, on obtient un montant CMG positif.
Le montant de CMG ne pouvant dépasser 85% des frais de garde, le résultat n’est pas cohérent

us: PTD-3275 montant frais de garde nul

---

openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
openfisca_france/model/prestations/pass_culture.py
tests/formulas/paje/paje_cmg_couple.yaml
tests/formulas/ppa/ppa.yaml
tests/formulas/rsa/rsa_celibataire.yaml
tests/formulas/taxe_habitation.yaml
tests/leximpact/2024/couple_1actif_1inactif_0.8_SMIC_3_enfants_d1.yml
tests/leximpact/2024/couple_1actif_1inactif_1.5_SMIC_3_enfants_d2.yml

*  `openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py`
* `openfisca_france\model\prestations\pass_culture.py`
* Détails :
- Correction d'un bug lié au calcul de l'âge. En effet, l'âge étant une variable définie sur un mois (`definition_period = MONTH`) or son calcul se fait au 1er jour du mois. La correction ci-après consiste à faire le calcul au dernier jour du mois.
- Exemple : une famille avec un seul enfant, dont la prise en charge commence le mois de sa naissance. La famille devrait avoir droit à la CMG, mais à cause du bug la simulation …

Mensualisation du calcul de l'age

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
pyproject.toml

* Zones impactées : `openfisca_france/model/prestations/aides_logement.py`.
* Détails :
- Supprime la variable `aides_logement_categorie` qui posait problème dans le dump (car string) pour l'intégrer directement dans le calcul de la variable qui l'appelait
- - - -

supprime la variable aides_logement_categorie

---

CHANGELOG.md
openfisca_france/model/caracteristiques_socio_demographiques/demographie.py
openfisca_france/model/prestations/prestations_familiales/paje.py
pyproject.toml
tests/formulas/paje/paje_adoption.yaml

* Périodes concernées : à partir du 01/01/2004.
* `openfisca_france/model/prestations/prestations_familiales/paje.py`
* `openfisca_france/model/caracteristiques_socio_demographiques/demographie.py`
* Détails :
- Ajout de la variable "paje_adoption" pour le calcul de la prime d'adoption de la PAJE, pour compléter celui de la prime de naissance.
- Ajout de la variable "date_adoption" pour permettre de renseigner la date d'arrivée dans le foyer de l'enfant adopté.
- - - -
- Ajoutent une fonctionnalité.
- - - -

Ajout du calcul de la prime d'adoption PAJE

---

CHANGELOG.md
openfisca_france/model/prestations/aides_logement.py
openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/foyer/k_coef_prise_en_charge/cm_et_r/cm3_apl3.yaml
pyproject.toml
tests/formulas/aides_logement_accedant_eligibilite.yaml
tests/mes-aides.gouv.fr/500E_mois_APL_Zone_1.yaml
tests/mes-aides.gouv.fr/500E_mois_APL_Zone_2.yaml
tests/mes-aides.gouv.fr/500E_mois_APL_Zone_3.yaml
tests/mes-aides.gouv.fr/aides_logement_primo_accedant_AL_Zone_1_450E_mois.yaml
tests/mes-aides.gouv.fr/aides_logement_primo_accedant_APL_Zone_2_650E_mois.yaml
tests/mes-aides.gouv.fr/aides_logement_primo_accedant_dhup.yaml
tests/mes-aides.gouv.fr/testMAcas1_6_couple_accedant_a_la_propriete_AL_1126_E_M_de_salaire_net.yaml

* `openfisca_france/model/prestations/aides_logement.py`
* `openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/foyer/k_coef_prise_en_charge/cm_et_r/cm3_apl3.yaml`
* Détails :
- On a modifié `aides_logement_primo_accedant_eligibilite` afin qu'une règle spécifique à l'éligibilité à l'APL Accession ne soit pas appliquée à l'AL Accession.
- Le calcul du coefficient "K" pour l'APL Accession a été implémenté.
- Les variables `aide_logement_est_pret_conventionne` et `aide_logement_date_pret` ont été créées afin de pouvoir différencier un prêt conventionné d'un prêt qui ne l'est pas. On a quand même gardé la variable `aide_logement_date_pret_conventionne` qui peut être …

feat(PTD-3436): corrections paramètres et calcul APL Accession

---

CHANGELOG.md
openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_cm2/montant/prime_adoption.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_cm2/montant/prime_naissance.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/duree_majoration_plus_de_20_ans.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/maj_age_deux_enfants/age1.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/maj_age_deux_enfants/age2.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/nb_enfants_min_pour_aine_donne_droit_a_majoration.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/nb_enfants_min_pour_majoration_forfaitaire_plus_20ans.yaml
openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/duree_majoration_plus_de_20_ans.yaml
pyproject.toml

* Zones impactées : `openfisca_france/parameters/prestations_sociales/prestations_familiales/*`.
* Détails :
- Mise à jour des `last_value_still_valid_on` et de certaines références.
- - - -
- - - -

Mise à jour des last_value_still_valid_on pour les prestations familiales

---

CHANGELOG.md
openfisca_france/model/prelevements_obligatoires/taxe_habitation/taxe_habitation_import_baremes_locaux.py
openfisca_france/model/prestations/aides_logement.py
openfisca_france/model/prestations/bail_reel_solidaire.py
openfisca_france/scripts/performance/measure_tests_performance.py
pyproject.toml

* Détails :
- Remplace l'usage de `pkg_resources` pas `importlib`
- - - -
[`pkg_resources`](https://setuptools.pypa.io/en/latest/pkg_resources.html) est déprécié et remplacé par `importlib`.
`pkg_resources` n'est pas inclus pas défaut (semble-t-il) avec python 3.12 et donc il faut soit spécifié `setuptools` dans les dépendences d'OpenFisca France (qui importe le module `pkg_resources`) soit migrer à `importlib`.

Remplace pkg_resources par importlib
